#!/bin/ksh
# INSTALLEXTRA


T=testcomsat


: ${LOCAL:=/usr/add-on/local}
: ${EXTRA:=/usr/extra}
export LOCAL EXTRA


install() {
  P=${1}
  D=${2}
  makenewer ${P} ${D}
  chmod +x ${D}/${P}
  chgrp mail ${D}/${P}
  chmod g+s ${D}/${P}
}


rm -f ${T}.s5
cp -p ${T}.x ${T}.s5


N=rca
if pingstat -n $N ; then
  install ${T}.s5 /net/${N}/usr/extra/sbin
fi

N=rcb
if pingstat -n $N ; then
  install ${T}.s5 /net/${N}/usr/extra/sbin
fi



