#!/usr/extra/bin/ksh
# MAKEINSTALL

T=${1}
if [[ -z "${T}" ]] ; then
  T=${PWD##*/}
fi

: ${LOCAL:=/usr/add-on/local}
: ${EXTRA:=/usr/extra}

PRS=" ${LOCAL} /root[01]/${EXTRA} "

for PR in ${PRS} ; do
  if [[ -d ${PR} ]] ; then
    BINDIR=${PR}/bin
    if [[ -d ${BINDIR} ]] && [[ -x ${T}.x ]] ; then
      makenewer -r -o rmsuf ${T}.x ${BINDIR}
    fi
    HELPDIR=${PR}/share/help
    if [[ -d ${HELPDIR} ]] && [[ -r ${T}.help ]] ; then
      makenewer -o rmsuf ${T}.help ${HELPDIR}
    fi
  fi
done


