#!/usr/bin/ksh
# CHANGE


NAMES=
NAMES="${NAMES} cursorinit"


for F in "${@}" ; do

  if [[ -r "${F}" ]] ; then

    for N in ${NAMES} ; do

      if fgrep "${N}" $F > /dev/null ; then

      ed - $F <<\EOF
	g/cursorinit/s//curbegin/g
	g/cursorfree/s//curend/g
	w
	q
EOF

      fi

    done

  fi

done


