From pcs@rca Wed Jul 25 22:59:03 2007 remote from trans.rightcore.com
from:    	POP_administrator <pop>
x-face: 4e38!Aj{9Y%&#(|Xwv7Z[!L{@aCQQwz|dSx&hk0JDM4<(u,F]NH<UwT:1I*eL=qbxC*_Hr&
 Ejazlx/$;B}<e_&h}F5`#B*Kg;\%~\*#f'4}LZc@5W>miwoqB;\uZNEsda/=p&RzNqs`')-z[{?ZK?
 /AH3iN+j@m14R%[Xs/b
to:      	morano@ele.uri.edu
to:		dam@rightcore.com (David Morano)
subject:	test email

This is a test.  This is a test of the emergency email/posting
system.  This is only a test.  This test has been devised
as a means of testing email or bulletin board related operations.
If this had been an actual emergency, you would have been instructed
as to where to send email (for testing purposes !).
This concludes this test of the emergency email/posting system.

PCS Administrator
