#!/usr/extra/bin/ksh
# MAKEINSTALL

TS=${*}
if [[ -z "${TS}" ]] ; then
  TS=${PWD##*/}
fi

EXTS=" a "

PRS=" ${LOCAL} /root[01]/${EXTRA} "

DN=/dev/null
for T in ${TS} ; do
  for E in ${EXTS} ; do
    makeit ${T}.${E} > ${DN}
    if [[ -r ${T}.${E} ]] ; then
      for PR in ${PRS} ; do 
        if [[ -d "${PR}" ]] && [[ -d ${PR}/lib ]] ; then
          mn -r ${T}.${E} ${PR}/lib &
        fi
      done
    fi
  done
done
wait


