'\" t
.nr X
.TH strnlen 3c "1998-01-10" LOCAL
.SH NAME
strnlen \- calculate the length of a string up to a maximum value
.\"_
.SH "SYNOPSIS"
.LP
.BI "int strnlen(const char *" "str" ,
.BI "int " "maxlen" );
.\"_
.SH DESCRIPTION
.IX "strnlen" "" "\fLstrnlen\fP \(em calculate the length of a string"
.B strnlen(\|)
calculate the length of a string (not including any terminating NUL 
character) up to a maximum specified length.
See
.BR strlen (3c) 
for a simpler version of this subroutine.
.\"_
.SH EXAMPLES
.EX
/\(** calculate the length of a string \(**/
int		cl ;
const char	*cp = "hello world!\n" ;
cl = strnlen(cp,10) ;
fprintf(stdout,"len=%d\n",cl) ;
\&\.
\&\.
\&\.
.EE
.\"_
.SH "RETURN VALUES"
This subroutine returns the length of the given string (not including
any possible terminating NUL character) up to a specified maximum value.
.\"_
.SH "SEE ALSO"
.BR strlen (3c),
.BR strlcpy (3c)
.\"_
