From dam Thu Sep 23 14:06:19 1999
Received: (from dam@localhost)
	by rca.rightcore.com (8.8.8+Sun/8.8.8) id OAA06449;
	Thu, 23 Sep 1999 14:06:19 -0400 (EDT)
Date: Thu, 23 Sep 1999 14:06:19 -0400 (EDT)
From: "David A. Morano" <dam>
MIME-Version: 1.0
To: dam
Subject: test
Message-ID: <201_6400_rcaAAAN+q_UAA_1@rca>
Content-type: multipart/mixed;
	boundary="PART.BOUNDARY.201.6400.rca.rcaAAAN+q_UAA.1"
Content-Length: 1214

Hello from PCS (Personal Communication System) !

Your mailer program does not currently support multimedia (MIME) type
email messages.  This part of the email message would not normally be
visible to you if it did.  Some, or most, of this email message may
still be readable to you but in order to view it properly, you should
really pipe this message (using a message piping capability of your
existing mailer program) to another program named 'metamail'.  This
'metamail' program should already be in your PATH if you are using a
PCS mail reader program.  For all PCS mail reader programs, you can
pipe this message to the 'metamail' program with something similar to :

	| metamail -p

The PCS 'msgs' and 'bb' programs are already multimedia ready
(so you should not see this message if you are using one of
those programs).

The rest of this multimedia email message follows :


--PART.BOUNDARY.201.6400.rca.rcaAAAN+q_UAA.1
Content-ID: <201_6400_rcaAAAN+q_UAA_2@rca>
Content-type: text/plain

b

--PART.BOUNDARY.201.6400.rca.rcaAAAN+q_UAA.1
Content-ID: <201_6400_rcaAAAN+q_UAA_3@rca>
Content-type: text/plain ;
	name="sample.txt"

this is a test of clear text

--PART.BOUNDARY.201.6400.rca.rcaAAAN+q_UAA.1--


