Message-ID: <26356.938315339@rca>
Mime-Version: 1.0
Subject: hello there
Content-Type: multipart/mixed; boundary="-"

This is a MIME encoded message.  Decode it with "munpack"
or any other MIME reading software.  Mpack/munpack is available
via anonymous FTP in ftp.andrew.cmu.edu:pub/mpack/
---

this is a test of clear text

---
Content-Type: image/gif; name="binary.gif"
Content-Transfer-Encoding: base64
Content-Disposition: inline; filename="binary.gif"
Content-MD5: Da7QTQXgkXKUzhbNy88NWA==

MQoyIFRoaXMgaXMgc3VwcG9zZWQgdG8gYmUgYSBiaW5hcnkgR0lGIGZpbGUgIQozCg==

-----
