#!/usr/bin/ksh
# MKBIGFILE


integer c=0
integer outer=1 n=100


TFA=/tmp/a${$}
TFB=/tmp/b${$}
TFC=/tmp/c${$}
TFD=/tmp/d${$}

cleanup() {
  rm -f $TFA $TFB $TFC $TFD
}

trap 'cleanup ; exit 1' 1 2 3 15 16 17


    (( c = 0 ))
    while (( c < n )) ; do
      cat main.c
      (( c += 1 ))
    done > $TFA

    (( c = 0 ))
    while (( c < n )) ; do
      cat testbfile.x
      (( c += 1 ))
    done > $TFB



  (( c = 0 ))
  while (( c < outer )) ; do

    cat $TFA $TFB > $TFC
    cat $TFC $TFC > $TFD
    mv $TFC $TFA
    mv $TFD $TFB

      (( c += 1 ))

  done

  cat $TFA $TFB > testfile.in


cleanup





