From bounce.pcconnectionemail.com!bounce-51683_HTML-28835223-1630094-32120-0 Fri Jul 27 14:59:26 EDT 2007 -0400
return-path: received: from cs-ems3.ieee.org (cs-ems3.ieee.org [140.98.193.209])
 by mail.rightcore.com (DAM-MAILER) with ESMTP id 457A96A8AE
 for <dam@rightcore.com>; Fri, 27 Jul 2007 14:59:04 -0400 (EDT)
received: from gemini4.ieee.org (gemini4.ieee.org [140.98.193.189])
 by cs-ems3.ieee.org (8.12.11/8.12.11) with ESMTP id l6RIx5Ya022453
 for <morano@computer.org>; Fri, 27 Jul 2007 14:59:06 -0400
received: from hormel4.ieee.org (hormel4.ieee.org [140.98.193.227])
 by gemini4.ieee.org (Postfix) with ESMTP id A2794205079
 for <morano@computer.org>; Fri, 27 Jul 2007 14:59:06 -0400 (EDT)
received: from mta.pcconnectionemail.com (mta.pcconnectionemail.com 
	[64.132.92.111])
 by hormel4.ieee.org (8.12.11.20060308/8.12.11) with ESMTP id l6RIx5bM026413
 for <morano@computer.org>; Fri, 27 Jul 2007 14:59:05 -0400
received: by mta.pcconnectionemail.com (PowerMTA(TM) v3.2r11) id 
	hl907k0bndon for <morano@computer.org>; Fri, 27 Jul 2007 13:59:05 
	-0500 (envelope-from 
	<bounce-51683_HTML-28835223-1630094-32120-0@bounce.pcconnectionemail.com>)
message-id: <46AA4079.00000032@mta.pcconnectionemail.com>
X-Original-To: dam@rightcore.com
Delivered-To: dam@rightcore.com
DomainKey-Signature: a=rsa-sha1; c=nofws; q=dns; s=200608; 
	d=pcconnectionemail.com;
 b=IXCJNTj3iAVgD1KtN0CybvRecZAoqcznF1va7H95YSVGtfTQlfGJGCDcUy6O8ZLYzuz62A6cK3gd
 oGDkGObOaRQPFLZ4ymq1FTnmrkcy6ICo3I68MrnuiY9UX1ia6BzNt7faGIthfGTkAG9+7l36Ld9v
 WYC6GBLKr9/BpLknP48=;
List-Unsubscribe: 
	<mailto:leave-fce41171736c07122d502d29-fe5e16787d67017f7717-fe9815767664047471-ff071772746604@leave.pcconnectionemail.com>
MIME-Version: 1.0
Reply-To: PC Connection 
	<reply-mpKaGwPs9WY=-51683_HTML-28835223-32120@pcconnectionemail.com>
x-job: 32120_1630094
Content-Type: multipart/alternative;
 boundary="78n581S8oz6Z";
X-Originating-IP: [64.132.92.111]
X-Spam-Score: undef - spam scanning disabled
X-IEEE-UCE-Filter-Settings: morano@computer_society (inherits from 
	90_OPT_OUT,default)
X-Scanned-By: IEEE UCE Filtering Service (uce . ieee . org) on 
	140.98.193.227
From: "PC Connection" <info@pcconnectionemail.com>
To: <morano@computer.org>
Date: Fri, 27 Jul 2007 13:49:57 -0500
Subject: PC Connection - Adobe Creative Suites 3 Is Here - Now In Stock and 
	Shipping

This is a multi-part message in MIME format.

--78n581S8oz6Z
Content-Type: text/plain;
	charset="us-ascii"
Content-Transfer-Encoding: 7bit

-A PC Connection Advertisement-
--------------------------------------------
http://www.pcconnection.com?oext=1160A


Shipping Promotion, On Web Orders Over $249, Hurry, Offer Ends On 7/31/2007 - Click for Details
http://www.pcconnection.com/?oext=1160B


Adobe Creative Suites 3 Is Here - Now In Stock and Shipping
http://www.pcconnection.com/B2C/PM/Brands/Adobe/CreativeSuites/default.htm?oext=1160C


Optimized for Everyday Multitasking
Acer TravelMate TM4230-6433
-  Features a 15.4-inch wide-screen display with razor-sharp resolution, abundant memory and ample storage
-  1.66GHz Intel Core 2 Duo T5500, 1GB DDR2 SDRAM, 120GB hard drive, DVD Super Multi 
-  15.4-inch 1280 x 800 display, Gigabit Ethernet, IEEE 802.11a/b/g, XP Pro, 6.2 lbs., 1-year warranty 
Only $849
#7732351
http://www.pcconnection.com/B2C/PM/Brands/Acer/TravelMate.htm?oext=1160D


Connect, Protect and Simplify 
HP Media Vault Pro mv2040 US
-  Provides small businesses with secure, automatic on-site backup and file sharing - without IT personnel
-  Preserve hard drive images of each PC in your office; use the included software for quick restoration of failed drives
-  Set up access rights for shared directories on your network - you're in charge with the easy-to-use browser-based administration interface
Only $739
#7755529
http://www.pcconnection.com/B2C/PM/Brands/HP/Storage.htm?oext=1160E


$80 Mail-in Rebate!
Vizio 42" Gallevia Widescreen LCD HDTV REFURB
-  Delivers vivid and accurate colors, wide viewing angles (178" x 178") and a blazing 8ms response time
-  With integrated HDTV capabilities, you can enjoy digital programming with enhanced audio and video reproduction
-  Less reflection and glare makes this television ideal in any room lighting situations
Only $669.95*
*After $80 mail-in rebate
#7782762
http://www.pcconnection.com/B2C/PM/Solutions/HotDeal/LCDTVAndPlasmaDeals.htm?oext=1160F


Great Deals on Acer Monitors!
Acer 22" AL2216WBD Analog Digital Widescreen LCD Monitor
-  Ideal for multimedia, gaming and video applications, offering value, versatility and high-performance
-  Ergonomic design features clean, minimal borders with adjustable tilt and wide viewing angles
-  1680 x 1050 maximum resolution, 5ms response time, 700:1 contrast ratio, 300 nits brightness, 170/160-degree viewing angles (H/V), 3-year warranty 
Only $239
#7011079
http://www.pcconnection.com/B2C/PM/Brands/Acer/Monitors.htm?oext=1160G


$50 Instant Savings!
Canon imageCLASS MF3240 Laser Multifunction Printer
-  Laser printer, copier, color scanner and fax in an all-in-one, space-saving unit
-  Generates fast, high-quality laser documents at a fast 21 pages per minute
-  Send and receive faxes using the built-in 33.6 Kbps fax modem; includes eight one-touch speed dial numbers, 100 coded speed dial numbers and more
Only $149.99
#6379787
http://www.pcconnection.com/B2C/PM/Brands/Canon/Printers.htm?oext=1160H


$50 Mail-in Rebate
HP Presario sr2170nx
-  Manage your photos, videos, music, and movies in one convenient location
-  Burn custom, professional-looking labels and artwork on LightScribe-enabled discs, right inside the drive
-  3GHz Intel Pentium 4 631, 1GB DDR2 SDRAM, 160GB hard drive, DVD Super Multi DL, Fast Ethernet, Vista Home Basic, 1-year warranty 
Only $429.95*
*After $50 mail-in rebate
#7773559
http://www.pcconnection.com/B2C/PM/Brands/HP/Desktops.htm?oext=1160I


Perfect Choice for Demanding Applications
Western Digital 80GB Caviar Ultra ATA 100 Internal Hard Drive
-  Ideal for activities requiring high-performance storage, such as computer gaming, digital video editing, and file server applications
-  Uses Western Digital's proven technology and quality manufacturing to deliver outstanding performance and reliability
-  8.9ms average seek time, up to 7200rpm performance, 7200rpm spindle speed, 2MB cache, 1-year warranty 
Only $42.95
#218493
http://www.pcconnection.com/B2C/PM/Brands/WesternDigital/default.htm?oext=1160J


--------------------------------------------
(c)2007 PC Connection. All rights reserved. PC Connection is a trademark of PC Connection, Inc. or its subsidiaries. All other trademarks remain the property of their owners.

You may forward this information to a friend.
http://view.pcconnectionemail.com/ftaf.aspx?j=fe9815767664047471&m=ff071772746604&ls=fe21117475600c787c1d72

You are subscribed with the following e-mail address:
morano@computer.org
Please include this e-mail address in all correspondence.

Click here to unsubscribe or modify your e-mail subscription.
http://pcconnection.hosting.exacttarget.com/webcollect/PCCLanding.aspx?brand=PC&emailaddr=morano@computer.org

PC Connection Attn: Unsubscribe E-mail, 730 Milford Road, Merrimack, NH  03054-4631

If you have any questions about PC Connection's Online Privacy Policy, please check out our web site:
http://www.pcconnection.com/B2C/Content/About/Legal/PrivacyPolicy.htm

Please note that product availability and prices may change:
http://www.pcconnection.com/B2C/Content/About/Legal/LegalNotices.htm


--78n581S8oz6Z
Content-Type: text/html;
	charset="us-ascii"
Content-Transfer-Encoding: 7bit

<img src="http://click.pcconnectionemail.com/open.aspx?ffcb10-fe9815767664047471-fe21117475600c787c1d72-ff071772746604-fef81171736c07-fe5e16787d67017f7717" width="1" height="1">
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<html>
<head>
<title>PC Connection</title>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"></head>


<body marginheight="0" marginwidth="0" topmargin="0" leftmargin="0" bgcolor="#ffffff" text="#000000" link="#2c71b2" alink="#79a101" vlink="#2c71b2">


<!--Insert Header, Shipping Promotion, Deal of the Day and Main Banner-->
<TABLE BORDER=0 WIDTH=600 CELLPADDING=0 CELLSPACING=0>
	<TR>
		<TD align="center" valign="top"><A href="http://click.pcconnectionemail.com/?ju=fe7415707465077e7714&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" >
<IMG WIDTH="600" HEIGHT="100" BORDER="0" src="http://image.pcconnectionemail.com/372003927899.gif" ALT="PC Connection&reg; : we have your brand&#153;"></A><br clear="all">
			<A href="http://click.pcconnectionemail.com/?ju=fe7315707465077e7715&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" >			
<IMG WIDTH="600" HEIGHT="30" BORDER="0" src="http://image.pcconnectionemail.com/9b5e6e60-a.gif" ALT="Shipping Promotion, On Web Orders Over $249, Hurry, Offer Ends On 7/31/2007 &ndash; Click for Details"></A><br clear="all">
			<A href="http://click.pcconnectionemail.com/?ju=fe7215707465077e7716&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" >
<IMG WIDTH="600" HEIGHT="130" BORDER="0" src="http://image.pcconnectionemail.com/0fb31b65-b.gif" ALT="Adobe Creative Suites 3 Is Here &ndash; Now In Stock and Shipping"></A><br clear="all">
		</TD>
	</TR>
</TABLE>


<!-- PRODUCT TABLE SPACERS -->
<table border="0" width="600" cellpadding="0" cellspacing="0">
	<tr>
		<td width=1 bgcolor="#0076be"><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=1 border=0><br clear="all"></td>
		<td width=19><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=19 border=0><br clear="all"></td>
		<td width=120><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=120 border=0><br clear="all"></td>
		<td width=120><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=120 border=0><br clear="all"></td>
		<td width=15><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=15 border=0><br clear="all"></td>
		<td width=305><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=305 border=0><br clear="all"></td>
		<td width=19><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=19 border=0><br clear="all"></td>
		<td width=1 bgcolor="#0076be"><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=1 border=0><br clear="all"></td>
	</tr>
	
	
	<!-- Introduction -->
	
	
	<!-- Slot 1 -->
	<tr>
		<td rowspan="5" bgcolor="#0076be"><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=1 border=0><br clear="all"></td>
		<td rowspan="5"></td>
		<td rowspan="5" align="left" valign="top"><font size="2" face="Verdana, Arial, Helvetica">&nbsp;<br clear="all"></font>
<img src="http://image.pcconnectionemail.com/3700102192822.gif" height=75 width=118 border=0 alt="Acer logo"><br clear="all"></td>
		<td rowspan="4" align="center" valign="top"><font size="2" face="Verdana, Arial, Helvetica">&nbsp;<br clear="all"></font>
<a href="http://click.pcconnectionemail.com/?ju=fe7115707465077e7717&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" > 
<img src="http://image.pcconnectionemail.com/a5d79fcf-c.jpg" height=90 width=90 border=0 alt="Acer TravelMate TM4230-6433"><br clear="all"></a></td>
		<td colspan="2" align="left" valign="top"><font size="2" color="#79a101" face="Verdana, Arial, Helvetica"><B><br>
Optimized for Everyday Multitasking
			</b><br></font><font size="2" color="#2c71b2" face="Verdana, Arial, Helvetica"><b> 
<A href="http://click.pcconnectionemail.com/?ju=fe7015707465077e7710&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" >
Acer TravelMate TM4230-6433
			</a></b><br></font></td>
		<td rowspan="5"></td>
		<td rowspan="5" bgcolor="#0076be"><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=1 border=0><br clear="all"></td>
	</tr><tr>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">&#149;<br></font></td>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">
Features a 15.4-inch wide-screen display with razor-sharp resolution, abundant memory and ample storage
			<br></font></td>
	</tr><tr>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">&#149;<br></font></td>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">
1.66GHz Intel Core 2 Duo T5500, 1GB DDR2 SDRAM, 120GB hard drive, DVD Super Multi 
			<br></font></td>
	</tr><tr>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">&#149;<br></font></td>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">
15.4-inch 1280 x 800 display, Gigabit Ethernet, IEEE 802.11a/b/g, XP Pro, 6.2 lbs., 1-year warranty 
			<br></font></td>
	</tr><tr>
		<td align="center" valign="top"><font size="2" face="Verdana, Arial, Helvetica">
#7732351
			<br></font></td>
		<td colspan="2" align="left" valign="top"><font size="2" color="#ff0000" face="Verdana, Arial, Helvetica"><B>
Only $849
			</b><br><!-- <font size="1" face="Verdana, Arial, Helvetica" color="#666666">

  			<br></font> --><br></font></td>
	</tr>
	
	<tr>
		<td bgcolor="#0076be"></td>
		<td></td>
		<td bgcolor="#666666" colspan="4"><img src="http://image.pcconnectionemail.com/3708169670834.gif" ALT="" width="1" height="1" border="0"><br clear="all"></td>
		<td></td>
		<td bgcolor="#0076be"></td>
	</tr>
	
	
	<!-- Slot 2 -->
	<tr>
		<td rowspan="5" bgcolor="#0076be"><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=1 border=0><br clear="all"></td>
		<td rowspan="5"></td>
		<td rowspan="5" align="left" valign="top"><font size="2" face="Verdana, Arial, Helvetica">&nbsp;<br clear="all"></font>
<img src="http://image.pcconnectionemail.com/3704435569348.gif" height=75 width=118 border=0 alt="HP logo"><br clear="all"></td>
		<td rowspan="4" align="center" valign="top"><font size="2" face="Verdana, Arial, Helvetica">&nbsp;<br clear="all"></font> 
<a href="http://click.pcconnectionemail.com/?ju=fe6f15707465077e7711&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" > 
<img src="http://image.pcconnectionemail.com/ca293d6d-0.jpg" height=90 width=90 border=0 alt="HP Media Vault Pro mv2040 US"><br clear="all"></a></td>
		<td colspan="2" align="left" valign="top"><font size="2" color="#79a101" face="Verdana, Arial, Helvetica"><B><br>
Connect, Protect and Simplify
			</b><br></font><font size="2" color="#2c71b2" face="Verdana, Arial, Helvetica"><b>
<A href="http://click.pcconnectionemail.com/?ju=fe6e15707465077e7712&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" >
HP Media Vault Pro mv2040 US
			</A></b><br></font> </td>
		<td rowspan="5"></td>
		<td rowspan="5" bgcolor="#0076be"><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=1 border=0><br clear="all"></td>
	</tr><tr>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">&#149;<br></font></td>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">
Provides small businesses with secure, automatic on-site backup and file sharing - without IT personnel
			<br></font></td>
	</tr><tr>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">&#149;<br></font></td>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">
Preserve hard drive images of each PC in your office; use the included software for quick restoration of failed drives
			<br></font></td>
	</tr><tr>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">&#149;<br></font></td>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">
Set up access rights for shared directories on your network - you're in charge with the easy-to-use browser-based administration interface
			<br></font></td>
	</tr><tr>
		<td align="center" valign="top"><font size="2" face="Verdana, Arial, Helvetica">
#7755529
			<br></font></td>
		<td colspan="2" align="left" valign="top"><font size="2" color="#ff0000" face="Verdana, Arial, Helvetica"><B>
Only $739
			</b><br><!-- <font size="1" face="Verdana, Arial, Helvetica" color="#666666">

  			<br></font> --><br></font></td>
	</tr>

	
	<tr>
		<td bgcolor="#0076be"></td>
		<td></td>
		<td bgcolor="#666666" colspan="4"><img src="http://image.pcconnectionemail.com/3708169670834.gif" ALT="" width="1" height="1" border="0"><br clear="all"></td>
		<td></td>
		<td bgcolor="#0076be"></td>
	</tr>
	
	
	<!-- Slot 3 -->
	<tr>
		<td rowspan="5" bgcolor="#0076be"><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=1 border=0><br clear="all"></td>
		<td rowspan="5"></td>
		<td rowspan="5" align="left" valign="top"><font size="2" face="Verdana, Arial, Helvetica">&nbsp;<br clear="all"></font>
<img src="http://image.pcconnectionemail.com/61d3dd9c-8.gif" height=75 width=118 border=0 alt="Vizio logo"><br clear="all"></td>
		<td rowspan="4" align="center" valign="top"><font size="2" face="Verdana, Arial, Helvetica">&nbsp;<br clear="all"></font>
<a href="http://click.pcconnectionemail.com/?ju=fe6d15707465077e7713&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" > 
<img src="http://image.pcconnectionemail.com/aea5914b-d.jpg" height=90 width=90 border=0 alt="Vizio 42&quot; Gallevia Widescreen LCD HDTV REFURB"><br clear="all"></a></td>
		<td colspan="2" align="left" valign="top"><font size="2" color="#79a101" face="Verdana, Arial, Helvetica"><B><br>
$80 Mail-in Rebate!
			</b><br></font><font size="2" color="#2c71b2" face="Verdana, Arial, Helvetica"><b>
<A href="http://click.pcconnectionemail.com/?ju=fe6c15707465077e771c&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" >
Vizio 42&quot; Gallevia Widescreen LCD HDTV REFURB
			</A></b><br></font></td>
		<td rowspan="5"></td>
		<td rowspan="5" bgcolor="#0076be"><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=1 border=0><br clear="all"></td>
	</tr><tr>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">&#149;<br></font></td>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">
Delivers vivid and accurate colors, wide viewing angles (178&quot; x 178&quot;) and a blazing 8ms response time
			<br></font></td>
	</tr><tr>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">&#149;<br></font></td>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">
With integrated HDTV capabilities, you can enjoy digital programming with enhanced audio and video reproduction
			<br></font></td>
	</tr><tr>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">&#149;<br></font></td>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">
Less reflection and glare makes this television ideal in any room lighting situations
			<br></font></td>
	</tr><tr>
		<td align="center" valign="top"><font size="2" face="Verdana, Arial, Helvetica">
#7782762
			<br></font></td>
		<td colspan="2" align="left" valign="top"><font size="2" color="#ff0000" face="Verdana, Arial, Helvetica"><B>
Only $669.95*
			</b><br><font size="1" face="Verdana, Arial, Helvetica" color="#666666">
*After $80 mail-in rebate
  			<br></font><br></font></td>
	</tr>

	
	<tr>
		<td bgcolor="#0076be"></td>
		<td></td>
		<td bgcolor="#666666" colspan="4"><img src="http://image.pcconnectionemail.com/3708169670834.gif" ALT="" width="1" height="1" border="0"><br clear="all"></td>
		<td></td>
		<td bgcolor="#0076be"></td>
	</tr>
	
	
	<!-- Slot 4 -->
	<tr>
		<td rowspan="5" bgcolor="#0076be"><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=1 border=0><br clear="all"></td>
		<td rowspan="5"></td>
		<td rowspan="5" align="center" valign="top"><font size="2" face="Verdana, Arial, Helvetica">&nbsp;<br clear="all"></font>
<img src="http://image.pcconnectionemail.com/3700102192822.gif" height=75 width=118 border=0 alt="Acer logo"><br clear="all"></td>
		<td rowspan="4" align="center" valign="top"><font size="2" face="Verdana, Arial, Helvetica">&nbsp;<br clear="all"></font>
<a href="http://click.pcconnectionemail.com/?ju=fe6b15707465077e771d&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" > 
<img src="http://image.pcconnectionemail.com/9d2e597f-5.jpg" height=90 width=90 border=0 alt="Acer 22&quot; AL2216WBD Analog Digital Widescreen LCD Monitor"><br clear="all"></a></td>
		<td colspan="2" align="left" valign="top"><font size="2" color="#79a101" face="Verdana, Arial, Helvetica"><B><br>
Great Deals on Acer Monitors!
			</b><br></font><font size="2" color="#2c71b2" face="Verdana, Arial, Helvetica"><b>
<A href="http://click.pcconnectionemail.com/?ju=fe7315707465077e7614&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" >
Acer 22&quot; AL2216WBD Analog Digital Widescreen LCD Monitor
			</A></b><br></font></td>
		<td rowspan="5"></td>
		<td rowspan="5" bgcolor="#0076be"><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=1 border=0><br clear="all"></td>
	</tr><tr>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">&#149;<br></font></td>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">
Ideal for multimedia, gaming and video applications, offering value, versatility and high-performance
			<br></font></td>
	</tr><tr>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">&#149;<br></font></td>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">
Ergonomic design features clean, minimal borders with adjustable tilt and wide viewing angles
			<br></font></td>
	</tr><tr>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">&#149;<br></font></td>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">
1680 x 1050 maximum resolution, 5ms response time, 700:1 contrast ratio, 300 nits brightness, 170/160-degree viewing angles (H/V), 3-year warranty 
			<br></font></td>
	</tr><tr>
		<td align="center" valign="top"><font size="2" face="Verdana, Arial, Helvetica">
#7011079
			<br></font></td>
		<td colspan="2" align="left" valign="top"><font size="2" color="#ff0000" face="Verdana, Arial, Helvetica"><B>
Only $239
			</b><br><!-- <font size="1" face="Verdana, Arial, Helvetica" color="#666666">

  			<br></font> --><br></font></td>
	</tr>

	
	<tr>
		<td bgcolor="#0076be"></td>
		<td></td>
		<td bgcolor="#666666" colspan="4"><img src="http://image.pcconnectionemail.com/3708169670834.gif" ALT="" width="1" height="1" border="0"><br clear="all"></td>
		<td></td>
		<td bgcolor="#0076be"></td>
	</tr>
	
	
	<!-- Slot 5 -->
	<tr>
		<td rowspan="5" bgcolor="#0076be"><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=1 border=0><br clear="all"></td>
		<td rowspan="5"></td>
		<td rowspan="5" align="left" valign="top"><font size="2" face="Verdana, Arial, Helvetica">&nbsp;<br clear="all"></font>
<img src="http://image.pcconnectionemail.com/5092945707028.gif" height=75 width=118 border=0 alt="Canon logo"><br clear="all"></td>
		<td rowspan="4" align="center" valign="top"><font size="2" face="Verdana, Arial, Helvetica">&nbsp;<br clear="all"></font>
<a href="http://click.pcconnectionemail.com/?ju=fe7215707465077e7615&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" > 
<img src="http://image.pcconnectionemail.com/6a6656c0-b.jpg" height=90 width=90 border=0 alt="Canon imageCLASS MF3240 Laser Multifunction Printer"><br clear="all"></a></td>
		<td colspan="2" align="left" valign="top"><font size="2" color="#79a101" face="Verdana, Arial, Helvetica"><B><br>
$50 Instant Savings!
			</b><br></font><font size="2" color="#2c71b2" face="Verdana, Arial, Helvetica"><b>
<A href="http://click.pcconnectionemail.com/?ju=fe7115707465077e7616&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" >
Canon imageCLASS MF3240 Laser Multifunction Printer
			</a></b></font></td>
		<td rowspan="5"></td>
		<td rowspan="5" bgcolor="#0076be"><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=1 border=0><br clear="all"></td>
	</tr><tr>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">&#149;<br></font></td>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">
Laser printer, copier, color scanner and fax in an all-in-one, space-saving unit
			<br></font></td>
	</tr><tr>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">&#149;<br></font></td>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">
Generates fast, high-quality laser documents at a fast 21 pages per minute
			<br></font></td>
	</tr><tr>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">&#149;<br></font></td>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">
Send and receive faxes using the built-in 33.6 Kbps fax modem; includes eight one-touch speed dial numbers, 100 coded speed dial numbers and more
			<br></font></td>
	</tr><tr>
		<td align="center" valign="top"><font size="2" face="Verdana, Arial, Helvetica">
#6379787
			<br></font></td>
		<td colspan="2" align="left" valign="top"><font size="2" color="#ff0000" face="Verdana, Arial, Helvetica"><B>
Only $149.99
			</b><br><!-- <font size="1" face="Verdana, Arial, Helvetica" color="#666666">

  			<br></font> --><br></font></td>
	</tr>

	
	<tr>
		<td bgcolor="#0076be"></td>
		<td></td>
		<td bgcolor="#666666" colspan="4"><img src="http://image.pcconnectionemail.com/3708169670834.gif" ALT="" width="1" height="1" border="0"><br clear="all"></td>
		<td></td>
		<td bgcolor="#0076be"></td>
	</tr>
	
	
	<!-- Slot 6 -->
	<tr>
		<td rowspan="6" bgcolor="#0076be"><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=1 border=0><br clear="all"></td>
		<td rowspan="6"></td>
		<td rowspan="6" align="left" valign="top"><font size="2" face="Verdana, Arial, Helvetica">&nbsp;<br clear="all"></font>
<img src="http://image.pcconnectionemail.com/3704435569348.gif" height=75 width=118 border=0 alt="HP logo"><br clear="all"></td>
		<td rowspan="5" align="center" valign="top"><font size="2" face="Verdana, Arial, Helvetica">&nbsp;<br clear="all"></font>
<a href="http://click.pcconnectionemail.com/?ju=fe7015707465077e7617&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" > 
<img src="http://image.pcconnectionemail.com/911a09c4-8.jpg" height=90 width=90 border=0 alt="HP Presario sr2170nx"><br clear="all"></a></td>
		<td colspan="2" align="left" valign="top"><font size="2" color="#79a101" face="Verdana, Arial, Helvetica"><B><br>
$50 Mail-in Rebate
			</b><br></font><font size="2" color="#2c71b2" face="Verdana, Arial, Helvetica"><b> 
<A href="http://click.pcconnectionemail.com/?ju=fe6f15707465077e7610&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" >
HP Presario sr2170nx
			</A></b><br></font></td>
		<td rowspan="6"></td>
		<td rowspan="6" bgcolor="#0076be"><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=1 border=0><br clear="all"></td>
	</tr><tr>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">&#149;<br></font></td>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">
Manage your photos, videos, music, and movies in one convenient location
			<br></font></td>
	</tr><tr>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">&#149;<br></font></td>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">
Burn custom, professional-looking labels and artwork on LightScribe-enabled discs, right inside the drive
			<br></font></td>
	</tr><tr>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">&#149;<br></font></td>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">
3GHz Intel Pentium 4 631, 1GB DDR2 SDRAM, 160GB hard drive, DVD Super Multi DL, Fast Ethernet, Vista Home Basic, 1-year warranty 
			<br></font></td>
	</tr><tr>
		<td align="left" valign="top"></td>
		<td align="left" valign="top"></td>
	</tr><tr>
		<td align="center" valign="top"><font size="2" face="Verdana, Arial, Helvetica">
#7773559
			<br></font></td>
		<td colspan="2" align="left" valign="top"><font size="2" color="#ff0000" face="Verdana, Arial, Helvetica"><B>
Only $379.95*
			</b><br><font size="1" face="Verdana, Arial, Helvetica" color="#666666">
*After $50 mail-in rebate
  			<br></font><br></font></td>
	</tr>

	
	<tr>
		<td bgcolor="#0076be"></td>
		<td></td>
		<td bgcolor="#666666" colspan="4"><img src="http://image.pcconnectionemail.com/3708169670834.gif" ALT="" width="1" height="1" border="0"><br clear="all"></td>
		<td></td>
		<td bgcolor="#0076be"></td>
	</tr>
	
	
	<!-- Slot 7 -->
	<tr>
		<td rowspan="6" bgcolor="#0076be"><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=1 border=0><br clear="all"></td>
		<td rowspan="6"></td>
		<td rowspan="6" align="left" valign="top"><font size="2" face="Verdana, Arial, Helvetica">&nbsp;<br clear="all"></font>
<img src="http://image.pcconnectionemail.com/5175794919690.gif" height=75 width=118 border=0 alt="Western Digital logo"><br clear="all"></td>
		<td rowspan="5" align="center" valign="top"><font size="2" face="Verdana, Arial, Helvetica">&nbsp;<br clear="all"></font>
<a href="http://click.pcconnectionemail.com/?ju=fe6e15707465077e7611&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" > 
<img src="http://image.pcconnectionemail.com/61cd89a7-9.jpg" height=90 width=90 border=0 alt="Western Digital 80GB Caviar Ultra ATA 100 Internal Hard Drive"><br clear="all"></a></td>
		<td colspan="2" align="left" valign="top"><font size="2" color="#79a101" face="Verdana, Arial, Helvetica"><B><br>
Perfect Choice for Demanding Applications
			</b><br></font><font size="2" color="#2c71b2" face="Verdana, Arial, Helvetica"><b> 
<A href="http://click.pcconnectionemail.com/?ju=fe6d15707465077e7612&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" >
Western Digital 80GB Caviar Ultra ATA 100 Internal Hard Drive
			</A></b><br></font></td>
		<td rowspan="6"></td>
		<td rowspan="6" bgcolor="#0076be"><img src="http://image.pcconnectionemail.com/3708169670834.gif" height=1 width=1 border=0><br clear="all"></td>
	</tr><tr>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">&#149;<br></font></td>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">
Ideal for activities requiring high-performance storage, such as computer gaming, digital video editing, and file server applications
			<br></font></td>
	</tr><tr>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">&#149;<br></font></td>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">
Uses Western Digital's proven technology and quality manufacturing to deliver outstanding performance and reliability
			<br></font></td>
	</tr><tr>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">&#149;<br></font></td>
		<td align="left" valign="top"><font size="1" face="Verdana, Arial, Helvetica">
8.9ms average seek time, up to 7200rpm performance, 7200rpm spindle speed, 2MB cache, 1-year warranty 
			<br></font></td>
	</tr><tr>
		<td align="left" valign="top"></td>
		<td align="left" valign="top"></td>
	</tr><tr>
		<td align="center" valign="top"><font size="2" face="Verdana, Arial, Helvetica">
#218493
			<br></font></td>
		<td colspan="2" align="left" valign="top"><font size="2" color="#ff0000" face="Verdana, Arial, Helvetica"><B>
Only $42.95
			</b><br><!-- <font size="1" face="Verdana, Arial, Helvetica" color="#666666">

  			<br></font> --><br></font></td>
	</tr>


</table>


<!-- Footer -->
<TABLE cellSpacing=0 cellPadding=0 width=600 border=0>
	<TR>
		<TD BGcolor="#0076be" align="center" valign="middle"><IMG BORDER="0" src="http://image.pcconnectionemail.com/3708169670834.gif" ALT="" width="600" height="1"><br clear="all">
			<IMG BORDER="0" src="http://image.pcconnectionemail.com/3708169670834.gif" ALT="" align="left" width="1" height="17"></TD>
	</TR>
	<TR>
		<TD align="center" valign="top"><font size="1" face="Verdana, Arial, Helvetica, sans-serif" color="#666666"> &copy;2007 PC Connection. All rights reserved. PC Connection is a trademark of PC Connection, Inc.<br>
			or its subsidiaries. All other trademarks remain the property of their owners.<br>
			<BR>
			You may <a href="http://click.pcconnectionemail.com/?ju=fe6c15707465077e7613&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" >forward this information</a> to a friend.<BR>
			<br>
			You are subscribed with the following e-mail address: <br>
			<B>morano@computer.org</b><BR>
			Please include this e-mail address in all correspondence.<BR>
			<BR>
			Click here to <a href="http://click.pcconnectionemail.com/?ju=fe6b15707465077e761c&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" >unsubscribe</a> or <a href="http://click.pcconnectionemail.com/?ju=fe6a15707465077e761d&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" >modify</a> your e-mail subscription.<BR>
			<BR>
			</font>
			<table cellpadding="0" cellspacing="0" width="600" ID="Table5" Border=0>
				<tr>
					<td align=center valign=top><FONT face="Verdana, Arial, Helvetica, sans-serif" color=#666666 size=1> <b>PC Connection</b> Attn: Unsubscribe E-mail, 730 Milford Road Merrimack, NH&nbsp; 03054-4631<br>
						<br>
						</font></td>
				</tr>
			</table>
			<FONT face="Verdana, Arial, Helvetica, sans-serif" color=#cc0000 size=2><B>1-888-800-0323</b></font> <FONT face="Verdana, Arial, Helvetica, sans-serif" color=#666666 size=1> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <A href="http://click.pcconnectionemail.com/?ju=fe7215707465077e7114&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" >Privacy Policy</A> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
<A href="http://click.pcconnectionemail.com/?ju=fe7115707465077e7115&ls=fe21117475600c787c1d72&m=ff071772746604&l=fef81171736c07&s=fe5e16787d67017f7717&jb=ffcf14&t=" >Legal Notices</A><BR>
			<br>
			<br>
			<br>
			<br>
			</font></TD>
	</TR>
</table>
</body>
</html>

--78there is a thing
