X-Apparently-To: weehawker59@yahoo.com via 209.191.125.91; Tue, 07 Nov 2006 17:13:05 -0800
X-Originating-IP: [216.49.160.74]
Authentication-Results: mta336.mail.mud.yahoo.com  from=davtv.com; domainkeys=neutral (no sig)
Received: from 216.49.160.74  (EHLO mail4.islc.net) (216.49.160.74)
  by mta336.mail.mud.yahoo.com with SMTP; Tue, 07 Nov 2006 17:13:04 -0800
Received: (qmail 24599 invoked by uid 90); 8 Nov 2006 01:13:04 -0000
Received: by simscan 1.2.0 ppid: 24593, pid: 24595, t: 0.4973s
         scanners: attach: 1.2.0 clamav: 0.88.4/m:40/d:2126
Received: from unknown (HELO mail.davtv.com) (12.156.250.3)
  by 0 with SMTP; 8 Nov 2006 01:13:03 -0000
Received: from PerkysEngine (12-156-251-9.davtv.com [12.156.251.9])
	by mail.davtv.com (Postfix) with SMTP id CCC60365742;
	Tue,  7 Nov 2006 20:13:02 -0500 (EST)
From: "Bob Perkins" <rperkins@davtv.com>
To: <Undisclosed-Recipient:;>
Subject: Fw: LETTER FROM A FARM KID
Date: Tue, 7 Nov 2006 20:13:02 -0500
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="----=_NextPart_000_0064_01C702A9.20DA6260"
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 6.00.2900.2869
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2900.2962

This is a multi-part message in MIME format.

------=_NextPart_000_0064_01C702A9.20DA6260
Content-Type: text/plain;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable


----- Original Message -----=20
Sent: Friday, November 03, 2006 5:39 AM
Subject: LETTER FROM A FARM KID


LETTER FROM A FARM KID,=20
(NOW AT SAN DIEGO MARINE CORPS RECRUIT TRAINING)=20

Dear Ma and Pa,=20
I am well. Hope you are. Tell Brother Walt and Brother Elmer the Marine =
Corps beats working for old man Minch by a mile. Tell them to join up =
quick before all of the places are filled.=20





I was restless at first because you got to stay in bed till nearly 6 =
a.m. but I am getting so I like to sleep late. Tell Walt and Elmer all =
you do before breakfast is smooth your cot, and shine some things. No =
hogs to slop, feed to pitch, mash to mix, wood to split, fire to lay. =
Practically nothing.=20





Men got to shave but it is not so bad, there's warm water. Breakfast is =
strong on trimmings like fruit juice, cereal, eggs, bacon, etc., but =
kind of weak on chops, potatoes, ham, steak, fried eggplant, pie and =
other regular food, but tell Walt and Elmer you can always sit by the =
two city boys that live on coffee. Their food plus yours holds you until =
noon when you get fed again. It's no wonder these city boys can't walk =
much.=20

We go on "route marches," which the platoon sergeant says are long walks =
to harden us. If he thinks so, it's not my place to tell him different. =
A "route march" is about as far as to our mailbox at home. Then the city =
guys get sore feet and we all ride back in trucks.=20

The country is nice but awful flat The sergeant is like a school =
teacher. He nags a lot. The Captain is like the school board. Majors and =
colonels just ride around and frown. They don't bother you none.=20





This next will kill Walt and Elmer with laughing. I keep getting medals =
for shooting. I don't know why. The bulls-eye is near as big as a =
chipmunk head and don't move, and it ain't shooting at you like the =
Higgett boys at home. All you got to do is lie there all comfortable and =
hit it. You don't even load your own cartridges. They come in boxes.=20





Then we have what they call hand-to-hand combat training. You get to =
wrestle with them city boys. I have to be real careful though, they =
break real easy. It ain't like fighting with that ole bull at home. I'm =
about the best they got in this except for that Tug Jordan from over in =
Silver Lake. I only beat him once. He joined up the same time as me, but =
I'm only 5'6" and 130 pounds and he's 6'8" and near 300 pounds dry.=20





Be sure to tell Walt and Elmer to hurry and join before other fellers =
get onto this setup and come stampeding in.=20

Your loving daughter,=20
Alice

Mike and Linda
------=_NextPart_000_0064_01C702A9.20DA6260
Content-Type: text/html;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML XMLNS:U1 XMLNS:ST1><HEAD>
<META http-equiv=3DContent-Type content=3D"text/html; =
charset=3Diso-8859-1">
<META content=3D"MSHTML 6.00.2900.2963" name=3DGENERATOR>
<STYLE></STYLE>
</HEAD>
<BODY id=3Drole_body style=3D"FONT-SIZE: 10pt; COLOR: #000000; =
FONT-FAMILY: Arial"=20
bottomMargin=3D7 bgColor=3D#ffffff leftMargin=3D7 topMargin=3D7 =
rightMargin=3D7>
<DIV>&nbsp;</DIV>
<DIV style=3D"FONT: 10pt arial">----- Original Message -----=20
<DIV><B>Sent:</B> Friday, November 03, 2006 5:39 AM</DIV>
<DIV><B>Subject:</B> LETTER FROM A FARM KID</DIV></DIV>
<DIV><BR></DIV><FONT id=3Drole_document face=3DArial color=3D#000000 =
size=3D2>
<DIV><SPAN=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; COLOR: rgb(0,0,255); =
FONT-FAMILY: 'Comic Sans MS'"><SPAN=20
class=3DApple-style-span=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; COLOR: rgb(0,0,255); =
FONT-FAMILY: Comic Sans MS">LETTER=20
FROM A FARM KID,</SPAN></SPAN><FONT face=3DVerdana color=3Dblack =
size=3D2><SPAN=20
style=3D"FONT-SIZE: 13px; COLOR: black; FONT-FAMILY: Verdana"><SPAN=20
class=3DApple-style-span style=3D"FONT-SIZE: 13px; FONT-FAMILY: =
Verdana">=20
</SPAN></SPAN></FONT><B=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 10px; FONT-FAMILY: Arial"><FONT=20
face=3D"Comic Sans MS" color=3Dblack size=3D4><SPAN=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 18px; COLOR: black; FONT-FAMILY: =
'Comic Sans MS'"><BR=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 18px; FONT-FAMILY: Comic Sans =
MS"><SPAN=20
class=3DApple-style-span=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 18px; FONT-FAMILY: Comic Sans =
MS">(NOW AT=20
</SPAN><U1:CITY u2:st=3D"on"><U1:PLACE u2:st=3D"on"><ST1:CITY =
w:st=3D"on"><ST1:PLACE=20
w:st=3D"on"><SPAN class=3DApple-style-span=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 18px; FONT-FAMILY: Comic Sans =
MS">SAN=20
DIEGO</SPAN></ST1:PLACE></ST1:CITY></U1:PLACE></U1:CITY><SPAN=20
class=3DApple-style-span=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 18px; FONT-FAMILY: Comic Sans =
MS"> MARINE=20
CORPS RECRUIT TRAINING) </SPAN><BR=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 18px; FONT-FAMILY: Comic Sans =
MS"></SPAN></FONT></B><FONT=20
face=3D"Comic Sans MS" color=3Dblack size=3D6><SPAN=20
style=3D"FONT-SIZE: 32px; COLOR: black; FONT-FAMILY: 'Comic Sans =
MS'"><BR=20
style=3D"FONT-SIZE: 32px; FONT-FAMILY: Comic Sans MS"><SPAN =
class=3DApple-style-span=20
style=3D"FONT-SIZE: 32px; FONT-FAMILY: Comic Sans MS">Dear Ma and Pa, =
</SPAN><BR=20
style=3D"FONT-SIZE: 32px; FONT-FAMILY: Comic Sans MS"><SPAN =
class=3DApple-style-span=20
style=3D"FONT-SIZE: 32px; FONT-FAMILY: Comic Sans MS">I am well. Hope =
you are.=20
Tell Brother Walt and Brother Elmer the Marine Corps beats working for =
old man=20
</SPAN><U1:PLACE u2:st=3D"on"><ST1:PLACE w:st=3D"on"><SPAN =
class=3DApple-style-span=20
style=3D"FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS">Minch</SPAN></ST1:PLACE></U1:PLACE><SPAN=20
class=3DApple-style-span style=3D"FONT-SIZE: 32px; FONT-FAMILY: Comic =
Sans MS"> by a=20
mile. Tell them to join up quick before all of the places are filled.=20
</SPAN></SPAN></FONT><FONT face=3DArial color=3Dblack><SPAN=20
style=3D"FONT-SIZE: 10px; COLOR: black; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"></SPAN></FONT><B=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 10px; FONT-FAMILY: Arial"><FONT=20
face=3D"Comic Sans MS" color=3Dblack size=3D6><SPAN=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; COLOR: black; FONT-FAMILY: =
'Comic Sans MS'"><BR=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS"><SPAN=20
class=3DApple-style-span=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS">I was=20
restless at first because you got to stay in bed till nearly 6 a.m. but =
I am=20
getting so I like to sleep late. Tell Walt and Elmer all you do before =
breakfast=20
is smooth your cot, and shine some things. No hogs to slop, feed to =
pitch, mash=20
to mix, wood to split, fire to lay. Practically nothing.=20
</SPAN></SPAN></FONT></B><FONT face=3DArial color=3Dblack><SPAN=20
style=3D"FONT-SIZE: 10px; COLOR: black; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"></SPAN></FONT><B=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 10px; FONT-FAMILY: Arial"><FONT=20
face=3D"Comic Sans MS" color=3Dblack size=3D6><SPAN=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 24px; FONT-FAMILY: Comic Sans MS; =
FONT-FAMIL: 'Comic Sans MS'"><SPAN=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; COLOR: black; FONT-FAMILY: =
'Comic Sans MS'"><BR=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS"><SPAN=20
class=3DApple-style-span=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS">Men got=20
to shave but it is not so bad, there's warm water. Breakfast is strong =
on=20
trimmings like fruit juice, cereal, eggs, bacon, etc., but kind of weak =
on=20
chops, potatoes, ham, steak, fried eggplant, pie and other regular food, =
but=20
tell Walt and Elmer you can always sit by the two city boys that live on =
coffee.=20
Their food plus yours holds you until noon when you get fed again. It's =
no=20
wonder these city boys can't walk much. </SPAN><BR=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS"><BR=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS"><SPAN=20
class=3DApple-style-span=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS">We go on=20
"route marches," which the platoon sergeant says are long walks to =
harden us. If=20
he thinks so, it's not my place to tell him different. A "route march" =
is about=20
as far as to our mailbox at home. Then the city guys get sore feet and =
we all=20
ride back in trucks. </SPAN><BR=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS"><BR=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS"><SPAN=20
class=3DApple-style-span=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS">The=20
country is nice but awful flat The sergeant is like a school teacher. He =
nags a=20
lot. The Captain is like the school board. Majors and colonels just ride =
around=20
and frown. They don't bother you none. =
</SPAN></SPAN></SPAN></FONT></B><FONT=20
face=3DArial color=3Dblack><SPAN s=3D"" tyle=3D"COLOR: black; =
FONT-FAMILY: Arial"><SPAN=20
style=3D"FONT-SIZE: 10px; COLOR: black; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"></SPAN></SPAN></FONT><B=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 10px; FONT-FAMILY: Arial"><FONT=20
face=3D"Comic Sans MS" color=3Dblack size=3D6><SPAN=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; COLOR: black; FONT-FAMILY: =
'Comic Sans MS'"></SPAN><BR=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 24px; FONT-FAMILY: Comic Sans =
MS"><SPAN=20
class=3DApple-style-span=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 24px; FONT-FAMILY: Comic Sans =
MS">This next=20
will kill Walt and Elmer with laughing. I keep getting medals for =
shooting. I=20
don't know why. The bulls-eye is near as big as a chipmunk head and =
don't move,=20
and it ain't shooting at you like the Higgett boys at home. All you got =
to do is=20
lie there all comfortable and hit it. You don't even load your own =
cartridges.=20
They come in boxes. </SPAN></FONT></B><FONT face=3DArial =
color=3Dblack><SPAN=20
style=3D"FONT-SIZE: 10px; COLOR: black; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"></SPAN></FONT><B=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 10px; FONT-FAMILY: Arial"><FONT=20
face=3D"Comic Sans MS" color=3Dblack size=3D6><SPAN=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; COLOR: black; FONT-FAMILY: =
'Comic Sans MS'"><BR=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS"><SPAN=20
class=3DApple-style-span=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS">Then we=20
have what they call hand-to-hand combat training. You get to wrestle =
with them=20
city boys. I have to be real careful though, they break real easy. It =
ain't like=20
fighting with that ole bull at home. I'm about the best they got in this =
except=20
for that Tug </SPAN><U1:COUNTRY-REGION u2:st=3D"on"><ST1:COUNTRY-REGION=20
w:st=3D"on"><SPAN class=3DApple-style-span=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS">Jordan</SPAN></ST1:COUNTRY-REGION></U1:COUNTRY-REGION><SPAN=20
class=3DApple-style-span=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS"> from=20
over in </SPAN><U1:PLACE u2:st=3D"on"><U1:PLACENAME =
u2:st=3D"on"><ST1:PLACE=20
w:st=3D"on"><ST1:PLACENAME w:st=3D"on"><SPAN class=3DApple-style-span=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS">Silver</SPAN></ST1:PLACENAME></ST1:PLACE></U1:PLACENAME><SPAN=20
class=3DApple-style-span=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS">=20
</SPAN><U1:PLACETYPE u2:st=3D"on"><ST1:PLACETYPE w:st=3D"on"><SPAN=20
class=3DApple-style-span=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS">Lake</SPAN></ST1:PLACETYPE></U1:PLACETYPE></U1:PLACE><SPAN=20
class=3DApple-style-span=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS">. I only=20
beat him once. He joined up the </SPAN><ST1:PERSONNAME w:st=3D"on"><SPAN =

class=3DApple-style-span=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS">sam</SPAN></ST1:PERSONNAME><SPAN=20
class=3DApple-style-span=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS">e time as=20
me, but I'm only 5'6" and 130 pounds and he's 6'8" and near 300 pounds =
dry.=20
</SPAN></SPAN></FONT></B><FONT face=3DArial color=3Dblack><SPAN=20
style=3D"FONT-SIZE: 10px; COLOR: black; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"><BR=20
style=3D"FONT-SIZE: 10px; FONT-FAMILY: Arial"></SPAN></FONT><B=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 10px; FONT-FAMILY: Arial"><FONT=20
face=3D"Comic Sans MS" color=3Dblack size=3D6><SPAN=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; COLOR: black; FONT-FAMILY: =
'Comic Sans MS'"><BR=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS"><SPAN=20
class=3DApple-style-span=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS">Be sure=20
to tell Walt and Elmer to hurry and join before other fellers get onto =
this=20
setup and come stampeding in. </SPAN><BR=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS"><BR=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS"><SPAN=20
class=3DApple-style-span=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS">Your=20
loving daughter,</SPAN></SPAN></FONT></B><FONT face=3D"Comic Sans MS" =
color=3Dblack=20
size=3D2><SPAN=20
style=3D"FONT-SIZE: 13px; COLOR: black; FONT-FAMILY: 'Comic Sans =
MS'"><SPAN=20
class=3DApple-style-span style=3D"FONT-SIZE: 13px; FONT-FAMILY: Comic =
Sans MS">=20
</SPAN></SPAN></FONT><B=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 10px; FONT-FAMILY: Arial"><FONT=20
face=3D"Comic Sans MS" color=3Dblack size=3D6><SPAN=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; COLOR: black; FONT-FAMILY: =
'Comic Sans MS'"><BR=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS"><SPAN=20
class=3DApple-style-span=20
style=3D"FONT-WEIGHT: bold; FONT-SIZE: 32px; FONT-FAMILY: Comic Sans =
MS">Alice</SPAN></SPAN></FONT></B></DIV>
<DIV>&nbsp;</DIV>
<DIV><FONT lang=3D0 face=3D"Edmunds Distressed" size=3D3 =
PTSIZE=3D"12"><B>Mike and=20
Linda</B></FONT></DIV></FONT></BODY></HTML>

------=_NextPart_000_0064_01C702A9.20DA6260--
