reply-to: morano@computer.org, morano@ele.uri.edu, morano@ieee.org,
 timothy.bevin@mercer.com (Tim Bevin),
 acarpenito@juno.com (Arthur Carpenito),
 busterjoe@afo.net (Larry Cecchi),
 ljc@afo.net,
From: morano@computer.org (David Morano),
 timothy.bevin@mercer.com (Tim Bevin),
 acarpenito@juno.com (Arthur Carpenito),
 busterjoe@afo.net (Larry Cecchi),
 ljc@afo.net,
to: rondayle@juno.com (Pastor Johnson),
 timothy.bevin@mercer.com (Tim Bevin),
 acarpenito@juno.com (Arthur Carpenito),
 busterjoe@afo.net (Larry Cecchi),
 ljc@afo.net,
 ddrost@PEACE.GORDON.EDU,
 esilver@comcast.net ,
x-bcc: zerotheigenvector@yahoo.com
Subject: parts of Bible not true !

Apparently the Roman Catholic Church in Britain has just figured out
that some parts of the Bible are NOT true (article attached) !

I do not know the the rest of the Roman Catholic Church worldwide thinks
about this.  But somehow, I don't think that there will be anything like
an uproar over this.

Dave M.

