From morano Mon Oct 24 12:32:45 EDT 2005 -0400
return-path: <rondayle@juno.com>
received: from orca.ele.uri.edu
	by localhost with POP3 (fetchmail-6.2.5)
	for morano@localhost (single-drop); Mon, 24 Oct 2005 12:32:45 -0400 (EDT)
received:  from leviathan.ele.uri.edu (leviathan [131.128.51.64])
	by ele.uri.edu (Cyrus v2.2.3) with LMTP; Mon, 24 Oct 2005 12:32:05 -0400
received:  from engine.ieee.org (engine.ieee.org [140.98.193.23])
	by leviathan.ele.uri.edu (8.12.9/8.12.9) with ESMTP id j9OGVs4r013492
	for <morano@ele.uri.edu>; Mon, 24 Oct 2005 12:31:55 -0400 (EDT)
received:  from gemini3.ieee.org (gemini3.ieee.org [140.98.193.188])
	by engine.ieee.org (Switch-3.1.2/Switch-3.1.2) with ESMTP id j9OGVj4g000004
	for <morano@ieee.org>; Mon, 24 Oct 2005 12:31:46 -0400 (EDT)
received:  from hormel5.ieee.org (hormel5.ieee.org [140.98.193.228])
	by gemini3.ieee.org (Postfix) with ESMTP id D510A39C16
	for <morano@ieee.org>; Mon, 24 Oct 2005 12:31:45 -0400 (EDT)
received:  from outbound-mail.lax.untd.com (outbound-mail.lax.untd.com [64.136.28.164])
	by hormel5.ieee.org (8.12.11/8.12.11) with SMTP id j9OGVDta009195
	for <morano@ieee.org>; Mon, 24 Oct 2005 12:31:14 -0400
received:  from webmail25.lax.untd.com (webmail25.lax.untd.com [10.131.27.165])
	by smtpout05.lax.untd.com with SMTP id AABBX4DCQABQ39TS
	for <morano@ieee.org> (sender <rondayle@juno.com>);
	Mon, 24 Oct 2005 09:31:10 -0700 (PDT)
received:  (from rondayle@juno.com) 
	by webmail25.lax.untd.com (jqueuemail) id K74EJMH8; Mon, 24 Oct 2005 09:30:41 PDT
received:  from [151.199.22.3] by webmail25.lax.untd.com with HTTP:
	Mon, 24 Oct 2005 16:30:20 GMT
content-length: 7448            
message-id: <20051024.093041.16784.4456@webmail25.lax.untd.com>
X-Sieve: CMU Sieve 2.2
X-Originating-IP: [151.199.22.3]
Mime-Version: 1.0
X-Mailer: Webmail Version 4.0
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline
Content-Type: text/plain
X-ContentStamp: 4:6:2165936585
X-UNTD-OriginStamp: mkNHgeD7Hyz6In0PLkVkDAuuTZVV093NWC6wKVe9CrH7xan0VtCTIA==
X-UNTD-Peer-Info: 10.131.27.165|webmail25.lax.untd.com|webmail25.lax.untd.com|rondayle@juno.com
X-UCE-Filter-Settings: morano redirected to 90_OPT_OUT
X-Spam-Score: undef - spam-scanning disabled
X-Scanned-By: IEEE UCE Filtering Service (uce . ieee . org) on 140.98.193.228
X-Spam-Level: **
X-Spam-Status: NO ; VERY LOW ; 2.10
X-Spam-Report: 2.10 hits
	1.7 FORGED_JUNO_RCVD       'From' juno.com does not match 'Received' headers
	0.4 DNS_FROM_RFC_ABUSE     RBL: Envelope sender in abuse.rfc-ignorant.org
From: "rondayle@juno.com" <rondayle@juno.com>
To: morano@acm.org, morano@ele.uri.edu, morano@ieee.org
Date: Mon, 24 Oct 2005 16:30:20 GMT
Subject: Articles

Hi Dave,
I thought you might like to read the column I wrote for the local paper =
after 911.  I wrote it on Oct 1/01 so it would have appeared in the Satu=
rday paper after that date.  I also included one I wrote in 2002 after t=
he court in CA said "god" in the pledge of allegiance was illegal. =

Ron

What Would Jesus Say?
	What would Jesus say to you in light of the events of September 11, 200=
1?  Thankfully, He answered those who asked Him about a known atrocity w=
hen He walked the earth, =93There were present at that season some that =
told him of the Galilaeans, whose blood Pilate had mingled with their sa=
crifices. 2 And Jesus answering said unto them, Suppose ye that these Ga=
lilaeans were sinners above all the Galilaeans, because they suffered su=
ch things? 3 I tell you, Nay: but, except ye repent, ye shall all likewi=
se perish. 4 Or those eighteen, upon whom the tower in Siloam fell, and =
slew them, think ye that they were sinners above all men that dwelt in J=
erusalem? 5 I tell you, Nay: but, except ye repent, ye shall all likewis=
e perish.=94 (Luke 13:1-5)
	To paraphrase Jesus=92 words in light of September 11, =93Or those 100'=
s whose blood the hijackers mingled with their own were they worse sinne=
rs than all other sinners living in America, because they suffered such =
things?  I tell you, No, but unless you repent You shall all likewise pe=
rish.  Or those 1000's, upon whom the World Trade Center Towers in New Y=
ork fell, and killed, do you think  that they were worse sinners than al=
l others who dwell in America?  I tell you, No, but except you repent, y=
ou shall all likewise perish.=94
	Why, when asked about an atrocity and then mentioning a known calamity,=
 does the Lord Jesus Christ call you to repentance?  Because that is wha=
t you and I need to hear!  Repentance is a gift of the One Living And Tr=
ue God, Father, Son and Holy Spirit whereby you are enabled to turn in t=
rue sorrow and shame from your sins and receive, through His free grace,=
 the gift of faith whereby you are enabled to embrace the Lord Jesus Chr=
ist as your only Lord and your only Saviour. (Ephesians 2:8-10)
	But, why does Jesus call you to repentance?  Why should this nation and=
 its citizens that have felt the Sovereign Hand of God in Judgment repen=
t?  (If you doubt that God was not Sovereign over the events of Septembe=
r 11, 2001 you need to read Isaiah 45:7; Amos 3:6 and Proverbs 21:1.)
	Why?  As a nation, has it unashamedly acknowledged the truth of Who the=
 LORD Jesus Christ is?  That He is the only Saviour of Sinners, Acts 4:1=
2; John 14:6; and Almighty God, John 8:24,58; Phil. 2:8-11.  It has not!=
  All in this nation who would chaff at replacing the words, =93God Bles=
s America=94 with the words, =93The LORD Jesus Christ Bless America=94 s=
how how great is the need of repentance.  Unless you repent living Ameri=
can you will perish for denying your need of the LORD Jesus Christ and W=
ho He is.
	Why?  As a nation, has it protected its most defenseless citizens?  Not=
 since Roe vs. Wade!  While our Creator God knits children together in t=
he womb Psalm 139:13,14  this nation has protected those who have become=
 experts at dismembering them.  We express outrage at the Taliban for pr=
otecting Osama Ben Laden.  Yet this nation has protected abortionists fo=
r much longer!  Unless you repent living American you will perish!
	Why? As a nation, has it embraced the Lord=92s teaching on God honoring=
 sexual relationships and practice?  It has not!  Both inside and outsid=
e the church His teaching is rejected, Mark 10:2-12.  This nation protec=
ts perversion by perverting the intention of the First Amendment!  Unles=
s you repent living American you will perish!  May the living God give y=
ou the wisdom to hear and heed what Jesus says to you in light of Septem=
ber 11, 2001.

One Nation Under........ Atheism is Alive and Well in The United States.=
  =

The recent decision by the 9th  circuit court in California has caused n=
o small amount of concern to many in this country.  It has not done so f=
or me and I will explain why.  This country is functionally atheistic an=
d idolatrous.  The One Living and True God is the Creator and Sustainer =
of all that is, yet this truth is not allowed in the public school syste=
ms of this land.  It is nothing but hypocrisy to say =93one nation under=
 God=94 and yet refuse to teach the children of this nation what is True=
 about Him and blaspheme Him with the science fiction called evolution. =
 But this country is also functionally idolatrous.  For, the Living God =
has the audacity to define and reveal who He is and reveal the only way =
 He can be known, yet the three letters g-o-d have become user definable=
 in this country.  The First Commandment says =93Thou Shalt Have no othe=
r gods before Me.=94  In this commandment the One Living and True God, w=
ho has declared who He is in Exodus 3:14, declares that His people are t=
o worship no other =93gods=94.  In fact, based on other verses in His Wo=
rd, The One Living and True God declares all other =93gods=94 to be fals=
e.(Psalm 115:1-8) A better term for them would be idols - idols that hav=
e no existence, and based on what God says in 1 Corinthians 10, are actu=
ally demonic deceptions! (1 Cor. 10:20) The God who exists is not politi=
cally correct!  The True God was not tolerant of the =93gods=94 of the E=
gyptians and He is not tolerant of the fill in the blank =93gods=94 embr=
aced by American idolaters today.  A word that can have whatever meaning=
 you want essentially has no meaning whatsoever.  Theistic pluralists an=
d atheists share the same bed in their denial of the One Living and True=
 God.  Many in this country today are offended at this attempt to remove=
 the three letters g-o-d out of the pledge of allegiance.  But the remov=
al of these 3 letters does not remove the one living and true God from b=
eing over all nations - including the United States.  I would go so far =
as to say that it does not bother the true God that this has happened.  =
He has clearly declared in His Word that He will not share His Glory wit=
h anything or anyone else.(Isa. 42:8)  For if the =93god=94 being referr=
ed to in the statement =93one nation under god=94 is not the one living =
and true God who exists, it would be better to not use the word than exp=
ress our idolatry before the One who has said you are to have no other g=
ods before Him.   Theistic or religious pluralism is simply another name=
 for idolatry.  There is only One God.  He is Sovereign over all things =
- including those who try to deny He exists.  He is monotheistic in esse=
nce and triune in nature.  All those who deny that Jesus Christ is God a=
re denying and dishonoring the only true God. (John 5:23; 8:24)  The onl=
y way that the One God who exists can be known is through the Son. (Matt=
. 11:27)  And the degree to which this country has embraced idolatry is =
easily seen.  If you chafe, get offended at, or call it intolerant to sa=
y One Nation Under the LORD Jesus Christ you are manifesting your ignora=
nce of who God is, Who He has perfectly and finally revealed Himself thr=
ough and how He alone can be known. You are intolerant of the One Living=
 and True God and He is intolerant of your idolatry.  Flee to the Son in=
 repentance and faith and be reconciled to the true God through Him befo=
re it is too late. 

