#!/usr/bin/ksh
# CHANGE


NAMES=
NAMES="${NAMES} INFNAME OUTFNAME ERRFNAME"


DN=/dev/null
PF=/tmp/pf${$}

function cleanup {
  rm -f ${PF}
}

trap 'cleanup ; exit 1' 1 2 3 15 16 17

for N in ${NAMES} ; do
  print -- ${N}
done > ${PF}


for F in "${@}" ; do

  if [[ -r "${F}" ]] ; then

      print -u2 -- "${0}: file=${F} str=${N}"

      if fgrep -f ${PF} ${F} > ${DN} ; then

      ed - $F <<\EOF
	g/STDINFNAME/s//STDINxFNAME/g
	g/STDOUTFNAME/s//STDOUTxFNAME/g
	g/STDERRFNAME/s//STDERRxFNAME/g
	g/STDSTDINFNAME/s//STDINxFNAME/g
	g/STDSTDOUTFNAME/s//STDOUTxFNAME/g
	g/STDSTDERRFNAME/s//STDERRxFNAME/g
	g/INFNAME/s//STDINxFNAME/g
	g/OUTFNAME/s//STDOUTxFNAME/g
	g/ERRFNAME/s//STDERRxFNAME/g
	w
	q
EOF

      fi

  fi

done

cleanup



