#!/usr/bin/ksh
# MAKEINSTALL-ALL


T=mkindexing


: ${LOCAL:=/usr/add-on/local}
export LOCAL

if [[ $# -gt 0 ]] ; then
  BINDIR=${1}
else
  BINDIR=${LOCAL}/bin
fi


ALL="mkindexing mkkey mkinv mkquery mktagprint "


if [[ ! -r ${T}.x ]] ; then
  make
fi

for F in ${ALL} ; do
  rm -f ${BINDIR}/${F}
  rm -f ${F}
  ln -f ${T}.x ${F}
done

find ${ALL} -print | cpio -pdmu ${BINDIR}



