#!/usr/bin/ksh
# INSTALLPROG (libuc)


: ${LOCAL:=/usr/add-on/local}
: ${NCMP:=/usr/add-on/ncmp}
: ${PCS:=/usr/add-on/pcs}
: ${EXTRA:=/usr/extra}
export LOCAL NCMP PCS EXTRA

TDIRS=" ${HOME} ${LOCAL} ${NCMP} ${PCS} ${EXTRA}"

T=libuc

LIBS="${T}.a "
INCS=" *.h "

F_RMSO=0


EXTRA=
fgrep 64 <( basename $PWD ) > /dev/null
if [[ $? -eq 0 ]] ; then
  EXTRA=sparcv9
fi


if [ -d /usr/sbin ] ; then
  MACH=$( uname -n )
  : ${OFD:-S5}
else
  MACH=$( hostname )
  PATH=/usr/5bin:${PATH}
  : ${OFD:-S4}
fi


STUFF="*.c *.a *.h Makefile"


makeit


for D in ${TDIRS} ; do

  if [[ -n "${LIBS}" ]] ; then
    makenewer ${LIBS} ${D}/lib/${EXTRA}
    makenewer -Q ${LIBS} ${D}/lib/${OFD}/${EXTRA} 2> /dev/null
  fi

  if [[ -n "${INCS}" ]] ; then
    makenewer ${INCS} ${D}/include
  fi

  if [[ $F_RMSO -ne 0 ]] ; then

    rm -f ${D}/lib/${T}.so
    rm -f ${D}/lib/${OFD}/${T}.so

  fi

done



