From dam Thu Dec 24 12:16:10 1998
X-Sender: dam@hocpw (Unverified)
Message-Id: <l03102800b2a826744973@[135.17.162.2]>
Mime-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
Date: Thu, 24 Dec 1998 12:14:40 -0500
To: conservative_list : ; (Conservative_List)
From: David Morano <dam@hocpw>
Subject: What would Jesus do ?
content-length: 272

Dear Conservative List people,

Check out Joseph Sobran's column on what Jesus Christ might do
in the same political climate that we are in now !

Check it out at :
http://www.uexpress.com/ups/opinion/column/js/text/1998/12/js981203.html

Dave Morano
morano@computer.org

