keywords: here there everywhere
Received:
	junk, junk,
	junk, junk,
	junk, junk,
	junk, junk,
	junk, junk,
	junk, junk,
	junk, junk,
	junk, junk,
	junk, junk,
	junk, junk,
	junk, junk,
	junk, junk,
	junk, junk,
	junk, junk,
	junk, junk,
	junk, junk,
Received:
	more junk,
	more junk,
	more junk,
	more junk,
to:      	bb (ha, ha !)
date:           02 Dec 93 12:26:33
x-here: there
	everywhere

body 1

From dam Fri May 23 22:30:10 EDT 1997
>From dam Fri May 23 22:30:10 EDT 1997 remote from mtgbcs
from:    	PCS_administrator <mtgbcs!pcs>
to:      	bb (ha, ha !)
subject:	test email/posting
subject:	test email/posting
subject:	test email/posting
subject:	test email/posting
subject:	test email/posting
subject:	test email/posting
subject:	test email/posting
subject:	test email/posting
subject:	test email/posting
subject:	test email/posting
date:           02 Dec 93 12:26:33

This is a test.  This is a test of the emergency email/posting
system.  This is only a test.  This test has been devised
as a means of testing email or bulletin board related operations.
If this had been an actual emergency, you would have been instructed
as to where to send email (for testing purposes !).
This concludes this test of the emergency email/posting system.

PCS Administrator

