#!/usr/extra/bin/ksh
# MKTESTFILE


TF=${1}
if [[ -z "${TF}" ]] ; then
  TF=testfile
fi

ETF1=/tmp/mtf${$}a
ETF2=/tmp/mtf${$}b

function cleanup {
  rm -f ${ETF1} ${ETF2}
}

trap 'cleanup ; exit 1' 1 2 3 15 16 17

SF=${NCMP}/share/dict/words
if [[ ! -r "${SF}" ]] ; then
  SF=${LOCAL}/share/dict/words
fi

cp ${SF} ${TF}
cp ${SF} ${ETF1}

integer n=4 c=0
for (( c = 0 ; c < n ; c += 1 )) ; do
  paste -d "" ${ETF1} ${SF} > ${ETF2}
  append ${TF} ${ETF2} 
  mv ${ETF2} ${ETF1}
done

cleanup


