/* config */


#define	VERSION		"0"
#define	WHATINFO	"@(#)testb26 "
#define	BANNER		"Test B25"
#define	SEARCHNAME	"testb26"

#define	VARPROGRAMROOT1	"TESTB26_PROGRAMROOT"
#define	VARPROGRAMROOT2	"LOCAL"
#define	VARPROGRAMROOT3	"PROGRAMROOT"

#define	VARBANNER	"TESTB26_BANNER"
#define	VARSEARCHNAME	"TESTB26_NAME"
#define	VAROPTS		"TESTB26_OPTS"
#define	VARCONF		"TESTB26_CONF"
#define	VARLINELEN	"TESTB26_LINELEN"
#define	VARTMPDNAME	"TMPDIR"
#define	VARERRORFNAME	"TESTB26_ERRORFILE"

#define	VARDEBUGFNAME	"TESTB26_DEBUGFILE"
#define	VARDEBUGFD1	"TESTB26_DEBUGFD"
#define	VARDEBUGFD2	"DEBUGFD"

#define	VARSYSNAME	"SYSNAME"
#define	VARRELEASE	"RELEASE"
#define	VARMACHINE	"MACHINE"
#define	VARARCHITECTURE	"ARCHITECTURE"
#define	VARHZ		"HZ"
#define	VARNODE		"NODE"
#define	VARCLUSTER	"CLUSTER"
#define	VARSYSTEM	"SYSTEM"
#define	VARDOMAIN	"DOMAIN"
#define	VARNISDOMAIN	"NISDOMAIN"
#define	VARTERM		"TERM"
#define	VARPRINTER	"PRINTER"
#define	VARLPDEST	"LPDEST"
#define	VARPAGER	"PAGER"
#define	VARMAIL		"MAIL"
#define	VARORGANIZATION	"ORGANIZATION"
#define	VARLINES	"LINES"
#define	VARCOLUMNS	"COLUMNS"
#define	VARNAME		"NAME"
#define	VARFULLNAME	"FULLNAME"
#define	VARTZ		"TZ"
#define	VARUSERNAME	"USERNAME"
#define	VARLOGNAME	"LOGNAME"
#define	VARNCPU		"NCPU"

#define	VARHOMEDNAME	"HOME"
#define	VARTMPDNAME	"TMPDIR"
#define	VARMAILDNAME	"MAILDIR"
#define	VARMAILDNAMES	"MAILDIRS"
#define	VARPATH		"PATH"

#define	VARPRLOCAL	"LOCAL"
#define	VARPRPCS	"PCS"

#ifndef	PROGRAMROOT
#define	PROGRAMROOT	"/usr/add-on/local"
#endif

#define	TMPDNAME	"/tmp"

#define	CONFIGFILE1	"etc/testb26/testb26.conf"
#define	CONFIGFILE2	"etc/testb26/conf"
#define	CONFIGFILE3	"etc/testb26.conf"

#define	LOGFNAME	"log/testb26"
#define	HELPFNAME	"lib/testb26/help"



