/* config */


#define	VERSION		"0"
#define	WHATINFO	"@(#)opendialertcpnls "
#define	BANNER		"Open-Dialer TCPNLS"
#define	SEARCHNAME	"opendialertcpnls"
#define	VARPRNAME	"EXTRA"

#define	VARPROGRAMROOT1	"OPENDIALERTCPNLS_PROGRAMROOT"
#define	VARPROGRAMROOT2	VARPRNAME
#define	VARPROGRAMROOT3	"PROGRAMROOT"

#define	VARBANNER	"OPENDIALERTCPNLS_BANNER"
#define	VARSEARCHNAME	"OPENDIALERTCPNLS_NAME"
#define	VARFILEROOT	"OPENDIALERTCPNLS_FILEROOT"
#define	VARLOGTAB	"OPENDIALERTCPNLS_LOGTAB"
#define	VARMSFNAME	"OPENDIALERTCPNLS_MSFILE"
#define	VARUTFNAME	"OPENDIALERTCPNLS_UTFILE"
#define	VARERRORFNAME	"OPENDIALERTCPNLS_ERRORFILE"

#define	VARDEBUGFNAME	"OPENDIALERTCPNLS_DEBUGFILE"
#define	VARDEBUGFD1	"OPENDIALERTCPNLS_DEBUGFD"
#define	VARDEBUGFD2	"DEBUGFD"

#define	VARNODE		"NODE"
#define	VARSYSNAME	"SYSNAME"
#define	VARRELEASE	"RELEASE"
#define	VARMACHINE	"MACHINE"
#define	VARARCHITECTURE	"ARCHITECTURE"
#define	VARCLUSTER	"CLUSTER"
#define	VARSYSTEM	"SYSTEM"
#define	VARNISDOMAIN	"NISDOMAIN"
#define	VARPRINTER	"PRINTER"

#define	VARTMPDNAME	"TMPDIR"

#define	VARPRLOCAL	"LOCAL"
#define	VARPRPCS	"PCS"

#ifndef	PROGRAMROOT
#define	PROGRAMROOT	"/usr/add-on/local"
#endif

#define	TMPDNAME	"/tmp"
#define	WORKDNAME	"/tmp"

#define	DEFINITFNAME	"/etc/default/init"
#define	DEFLOGFNAME	"/etc/default/login"
#define	NISDOMAINNAME	"/etc/defaultdomain"

#define	CONFIGFNAME	"conf"
#define	ENVFNAME	"environ"
#define	PATHSFNAME	"paths"
#define	HELPFNAME	"help"

#define	PIDFNAME	"run/opendialertcpnls"
#define	LOGFNAME	"var/log/opendialertcpnls"
#define	LOCKFNAME	"spool/locks/opendialertcpnls"
#define	MSFNAME		"ms"

#define	LOGSIZE		(80*1024)

#define	DEFRUNINT	60
#define	DEFPOLLINT	8
#define	DEFNODES	50

#define	TO_CACHE	2



