From nuucp Mon Apr 28 08:23:48 2003 remote from rcb
Date: 28 Jan 2003 08:23:48 +0530 (IST)
From: pcs
To: dam

test of zone-log file
From nuucp Mon Apr 28 08:23:48 2003 remote from rcb
Date: Mon, 28 Apr 2003 08:23:48 -0600 (MDT)
From: pcs
To: dam

test of zone-log file
From nuucp Mon Apr 28 08:23:48 2003 remote from rcb
Date: 28 Jan 2003 08:23:48 +0200 (CEST)
From: pcs
To: dam

test of zone-log file
From nuucp Mon Apr 28 08:23:48 2003 remote from rcb
Date: Mon, 28 Apr 2003 08:23:48 -0700 (PDT)
From: pcs
To: dam

test of zone-log file
From nuucp Mon Apr 28 08:23:48 2003 remote from rcb
Date: Mon, 28 Apr 2003 08:23:48 -0500 (CDT)
From: pcs
To: dam

test of zone-log file
From nuucp Mon Apr 28 08:23:48 2003 remote from rcb
Date: 28 Jan 2003 08:23:48 -0700 (MST)
From: pcs
To: dam

test of zone-log file
From nuucp Mon Apr 28 08:23:48 2003 remote from rcb
Date: 28 Jan 2003 08:23:48 -0500 (EST)
From: pcs
To: dam

test of zone-log file
From nuucp Mon Apr 28 08:23:48 2003 remote from rcb
Date: Mon, 28 Apr 2003 08:23:48 -0400 (EDT)
From: pcs
To: dam

test of zone-log file
From nuucp Mon Apr 28 08:23:48 2003 remote from rcb
Date: 28 Jan 2003 08:23:48 (EST)
From: pcs
To: dam

test of zone-log file
From nuucp Mon Apr 28 08:23:48 2003 remote from rcb
Date: Mon, 28 Apr 2003 08:23:48 (GMT)
From: pcs
To: dam

test of zone-log file
From nuucp Mon Apr 28 08:23:48 2003 remote from rcb
Date: Mon, 28 Apr 2003 08:23:48 (EDT)
From: pcs
To: dam

test of zone-log file
From nuucp Mon Apr 28 08:23:48 2003 remote from rcb
Date: Mon, 28 Apr 2003 08:23:48 -0000 (GMT)
From: pcs
To: dam

test of zone-log file
