From apcc.com!commercemaster Wed Mar 10 20:19:48 EST 2004
return-path: <commercemaster@apcc.com>
received: from berry.computer.org (berry.computer.org [63.84.220.201])
	by leviathan.ele.uri.edu (8.12.9/8.12.9) with ESMTP id i2B1JEPf013386
	for <morano@ele.uri.edu>; Wed, 10 Mar 2004 20:19:14 -0500 (EST)
received:  from apccorp.apcc.com (apccorp.apcc.com [159.215.19.1])
	by berry.computer.org (Switch-2.2.8/Switch-2.2.4) with ESMTP id W2B10OPX00000558
	for <morano@computer.org>; Wed, 10 Mar 2004 17:24:26 -0800
received:  from ECOM2KSEC.ams.apc.com (ecom2ksec.apcc.com [159.215.19.47])
	by apccorp.apcc.com (8.12.10/8.12.10) with ESMTP id i2B1J82r025408
	for <morano@computer.org>; Wed, 10 Mar 2004 20:19:08 -0500
content-length: 2396            
message-id: <20040310-20190428-bdc-0@ECOM2KSEC.ams.apc.com>
Reply-To: "American Power Conversion" <commercemaster@apcc.com>
Content-Type: multipart/mixed;
	boundary="--=502977142D6F46FB9AB3_FDF1_9257_F099"
MIME-Version: 1.0
X-Scanned-By: MIMEDefang 2.38
X-Spam-Report: 0.40 hits
	* -1.4 -- Subject looks like order info
	*  0.2 -- BODY: Contains a tollfree number
	*  1.3 -- BODY: Spam phrases score is 13 to 21 (high)
	[score: 16]
	*  0.0 -- BODY: Contains a line >=199 characters long
	*  0.3 -- RAW: Message contains a lot of ^M characters
X-Spam-Status: NO ; VERY LOW ; 0.40
X-MIMEDefang-Status: Skipped: 159.215.19.47
From: "American Power Conversion" <commercemaster@apcc.com>
To: "David Morano" <morano@computer.org>
Date: Wed, 10 Mar 2004 20:19:04 -0500
Subject: American Power Conversion - Order confirmation #1101046

----=502977142D6F46FB9AB3_FDF1_9257_F099
Content-Type: multipart/alternative;
	boundary="--=7B38C3C7AF3C4C1BBF83_9B82_D360_C0F4"

----=7B38C3C7AF3C4C1BBF83_9B82_D360_C0F4
Content-Type: text/plain;charset="UTF-8"
Content-Transfer-Encoding: Quoted-Printable

DEAR CUSTOMER:
=20
We have received your order.  As soon as your order ships, you will rec=
eive an e-mail confirmation with the package(s) tracking number(s).  Th=
ank you for choosing us for your power protection needs.
=20
Order Number: 1101046=0D=0DTo track the status of your order, please cl=
ick on the following URL (Some e-mail programs may require you to copy =
this link to your web browser rather than clicking it from the e-mail p=
rogram.) :=0Dhttps://buy.apc.com/commerce/storefronts/etail/profile/vie=
w_order.asp?ListItem=3D1101046&Email=3Dmorano%40computer%2Eorg&CountryC=
ode=3Dus&StorefrontCode=3Dapcfs&iSource=3D5&tsk=3Dw447z&LanguageCode=3D=
en=0D=0DIf you have any questions, please e-mail to commercemaster@apcc=
.com or call 1-800-800-4272 and we will be happy to assist you.

----=7B38C3C7AF3C4C1BBF83_9B82_D360_C0F4
Content-Type: text/html;charset="UTF-8"
Content-Transfer-Encoding: Quoted-Printable

DEAR CUSTOMER:<br />=0A <br />=0AWe have received your order.  As soon =
as your order ships, you will receive an e-mail confirmation with the p=
ackage(s) tracking number(s).  Thank you for choosing us for your power=
 protection needs.<br />=0A <br />=0AOrder Number:=0D 1101046<br /><br =
/>=0DTo track the status of your order, please click on the following U=
RL (Some e-mail programs may require you to copy this link to your web =
browser rather than clicking it from the e-mail program.) :=0D<A HREF=3D=
"https://buy.apc.com/commerce/storefronts/etail/profile/view_order.asp?=
ListItem=3D1101046&Email=3Dmorano%40computer%2Eorg&CountryCode=3Dus&Sto=
refrontCode=3Dapcfs&iSource=3D5&tsk=3Dw447z&LanguageCode=3Den" target=3D=
"_blank">https://buy.apc.com/commerce/storefronts/etail/profile/view_or=
der.asp?ListItem=3D1101046&amp;Email=3Dmorano%40computer%2Eorg&amp;Coun=
tryCode=3Dus&amp;StorefrontCode=3Dapcfs&amp;iSource=3D5&amp;tsk=3Dw447z=
&amp;LanguageCode=3Den</A><br /><br />=0DIf you have any questions, ple=
ase e-mail to commercemaster@apcc.com or call 1-800-800-4272 and we wil=
l be happy to assist you.

----=7B38C3C7AF3C4C1BBF83_9B82_D360_C0F4--

----=502977142D6F46FB9AB3_FDF1_9257_F099--
