From dell@nii.net Mon Jun 23 11:48:48 2003
Return-Path: <dell@nii.net>
Received: from alias2.acm.org (alias2.acm.org [199.222.69.92])
	by leviathan.ele.uri.edu (8.12.6/8.12.6) with ESMTP id h5NFmjf2014763
	for <morano@ele.uri.edu>; Mon, 23 Jun 2003 11:48:45 -0400 (EDT)
Received: from baron.nii.net ([209.113.172.16])
        by alias2.acm.org (ACM Email Forwarding Service) with ESMTP id CRY73883
        for <morano@acm.org>; Mon, 23 Jun 2003 11:48:45 -0400
Received: from nii.net (dialup-67.75.37.109.Dial1.Boston1.Level3.net [67.75.37.109])
	by baron.nii.net (8.9.3/8.9.3) with ESMTP id LAA24724
	for <morano@acm.org>; Mon, 23 Jun 2003 11:48:43 -0400
Message-ID: <3EF71F1F.7020100@nii.net>
Date: Mon, 23 Jun 2003 11:39:11 -0400
From: dell <dell@nii.net>
User-Agent: Mozilla/5.0 (Windows; U; Win98; en-US; rv:1.0.2) Gecko/20030208 Netscape/7.02
X-Accept-Language: en-us, en
MIME-Version: 1.0
To: Dave Morano <morano@acm.org>
Subject: larger area
Content-Type: text/plain; charset=us-ascii; format=flowed
Content-Transfer-Encoding: 7bit
X-Spam-Status: NO ; VERY LOW ; -0.20
X-Spam-Report: -0.20 hits
	* -0.6 -- User-Agent header indicates a non-spam MUA (Mozilla)
	* -0.5 -- Found a User-Agent header
	* -0.2 -- Found a X-Accept-Language header
	*  0.8 -- BODY: Spam phrases score is 00 to 01 (low)
	*  0.3 -- RAW: Message contains a lot of ^M characters
Content-Length: 478

Dave,

The coffee stain area is larger now than ever and it looks as if someone 
wet the bed, kind of a urin color that spread out....do ya think I can 
get rid of that?
Maybe I should try th car  'frabric' carpet cleaner that I use for the 
car...I know it cleans coffee stains (if any) on a car carpet...I saw 
how that works and it's great...sorry I didn't pull that little blue tab 
off the car cleaner can...donno how it worked the first time when I used 
it...
your mom



