From nucar-request@lochinvar.ece.neu.edu Mon Oct 08 16:15:29 EDT 2001 
Return-Path: <nucar-request@lochinvar.ece.neu.edu>
Received: from lochinvar.ece.neu.edu (mail2.ece.neu.edu [129.10.60.82])
	by leviathan.ele.uri.edu (8.11.2/8.11.2) with ESMTP id f98KFR216302;
	Mon, 8 Oct 2001 16:15:28 -0400 (EDT)
Received: from yoda.ece.neu.edu (yoda [129.10.60.143])
	by lochinvar.ece.neu.edu (8.9.3/8.9.3) with ESMTP id QAA28911
	for <nucar@gateway.ece.neu.edu>; Mon, 8 Oct 2001 16:17:45 -0400 (EDT)
Received: from localhost by yoda.ece.neu.edu (8.9.3/8.9.3) with ESMTP id QAA01330
	for <nucar@ece.neu.edu>; Mon, 8 Oct 2001 16:14:30 -0400 (EDT)
X-Authentication-Warning: yoda.ece.neu.edu: mdealba owned process doing -bs
Date: Mon, 8 Oct 2001 16:14:30 -0400 (EDT)
From: Marcos de Alba <mdealba@ECE.NEU.EDU>
X-Sender: mdealba@yoda
To: nucar@ECE.NEU.EDU
Subject: SMT simulator (fwd)
Message-ID: <Pine.GSO.4.21.0110081614080.1328-100000@yoda>
MIME-Version: 1.0
Content-Type: TEXT/PLAIN; charset=US-ASCII
Content-Length: 1413

Deniz,

This should be of your interest.

________________________________________________________________________
 Marcos R. de Alba                                
 Computer Engineering Research Laboratory	Northeastern University	
 Lab: (617) 373-7780                             

---------- Forwarded message ----------
Date: Mon, 8 Oct 2001 18:00:20 +0300
From: Ioannis E. Venetis <iev@hpclab.ceid.upatras.gr>
To: simplescalar@cs.wisc.edu
Subject: SMT simulator

Hello,

Browsing through the project web site I noticed that it is planned to add an SMT simulator to SimpleScalar. Is this simulator included in the upcoming 3.0 release of SimpleScalar and when will the new version be released?

It is also mentioned in a few papers that there exist some SMT simulators based on SimpleScalar. Does anyone know where I can find such extensions?

In case I cannot find an already implemented SMT simulator, where can I find documentation to implement my own SMT simulator using SimpleScalar?

Finally, a question not related to SimpleScalar: Is anyone aware of any SMT simulator that is not based on SimpleScalar, except of SMTSIM?


Thank you for your help,

Ioannis E. Venetis
PostGraduate Student - Research Assistant
High Performance Information Systems Laboratory
Computer Engineering and Informatics Department
University of Patras, Greece
http://www.hpclab.ceid.upatras.gr/pgroup/members/iev/index.html




