From s1a22003@yahoo.com.br Mon Sep  8 13:10:29 2003
Return-Path: <s1a22003@yahoo.com.br>
Received: from berry.computer.org (berry.computer.org [63.84.220.201])
	by leviathan.ele.uri.edu (8.12.9/8.12.9) with ESMTP id h88H9ta6001224
	for <morano@ele.uri.edu>; Mon, 8 Sep 2003 13:09:56 -0400 (EDT)
Received: from mercury.ccil.org (mercury.ccil.org [192.190.237.100])
	by berry.computer.org (Switch-2.2.6/Switch-2.2.4) with ESMTP id V88H1CC924271
	for <morano@computer.org>; Mon, 08 Sep 2003 10:12:48 -0700
Received: from [200.103.111.30] (helo=stc3)
	by mercury.ccil.org with smtp (Exim 3.35 #1 (Debian))
	id 19wKJO-0001gu-00
	for <jargon-helpers@ccil.org>; Mon, 08 Sep 2003 07:36:10 -0400
From: "s1a22003" <s1a22003@yahoo.com.br>
To: "jargon-helpers" <jargon-helpers@ccil.org>
Subject: [***SPAM 20.40***] AUMENTE SEU PENIS EM ATE 7cm
Date: Mon, 08 Sep 03 07:22:42 Hora oficial do Brasil
MIME-Version: 1.0
Content-Type: multipart/mixed;boundary= "----=_NextPart_000_002B_7567556F.B846A66F"
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 6.00.2462.0000
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2462.0000 
Message-Id: <E19wKJO-0001gu-00@mercury.ccil.org>
X-Spam-Level: ********************
X-Spam-Status: YES ; HIGH ; 20.40
X-Spam-Report: 20.40 hits
	* -0.3 -- To: repeats local-part as real name
	*  1.5 -- Invalid Date: header (not RFC 2822)
	*  0.9 -- From: ends in numbers
	*  0.3 -- From: contains numbers mixed in with letters
	*  0.2 -- X-Mailer header indicates a non-spam MUA (Outlook Express)
	*  0.8 -- BODY: Spam phrases score is 00 to 01 (low)
	          [score: 0]
	*  0.3 -- BODY: FONT Size +2 and up or 3 and up
	*  0.3 -- BODY: HTML font face is not a commonly used face
	*  0.3 -- BODY: HTML font color is red
	*  0.4 -- BODY: Frontpage used to create the message
	*  0.2 -- BODY: Includes a URL link to send an email
	*  3.9 -- Listed in Razor2, see http://razor.sf.net/
	*  2.7 -- Listed in DCC, see http://rhyolite.com/anti-spam/dcc/
	*  1.4 -- 'From' yahoo.com does not match 'Received' headers
	*  0.3 -- Date: is 3 to 6 hours before Received: date
	*  4.0 -- RBL: Received via a relay in bl.spamcop.net
	          [RBL check: found 30.111.103.200.bl.spamcop.net.]
	*  3.2 -- RBL: Received via a relay in list.dsbl.org
	          [RBL check: found 30.111.103.200.list.dsbl.org]
X-Spam-Flag: YES
Content-Length: 3605

------=_NextPart_000_002B_7567556F.B846A66F
Content-Type: text/html
Content-Transfer-Encoding: base64

PGh0bWw+DQoNCjxoZWFkPg0KPG1ldGEgaHR0cC1lcXVpdj0iQ29udGVudC1MYW5ndWFnZSIg
Y29udGVudD0icHQtYnIiPg0KPG1ldGEgbmFtZT0iR0VORVJBVE9SIiBjb250ZW50PSJNaWNy
b3NvZnQgRnJvbnRQYWdlIDUuMCI+DQo8bWV0YSBuYW1lPSJQcm9nSWQiIGNvbnRlbnQ9IkZy
b250UGFnZS5FZGl0b3IuRG9jdW1lbnQiPg0KPG1ldGEgaHR0cC1lcXVpdj0iQ29udGVudC1U
eXBlIiBjb250ZW50PSJ0ZXh0L2h0bWw7IGNoYXJzZXQ9d2luZG93cy0xMjUyIj4NCjx0aXRs
ZT5Db20gbyBNQU5VQUwgbWFpcyBjb2Jp52FkbyBkYSBpbnRlcm5ldCBubyBtb21lbnRvPC90
aXRsZT4NCjwvaGVhZD4NCg0KPGJvZHk+DQoNCjxmb250IGZhY2U9IkFyaWFsIiBzaXplPSIy
Ij4NCjxkaXY+DQogIDxmb250IGZhY2U9IkFyaWFsIiBjb2xvcj0iI2ZmMDAwMCI+PGZvbnQg
c2l6ZT0iMyIgY29sb3I9IiMwMDAwMDAiPjxzdHJvbmc+Q29tIA0KICBvIE1BTlVBTCBtYWlz
IGNvYmnnYWRvIGRhIGludGVybmV0IG5vIG1vbWVudG88L3N0cm9uZz4sIDwvZm9udD4NCiAg
PGZvbnQgc2l6ZT0iMyIgY29sb3I9IiNmZjAwMDAiPjxzdHJvbmc+dm9j6iBhdW1lbnRhIG8g
dGFtYW5obzxicj4NCiAgZGUgc2V1IHDqbmlzIGRlIDIgYSZuYnNwOzcgY20mbmJzcDsgZW0m
bmJzcDsgMiBtZXNlcyBjb20gZXhlcmPtY2lvcyBhYnNvbHV0YW1lbnRlPGJyPg0KICBuYXR1
cmFpcy4gQXVtZW50YSB0YW1i6W0gYSBzdWEgcG906m5jaWEsJm5ic3A7IGNvbnRyb2xlIGUg
dm9sdW1lIGRhIGVqYWN1bGHn428sPC9zdHJvbmc+PGJyPg0KICA8L2ZvbnQ+PGZvbnQgc2l6
ZT0iMyIgY29sb3I9IiMwMDAwMDAiPjxzdHJvbmc+ZGVudHJlIG91dHJvcyBiZW5lZu1jaW9z
LiANCiAgUHJvZ3JhbWEgY29tcGxldG8gY29tIGZpZ3VyYXMgaWx1c3RyYXRpdmFzPGJyPg0K
ICBleHBsaWNhbmRvIGRldGFsaGFkYW1lbnRlIHRvZG9zIG9zIGV4ZXJj7WNpb3MuJm5ic3A7
IEZvdG9zIGNvbXBhcmF0aXZhcyBubyBzaXRlPGJyPg0KICBkZSBwZXNzb2FzIHF1ZSBleHBl
cmltZW50YXJhbSBlc3NhIHTpY25pY2EuPC9zdHJvbmc+IDwvZm9udD48L2ZvbnQ+PC9mb250
Pg0KICA8Zm9udCBjb2xvcj0iIzAwMDAwMCIgc2l6ZT0iNCIgZmFjZT0iQXJpYWwgQmxhY2si
Pg0KICA8YSBocmVmPSJodHRwOi8vd3d3LnBlbmlzMjIuY29tIj5DTElRVUUgSsE8L2E+PC9m
b250Pjxmb250IGZhY2U9IkFyaWFsIj48L2Rpdj4NCjwvZm9udD48Zm9udCBmYWNlPSJBcmlh
bCIgc2l6ZT0iMiI+DQo8ZGl2Pg0KICA8Zm9udCBzaXplPSIyIj4NCiAgPGRpdj4NCiAgICA8
ZGl2Pg0KICAgICAgPGRpdj4NCiAgICAgICAgPGRpdj4NCiAgICAgICAgICA8Zm9udCBjb2xv
cj0iIzAwMDAwMCIgc2l6ZT0iMiIgZmFjZT0iQXJpYWwiPjwvZm9udD4NCiAgICAgICAgPC9k
aXY+DQogICAgICAgIDxmb250IGZhY2U9IkFyaWFsIiBzaXplPSIyIj4NCiAgICAgICAgPGRp
dj4NCiZuYnNwOzwvZGl2Pg0KICAgICAgPC9kaXY+DQogICAgICA8L2ZvbnQ+PC9mb250Pg0K
ICAgIDwvZGl2Pg0KICA8L2Rpdj4NCjwvZGl2Pg0KPGRpdj4NCiAgJm5ic3A7PC9kaXY+DQo8
ZGl2Pg0KICAmbmJzcDs8L2Rpdj4NCjxkaXY+DQogICZuYnNwOzxwPiZuYnNwOzwvcD4NCiAg
PHA+Jm5ic3A7PC9wPg0KICA8cD4mbmJzcDs8L3A+DQogIDxwPiZuYnNwOzwvcD4NCiAgPHA+
Jm5ic3A7PC9kaXY+DQo8ZGl2Pg0KICAmbmJzcDs8L2Rpdj4NCjxkaXY+DQogICZuYnNwOzwv
ZGl2Pg0KPGRpdj4NCiAgX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19f
X19fX19fX19fX19fX19fX19fX19fX19fX19fX188L2Rpdj4NCjxkaXY+DQogIE9CUzogRXN0
YSBtZW5zYWdlbSBu428g6SB1bSBzcGFtLCB2aXN0byBxdWUgc29tZW50ZSBlc3RhcuEgc2Vu
ZG8gPGJyPg0KICBlbnZpYWRvIHVtYSD6bmljYSB2ZXosIGUgdGFtYultIGNvbnTpbSB1bWEg
Zm9ybWEgZGUgc2VyIHJlbW92aWRhLDxicj4NCiAg6SB1bSBlLW1haWwgbm9ybWFsIGNvbW8g
dGFudG9zIG91dHJvcyBxdWUgdm9j6iByZWNlYmUsIG7jbyBlc3RhbW9zPGJyPg0KICBpbnZh
ZGluZG8gc3VhIHByaXZhY2lkYWRlIGUgZW52aWFyIHVtIGUtbWFpbCBu428g6SBjcmltZSwg
ZGVzZGUgcXVlPGJyPg0KICBu428gY29udGVuaGEgbWVuc2FnZW5zIHF1ZSBwb3NzYW0gY2F1
c2FyIGRhbm9zIGFvIHVzdeFyaW8uIENhc28gPGJyPg0KICBxdWVyaWEgcmVtb3ZlciBzZXUg
ZW5kZXJl528gZGUgbm9zc2EgbGlzdGEsIGJhc3RhIGVudmlhciB1bSANCiAgPGEgaHJlZj0i
bWFpbHRvOnMxYTIyMDAzQHlhaG9vLmNvbS5iciI+ZS1tYWlsPC9hPjxicj4NCiAgY29tIG8g
dGl0dWxvIChhc3N1bnRvKSByZW1vdmVyLCBxdWUgc2V1PGJyPg0KICBlLW1haWwgc2Vy4SBy
ZW1vdmlkbyBkZSBub3NzYSBsaXN0YSBkZWZpbml0aXZhbWVudGUuRGVzY3VscGUtbm9zPGJy
Pg0KICBjYXNvIHRlbmhhbW9zIGxoZSBpbXBvcnR1bmFkbyBjb20gbm9zc28gZS1tYWlsIGRl
IGRpdnVsZ2Hn428uPGJyPg0KICBPYnJpZ2FkbyE8L2Rpdj4NCjwvZm9udD4NCg0KPC9ib2R5
Pg0KDQo8L2h0bWw+ICAgIA==
------=_NextPart_000_002B_7567556F.B846A66F--

