From wsmohyqhnvsw@chanmiracle.com Wed Jun  4 19:12:50 2003
Return-Path: <wsmohyqhnvsw@chanmiracle.com>
Received: from clement.computer.org (clement.computer.org [63.84.220.160])
	by leviathan.ele.uri.edu (8.12.6/8.12.6) with ESMTP id h54NCif2015022
	for <morano@ele.uri.edu>; Wed, 4 Jun 2003 19:12:45 -0400 (EDT)
Received: from localhost.localdomain (m12.happiness-counseling.com [208.169.112.12])
	by clement.computer.org (Switch-2.2.6/Switch-2.2.4) with SMTP id V54N1C1I31561
	for <morano@computer.org>; Wed, 04 Jun 2003 16:12:37 -0700
To: morano@computer.org
Date: Thu, 5 Jun 2003 07:18:30 -0600
Message-ID: <1054815510.6959@localhost.localdomain>
X-Mailer: Microsoft Outlook Express 5.00.3018.1300
From: hahcar help <wsmohyqhnvsw@chanmiracle.com>
Subject: [***SPAM 15.70***] savdo up to 70% over auto brokerwmq
Content-type: text/html
X-Spam-Level: ***************
X-Spam-Status: YES ; HIGH ; 15.70
X-Spam-Report: 15.70 hits
	*  0.2 -- X-Mailer header indicates a non-spam MUA (Outlook Express)
	*  0.8 -- BODY: Spam phrases score is 00 to 01 (low)
	*  0.1 -- BODY: Contains a comment with nothing but unique ID
	*  0.3 -- RAW: Message contains a lot of ^M characters
	*  0.7 -- URI: URL of page called "remove"
	*  0.2 -- URI: Includes a 'remove' email address
	*  2.7 -- Listed in DCC, see http://rhyolite.com/anti-spam/dcc/
	*  4.0 -- RBL: Received via a relay in bl.spamcop.net
	          [RBL check: found 12.112.169.208.bl.spamcop.net.]
	*  0.4 -- RBL: Received via a relay in relays.osirusoft.com
	          [RBL check: found 12.112.169.208.relays.osirusoft.com., type: 127.0.0.4]
	*  3.2 -- RBL: Received via SBLed relay, see http://www.spamhaus.org/sbl/
	          [RBL check: found 12.112.169.208.sbl.spamhaus.org.]
	*  2.7 -- RBL: DNSBL: sender is Confirmed Spam Source
	*  0.4 -- HTML-only mail, with no text version
X-Spam-Flag: YES
Content-Length: 634

<HTML>
</: ejltyssrahnveopnalhvfhkwrbd{{9}}><!-- iapbhcmbdftuhdjfja-->
<BODY BGCOLOR=#FFFFFF>
<p><a href="http://chanmiracle.com/redir_aw.php?vyajhyoolnipqqrhtylgconyjwcudmwynaku.htmlmorano@computer.orghhhhhhyyjmmreekwnevbmbpaabxeydsvchvocwnomciqitnxamy"><img src="http://chanmiracle.com/aw/wa.gif" width="561" height="393" border="0"></a></p>
<p><a href="http://chanmiracle.com/unsub_aw.php?remove=morano@computer.org"><img src="http://chanmiracle.com/images/r.gif" width="400" height="19" border="0"></a></p>
<p>&nbsp;</p>
</BODY>
</HTML>
<!-- ppqppspttsnrwuqlyn--></: bncgwtosjpuxoknidfdsawopolm{{9}}>
<!-- fanvbexjbtyvgqsefe-->



