From funny@ele.uri.edu Thu Jun 12 00:40:25 EDT 2003
return-path: funny@ele.uri.edu
received: (from pcs@localhost)  
	by mail.rightcore.com (8.10.1/dam0)
	id h5C4eP812070
	for dam 
	; Thu, 12 Jun 2003 00:40:25 -0400 (EDT)
received: 	from 
	person@rightcore.com
received: 	from 
	other_person
received: 	from 
	third_person
content-length: 407             
message-id: <200306120440.h5C4eP812070@mail.rightcore.com>
sender: jack@in.the.box
errors-to: pcs@rightcore.com
From: POP_administrator <pop>
To: morano
Date: Thu, 12 Jun 2003 00:40:25 -0400 (EDT)
Subject: test email

This is a test.  This is a test of the emergency email/posting
system.  This is only a test.  This test has been devised
as a means of testing email or bulletin board related operations.
If this had been an actual emergency, you would have been instructed
as to where to send email (for testing purposes !).
This concludes this test of the emergency email/posting system.

From here@there
PCS Administrator
