From KELLEEBENDURE@yahoo.ca Wed Sep 24 00:24:48 2003
Return-Path: <KELLEEBENDURE@yahoo.ca>
Received: from OLDBUTNOTDONE (user-0cet377.cable.mindspring.com [24.238.140.231])
	by leviathan.ele.uri.edu (8.12.9/8.12.9) with SMTP id h8O4Oha6023809
	for <morano@ele.uri.edu>; Wed, 24 Sep 2003 00:24:44 -0400 (EDT)
Message-Id: <200309240424.h8O4Oha6023809@leviathan.ele.uri.edu>
From: "singer" <KELLEEBENDURE@yahoo.ca>
To: "morano@ele.uri.edu" <morano@ele.uri.edu>
Subject: [***SPAM 11.30***] hello
Date: Tue, 23 Sep 2003 23:23:57 -0500
X-Priority: 3 (normal)
Importance: Normal
X-Mailer: Microsoft Outlook IMO, Build 9.0.2416 (9.0.2910.0)
MIME-Version: 1.0
Content-Type: text/html;
	charset="iso-8859-1"
Content-Transfer-Encoding: base64
X-Spam-Level: ***********
X-Spam-Status: YES ; MEDIUM ; 11.30
X-Spam-Report: 11.30 hits
	* -0.0 -- X-Mailer header indicates a non-spam MUA (Outlook)
	*  1.6 -- Subject starts with "Hello"
	*  0.2 -- To: repeats address as real name
	*  0.8 -- BODY: Spam phrases score is 00 to 01 (low)
	          [score: 0]
	*  1.4 -- RAW: Message text disguised using base-64 encoding
	*  0.3 -- RAW: Message contains a lot of ^M characters
	*  3.9 -- Listed in Razor2, see http://razor.sf.net/
	*  2.7 -- Listed in DCC, see http://rhyolite.com/anti-spam/dcc/
	*  0.4 -- HTML-only mail, with no text version
X-Spam-Flag: YES
Content-Length: 528

PGh0bWw+DQpIaSw8YnI+DQpIZXJlPCFkbGE0aGc3Zj4gaXMgdGhlIHdlYjwheXF3cjFleW8+c2l0
ZSB5b3Ugd2FudGVkIHdoZXJlIHlvdSBjYW4gZ2V0IGEgczwhZ29pZGZzPnVwZXIgbG93PGJyPg0K
aW50PCFtOGk5b3BqODk+ZXJlc3QgcmE8IWZkOHU0YT50ZSBvbiB5b3VyIG1vcjwhY2x1c3Rlcj50
Z2FnZS4gR2V0IGFuIG9ubGluZSBxdW88IXByZXN0bz50ZSBub3chPGJyPg0KPGEgaHJlZj0iaHR0
cDovL3d3dy5zdXBlcmxvd3JhdGVzLm5ldCI+IFdlYnNpdGUgaXMgaGVyZSE8L2E+PGJyPg0KVGhh
bmsgeW91LDxicj4NCldpbGxpYW0gPCFsYXd5ZXI+QmVuZWRpY3Q8YnI+DQo8YnI+DQo8YnI+DQo8
IXlxd3IxZXlvPg0KPCFnb2lkZnM+DQo8IW04aTlvcGo4OT4NCjwvaHRtbD4NCg==


