From nuucp Mon Apr 28 08:23:48 2003 remote from rcb
>From morano@rca Mon Apr 28 08:20:48 2003 remote from rca
from:    	POP_administrator <pop>
to:      	morano
subject:	test email
content-length:
	392
from: meszaros

This is a test.  This is a test of the emergency email/posting
system.  This is only a test.  This test has been devised
as a means of testing email or bulletin board related operations.
If this had been an actual emergency, you would have been instructed
as to where to send email (for testing purposes !).
This concludes this test of the emergency email/posting system.

PCS Administrator











From meszaros Mon Apr 28 08:23:48 2003
Received:  (from morano@localhost)  
	by mail.rightcore.com (8.10.1/dam0)
	
	id h3SCNmn07480
	for dam 
	; Mon, 28 Apr 2003 08:23:48 -0400 (EDT)
Date: Mon, 28 Apr 2003 08:23:48 -0400 (EDT)
From: ("David A. Morano") morano
Message-Id: <dsifguhsdifgspidgfpisgdfpisgdfg200304281223.h3SCNmn07480@mail.rightcore.com>
To: 
	dam
Content-Length: 
	12
Subject: postal address
from:
	other (person)

send to Tom
