From besthealthplan3003@PRIMARYFOCALPOINTS.NET Mon May  5 23:54:00 2003
Return-Path: <besthealthplan3003@PRIMARYFOCALPOINTS.NET>
Received: from cpe000103340703-cm014350105704.cpe.net.cable.rogers.com (CPE000103340703-CM014350105704.cpe.net.cable.rogers.com [24.42.231.95])
	by leviathan.ele.uri.edu (8.12.6/8.12.6) with SMTP id h463rff2026826
	for <morano@ele.uri.edu>; Mon, 5 May 2003 23:53:55 -0400 (EDT)
Received: from  [61.192.19.70]
	by cpe000103340703-cm014350105704.cpe.net.cable.rogers.com;
	Tue, 06 May 2003 02:50:13 -0200
Message-ID: <6-51mn1$cq--dxs$6$7s1xu275i-uc2@2t7ay.4.7oj>
From: "" <besthealthplan3003@PRIMARYFOCALPOINTS.NET>
To: <morano@ele.uri.edu>
Subject: [***SPAM 12.60***] Self Employed Health Insurance - Free Quotes! ewnrsxehldphngkxaa
Date: Tue, 06 May 03 02:50:13 GMT
X-Mailer: eGroups Message Poster
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="_FF.FC6EC63E.CB_C"
X-Priority: 3
X-MSMail-Priority: Normal
X-Spam-Level: ************
X-Spam-Status: YES ; HIGH ; 12.60
X-Spam-Report: 12.60 hits
	*  1.3 -- From: does not include a real name
	*  1.0 -- Bulk email software fingerprint (eGroups) found in headers
	*  0.9 -- From: ends in numbers
	*  0.6 -- BODY: Free Quote
	*  0.4 -- BODY: Asks you to click below (in caps)
	*  0.3 -- BODY: Asks you to click below
	*  1.3 -- BODY: Spam phrases score is 13 to 21 (high)
	          [score: 13]
	*  0.3 -- BODY: HTML font color is red
	*  0.6 -- BODY: Tells you to click on a URL (in caps)
	*  0.3 -- BODY: Tells you to click on a URL
	*  1.0 -- RAW: Excessive quoted-printable encoding in body
	*  0.3 -- RAW: Quoted-printable line longer than 76 characters
	*  2.7 -- Listed in DCC, see http://rhyolite.com/anti-spam/dcc/
	*  0.5 -- Message has X-MSMail-Priority, but no X-MimeOLE
	*  1.1 -- Message looks like Outlook, but isn't
X-Spam-Flag: YES
Content-Length: 1834

This is a multi-part message in MIME format.

--_FF.FC6EC63E.CB_C
Content-Type: text/html;
Content-Transfer-Encoding: quoted-printable

<HTML><FONT COLOR=3D"#000000" SIZE=3D2 PTSIZE=3D8 FAMILY=3D"SANSSERIF" FAC=
E=3D"Arial" LANG=3D"0"><center><B>Forbes Ranked #1 Largest Health Insuranc=
e Provider Expanding!<BR>
<FONT COLOR=3D"RED" SIZE=3D2.5 PTSIZE=3D9 FAMILY=3D"SANSSERIF" FACE=3D"Ari=
al" LANG=3D"0">Lowest Rates - Fastest Local & Personal Service Available! =
<BR>
<FONT COLOR=3D"#000000" SIZE=3D2.5 PTSIZE=3D9 FAMILY=3D"SANSSERIF" FACE=3D=
"Arial" LANG=3D"0"> Health Planning for Families, Individuals and Self-Emp=
loyed!<BR><BR>
Quotes in 5 Minutes or Less with QuickQuote Form!<BR>
All Inquiries Welcome as we Review ALL Inquiries!<BR> 
Planning for the Unexpected - What Could Be Easier? <BR> </FONT>
<FONT COLOR=3D"#000000" BACK=3D"#ffffff" style=3D"BACKGROUND-COLOR: #fffff=
f" SIZE=3D2 PTSIZE=3D9 FAMILY=3D"SANSSERIF" FACE=3D"Arial" LANG=3D"0"><BR>=

<B><i>Get Your FREE Health Coverage Quote Now!</B></I><BR><BR>
<A HREF=3D"http://DV.nationwideacceptable.com/ins2/">For Your FREE Insuran=
ce Quote - CLICK HERE!</A></B><BR>
<FONT COLOR=3D"#000000" BACK=3D"#ffffff" style=3D"BACKGROUND-COLOR: #fffff=
f" SIZE=3D1.5 PTSIZE=3D8 FAMILY=3D"SANSSERIF" FACE=3D"Arial"
LANG=3D"0">=3D=
=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=
=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=
<BR>
This email has been broadcast to all previous customers.<BR>
To Remove from future offers <A HREF=3D"http://DV.nationwideacceptable.com=
/ins2/?rm=3D1">CLICK
HERE</A><BR>
=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=
=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=
=3D=3D<BR>
</FONT></HTML>
dvtcpya

--_FF.FC6EC63E.CB_C--


