Received: 
	from 
	person@rightcore.com
Received: 
	from 
	other_person@rightcore.com
Received: 
	from 
	third_person@rightcore.com
return-path:
	here1, here2,
	here3, here4
return-path: more1
from:    	POP_administrator <pop>
to:      	morano,
 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@bbbbbbbbbbbbbbb.com
to:	other, other2, other3,
	other4, other5
subject:	test email 	 	 other   there 

This is a test.  This is a test of the emergency email/posting
system.  This is only a test.  This test has been devised
as a means of testing email or bulletin board related operations.
If this had been an actual emergency, you would have been instructed
as to where to send email (for testing purposes !).
This concludes this test of the emergency email/posting system.

PCS Administrator
