/* config */


#define	VERSION		"0"
#define	WHATINFO	"@(#)TESTDATER "
#define	BANNER		"Test DATER"
#define	SEARCHNAME	"testdater"
#define	VARPRNAME	"LOCAL"

#define	VARPROGRAMROOT1	"TESTDATER_PROGRAMROOT"
#define	VARPROGRAMROOT2	VARPRNAME
#define	VARPROGRAMROOT3	"PROGRAMROOT"

#define	VARBANNER	"TESTDATER_BANNER"
#define	VARNAME		"TESTDATER_NAME"
#define	VAROPTS		"TESTDATER_OPTS"
#define	VARAFNAME	"TESTDATER_AF"
#define	VAREFNAME	"TESTDATER_EF"
#define	VARERRORNAME	"TESTDATER_ERRORFILE"

#define	VARDEBUGFNAME	"TESTDATER_DEBUGFILE"
#define	VARDEBUGFD1	"TESTDATER_DEBUGFD"
#define	VARDEBUGFD2	"DEBUGFD"

#ifndef	PROGRAMROOT
#define	PROGRAMROOT	"/usr/add-on/local"
#endif

#define	TMPDNAME	"/tmp"


