'\" t
.TH PCSNAME 1 0 PCS
.SH NAME
pcsname \- get or set the PCS real name
.SH SYNOPSIS
.\"_
.so tmac.att
.\"_
.BR pcsname
.OP -u " user" ] [
.OP -s " name" ] [
.OP -R " program-root" ] [
.OP -D\fR[=<\fIn\fP>]\fP "" ] [
.OP -V "" ] [
.SH DESCRIPTION
.sp
.SS Introduction
.PP
The \f(CWpcsname\fP program
is used by the Personal Communication Services (PCS) user to get or
to set his personal real name.
Two PCS real names are available for use.  These are the
regular real name, and the (so-called) "full" real name.
The regular real name is generally the real name of the user
with an abbreviated middle initial only and no postnominal letters.
This type of real name is usually already established by the
system administrator when the user account was set up.
The full real name is an optional additional name that can
have non-abbreviated parts or postnominal letters appended.
By default the regular real name of a user is set by the
system administrator, but that real name can be changed by
the use of this program.
By default (without any program options specified)
the regular real name of the user is printed to standard-output.
.\"_
.SS Options
The following options can be used to change the mode of operation.
.PP
.RS 5
.TP 15
\fB-u\fP  \fIusername\fP
Operate on an alternative user besides the default calling user.
Proper privileges are required for setting the origanization of
another user.
.TP 15
\fB-s\fP  \fIname\fP
This option allows for setting of a real name (either regular 
or full depending on the \fB-f\fP option) for the user.
The real name should be quoted if it contains either whitespace
or other characters that would be interpreted by a SHELL.
.TP 15
\fB-f\fP
This option specified that the fullname should be operated on
rather than the regular real name.
Without this option, only the regular real name is operated upon.
.TP 15
\fB-R\fP  \fIprogram-root\fP
This option allows for setting the program-root of the program.
This is largely used for special debugging purposes.
.TP 15
\fB-V\fP
This option makes the program print the version of the program
to standard-error and then causes the program to exit (no other
functions are performed).
.RE
.\"_
.SH ENVIRONMENT VARIABLES
.\"_
The following environment variables may change the default behavior of the
program.
.RS 5
.TP 15
.B PCSNAME_PROGRAMROOT
This environment variable is taken to contain
the program root over any other such environment variable.
The \fB-R\fP argument overides this environment variable.
.\"_
.TP 15
.B PCS
This environment variable is normally taken to contain
the program root.
The \fB-R\fP argument overides this environment variable.
.\"_
.TP 15
.B PROGRAMROOT
This environment variable is taken to contain
the program root if not other suitable environment variable
this this purpose are in the environment.
The \fB-R\fP argument overides this environment variable.
.RE
.\"_
.SH EXAMPLES
.\"_
.IP \(rh 5
simply get the current PCS regular real name of the user:
.EX
 \f(CWpcsname \fP
.EE
.IP \(rh 5
get the current PCS full real name of the user:
.EX
 \f(CWpcsname -f\fP
.EE
.IP \(rh 5
get the PCS regular real name for another user:
.EX
 \f(CWpcsname -u johny\fP
.EE
.IP \(rh 5
set the regular real name:
.EX
 \f(CWpcsname -s "Adam Smith"\fP
.EE
.IP \(rh 5
set the full real name:
.EX
 \f(CWpcsname -f -s "Adam Smith"\fP
.EE
.\"_
.SH SEE ALSO
pcsorg(1), pcsprojinfo(1), bb(1), vmail(1), msgs(1)
.\"_
.SH PATH TO
This program is currently located 
in \f(CW /usr/add-on/pcs/bin \fP
or possibly where ever PCS programs are stored on your system.
This is often 
at \f(CW ${PCS}/bin \fP
on some systems.
.\"_
.SH WARNINGS
Be careful to put at one space between all option key 
letters and the associated
key letter parameter.
.\"_
.SH ACKNOWLEDGEMENTS
All previous PCS contributors and administrators.
.\"_
.SH AUTHOR
David A.D. Morano
.\"_
.\"_
