From gmail.com!coldheartedlady Wed Jul 25 22:59:03 EDT 2007 -0400
return-path: <coldheartedlady@gmail.com>
received: from acm26-4.acm.org (acm26-4.acm.org [63.118.7.109])
 by mail.rightcore.com (DAM-MAILER) with ESMTP id 4C8DD6A8AE
 for <dam@rightcore.com>; Wed, 25 Jul 2007 22:58:41 -0400 (EDT)
received: from psmtp.com ([64.18.2.86])
 by acm26-4.acm.org (ACM Email Forwarding Service) with SMTP id FJG82840
 for <morano@acm.org>; Wed, 25 Jul 2007 22:58:40 -0400
received: from source ([209.85.146.181]) by exprod7mx91.postini.com 
	([64.18.6.14]) with SMTP;
 Wed, 25 Jul 2007 22:58:40 EDT
received: by wa-out-1112.google.com with SMTP id v27so432018wah
 for <morano@acm.org>; Wed, 25 Jul 2007 19:58:40 -0700 (PDT)
received: by 10.114.73.1 with SMTP id v1mr1282136waa.1185418720348;
 Wed, 25 Jul 2007 19:58:40 -0700 (PDT)
received: by 10.114.112.11 with HTTP; Wed, 25 Jul 2007 19:58:40 -0700 (PDT)
X-Original-To: dam@rightcore.com
Delivered-To: dam@rightcore.com
DKIM-Signature: a=rsa-sha1; c=relaxed/relaxed;
 d=gmail.com; s=beta;
 h=domainkey-signature:received:received:message-id:date:from:to:subject:in-reply-to:mime-version:content-type:content-transfer-encoding:content-disposition:references;
 b=PyhO2S2bAvyUM7cJ+SBNizLxj8fHmW0XHnu0nGtKTXFJIGWA7ehWSKpKPeYQ7HkzpfcSF986EfHG+1FWCpyeLfmoeYv6atoLNQVFFfxeksdfLIuEZKdP+PqC96iX0sCXYVknvq6EP8kA4KPPGiYJTqkZOvjU7bPDp+vJii7Rh2A=
DomainKey-Signature: a=rsa-sha1; c=nofws;
 d=gmail.com; s=beta;
 h=received:message-id:date:from:to:subject:in-reply-to:mime-version:content-type:content-transfer-encoding:content-disposition:references;
 b=eQ/yy/4V5jbMMqOoOpDeX/Pt2tbsds8Max2IhkrchdtRILBQD0kja3u86rv39DIWBM4O325b1fa9DjtzlHMDjdkA7DictEQky21z89U3HZ9Po+6CV32Vl9qcQQUMF11HSk1tlK34JrZ1BmI6QW1Az90oQJA8Sqep9SwMGmA1r+M=
In-Reply-To: <20070725223428.E0B716A8AE@mail.rightcore.com>
MIME-Version: 1.0
Content-Type: text/plain; charset=ISO-8859-1; format=flowed
Content-Transfer-Encoding: 7bit
Content-Disposition: inline
X-pstn-levels: (S:99.90000/99.90000 )
X-pstn-settings: 1 (0.1500:0.1500) gt3 gt2 gt1
X-pstn-addresses: from <coldheartedlady@gmail.com> [214/10]
References: <20070725223428.E0B716A8AE@mail.rightcore.com>
From: "Eve Silver" <coldheartedlady@gmail.com>
To: morano@computer.org, morano@ieee.org, morano@acm.org
Date: Wed, 25 Jul 2007 22:58:40 -0400
Subject: Re: test
x-message-id: <hereis3@there.com>

However! However: It is now properly reduced to the intellectual level
it merits!

Obama AND Guliana sissy girl .

Eve

On 7/25/07, morano@computer.org <morano@computer.org> wrote:
> Eve,
>
> > Is it ANY wonder why I just quit voting?
> >
> > I heartily reccommend it!
>
> Didn't I predict this?  I showed you that first "Obama-Girl"
> video and predicted that there would be "_____ Girls" for other
> candidates!  The first other "<blank> girls" were for Gulliani.
>
> I would not be surprized if we saw more "<blank> girls" for other
> candidates! :-)
>
> Dave
>
>
>
