Received: 
	from 
	person@rightcore.com
Received: 
	from 
	other_person@rightcore.com
Received: 
	from 
	third_person@rightcore.com
from:    	POP_administrator <pop>
to:      	morano
subject:	test email

This is a test.  This is a test of the emergency email/posting
system.  This is only a test.  This test has been devised
as a means of testing email or bulletin board related operations.
If this had been an actual emergency, you would have been instructed
as to where to send email (for testing purposes !).
This concludes this test of the emergency email/posting system.

PCS Administrator
