From gmail.com!coldspacemachine+caf_=dam=rightcore.com Fri Apr 04 19:50:36 USEDT 2014 -0400
return-path:  <coldspacemachine+caf_=dam=rightcore.com@gmail.com>
received: from mail-ie0-f179.google.com (mail-ie0-f179.google.com 
	[209.85.223.179])
 by mail.rightcore.com (RCMAILER) with ESMTP id 933E72EEF2
 for <dam@rightcore.com>; Fri,  4 Apr 2014 19:50:35 -0400 (USEDT)
received: by mail-ie0-f179.google.com with SMTP id lx4so4097358iec.10
 for <dam@rightcore.com>; Fri, 04 Apr 2014 16:50:35 -0700 (PDT)
received: by 10.50.41.194 with SMTP id h2csp6860igl;
 Fri, 4 Apr 2014 16:50:34 -0700 (PDT)
received: from acmsmtp01.acm.org (ACMSMTP01.acm.org. [64.238.147.78])
 by mx.google.com with ESMTPS id v93si4098234qge.132.2014.04.04.16.50.33
 for <coldspacemachine@gmail.com>
 (version=TLSv1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
 Fri, 04 Apr 2014 16:50:33 -0700 (PDT)
received: from psmtp.com
 by acmsmtp01.acm.org (ACM Email Forwarding Service) with SMTP id 
	1201404041950308200
 for <morano@acm.org>; Fri, 04 Apr 2014 19:50:30 -0400
received: from vms173017pub.verizon.net ([206.46.173.17]) by 
	na3sys009amx228.postini.com ([74.125.148.10]) with SMTP;
 Fri, 04 Apr 2014 23:50:30 GMT
received: from Joe-Meszaross-Mac-mini.local ([unknown] [71.174.27.231])
 by vms173017.mailsrvcs.net
 (Sun Java(tm) System Messaging Server 7u2-7.02 32bit (built Apr 16 2009))
 with ESMTPA id <0N3J009EG684MQ50@vms173017.mailsrvcs.net> for 
	morano@acm.org;
 Fri, 04 Apr 2014 18:50:29 -0500 (CDT)
content-length: 250                 
content-lines: 9                   
message-id: <533F4544.30105@verizon.net>
x-original-to: dam@rightcore.com
delivered-to: dam@rightcore.com
delivered-to: coldspacemachine@gmail.com
x-google-dkim-signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
 d=1e100.net; s=20130820;
 h=x-original-authentication-results:delivered-to:message-id:date:from
 :user-agent:mime-version:to:cc:subject:references:in-reply-to
 :content-type:content-transfer-encoding;
 bh=7qG94Cr7Hzql9TrsUys99Szv9xotAZtdWMr2iv5cGSY=;
 b=d/kkDtcsKUrEQ/cbmJyUVAaIlMxUjd1WCI1y0I0RsFMkmTBJo339PAiROldliZCJPo
 j2wcrZdydBjMaEiItInpZS81T0XQWkL4eeomEvJmNBqMapCXT19OP4nGYx4EqtMdPDYt
 tCYQVcIKkeIzPEmwOgz9ewqyHoN6bEyLMPIF1wyoEQe9d6d0URjaridFg+IxhG7m0u77
 Gmt8X1EEJkUJKy4fiFgqr94L8D6P4vTbGY5RfGxR1YNwQ6J+Il4E4GJiKQD1qF9YtqxZ
 LeSJB0sLSe8UNF7NbqNhdD7Xi2W9XfGcwRS7vMl2zXYLSfUfxpaGWoQd1zDyt3jb28Jc
 IZBg==
x-original-authentication-results: mx.google.com;       spf=pass 
	(google.com: domain of 
	SRS0+d4f5bdc10a4f8949=ZE=verizon.net=joe.meszaros@srs.acm.org 
	designates 64.238.147.78 as permitted sender) 
	smtp.mail=SRS0+d4f5bdc10a4f8949=ZE=verizon.net=joe.meszaros@srs.acm.org
x-received: by 10.50.62.178 with SMTP id z18mr6259300igr.49.1396655435352;
 Fri, 04 Apr 2014 16:50:35 -0700 (PDT)
x-received: by 10.224.156.204 with SMTP id 
	y12mr17869823qaw.66.1396655433965;
 Fri, 04 Apr 2014 16:50:33 -0700 (PDT)
x-forwarded-to: dam@rightcore.com
x-forwarded-for: coldspacemachine@gmail.com dam@rightcore.com
received-spf: pass (google.com: domain of 
	SRS0+d4f5bdc10a4f8949=ZE=verizon.net=joe.meszaros@srs.acm.org 
	designates 64.238.147.78 as permitted sender) 
	client-ip=64.238.147.78;
authentication-results: mx.google.com;
 spf=pass (google.com: domain of 
	SRS0+d4f5bdc10a4f8949=ZE=verizon.net=joe.meszaros@srs.acm.org 
	designates 64.238.147.78 as permitted sender) 
	smtp.mail=SRS0+d4f5bdc10a4f8949=ZE=verizon.net=joe.meszaros@srs.acm.org
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:17.0)
 Gecko/20130328 Thunderbird/17.0.5
mime-version: 1.0
x-in-reply-to: 
	<CANXuW=OHtW_RFo3wrx-S2ZYC+ycDkELe1cPF9v-CoFHLdocPMA@mail.gmail.com>
content-type: text/plain; charset=ISO-8859-1; format=flowed
content-transfer-encoding: 7bit
x-pstn-levels: (S:99.90000/99.90000 CV:99.9000 FC:95.5390 LC:95.5390 
	R:95.9108 P:95.9108 M:97.0282 C:98.6951 )
x-pstn-dkim: 0 skipped:not-enabled
x-pstn-settings: 3 (1.0000:1.0000) s cv gt4 gt3 gt2 gt1
x-pstn-addresses: from <joe.meszaros@verizon.net> forward (user good) 
	[3193/157]
status: 
x-references: 
	<CANXuW=OHtW_RFo3wrx-S2ZYC+ycDkELe1cPF9v-CoFHLdocPMA@mail.gmail.com>
From:  Joe Meszaros <joe.meszaros@verizon.net>
To:  Dell Morano <dell.morano@gmail.com>
cc:  David Morano:ACM <morano@acm.org>, Philip Dell'Orfano Morano
 <pmorano@gmail.com>
x-Date: Fri, 04 Apr 2014 19:50:28 -0400
Subject: Re: didcha know?


My understanding is that Jimmy Fallon is clobbering him in the ratings, 
so he's choosing to bow out.

On 4/4/14 7:03 AM, Dell Morano wrote:
> I dunno if you guys know that David Letterman is 
> retiring...but...rather suddenly....questions?
> mom

