From joe.meszaros@nii.net Tue Mar 28 19:57:36 2000 
Received: from lochinvar.ece.neu.edu (lochinvar.ece.neu.edu [129.10.60.161])
	by Mail2.coe.neu.edu (8.9.3/8.9.1) with ESMTP id TAA22265
	for <morano@coe.neu.edu>; Tue, 28 Mar 2000 19:57:35 -0500 (EST)
Received: from sendmail1.computer.org (sendmail1.computer.org [206.99.235.24])
	by lochinvar.ece.neu.edu (8.9.3/8.9.3) with ESMTP id TAA13078
	for <dmorano@ece.neu.edu>; Tue, 28 Mar 2000 19:58:01 -0500 (EST)
Received: from baron.nii.net (baron.nii.net [209.113.172.16])
          by sendmail1.computer.org (2.0 Build 2119 (Berkeley 8.8.4)/8.8.4) with ESMTP
	  id TAA08596 for <morano@computer.org>; Tue, 28 Mar 2000 19:57:58 -0500
Received: from nii.net (xcom19.nii.net [209.113.173.83])
	by baron.nii.net (8.9.3/8.9.3) with ESMTP id TAA13961
	for <morano@computer.org>; Tue, 28 Mar 2000 19:56:52 -0500
Message-ID: <38E1548A.66E6AD65@nii.net>
Date: Tue, 28 Mar 2000 19:55:38 -0500
From: Joe Meszaros <joe.meszaros@nii.net>
X-Mailer: Mozilla 4.72 [en] (Win98; U)
X-Accept-Language: en
MIME-Version: 1.0
To: Dave <morano@computer.org>
Subject: CyberPatrol Update - Mattel Wins?
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit
Content-Length: 73

The silly becomes scary.

http://slashdot.org/yro/00/03/27/1736221.shtml

