From morano Fri May 21 16:55:22 EDT 2004
return-path: <joe.meszaros@nii.net>
received: from orca.ele.uri.edu [131.128.51.63]
	by localhost with POP3 (fetchmail-6.2.5)
	for morano@localhost (single-drop); Fri, 21 May 2004 16:55:22 -0400 (EDT)
received:  from leviathan.ele.uri.edu (leviathan [131.128.51.64])
	by ele.uri.edu (Cyrus v2.2.3) with LMTP; Fri, 21 May 2004 16:55:12 -0400
received:  from Flemming.computer.org (flemming.computer.org [206.99.235.24])
	by leviathan.ele.uri.edu (8.12.9/8.12.9) with ESMTP id i4LKt94h008926
	for <morano@ele.uri.edu>; Fri, 21 May 2004 16:55:10 -0400 (EDT)
received:  from smtp.nii.net (smtp.nii.net [209.113.172.8])
	by Flemming.computer.org (Switch-2.2.8/Switch-2.2.4) with ESMTP id W4LK2J49000034F0
	for <morano@computer.org>; Fri, 21 May 2004 16:55:04 -0400
received:  from [4.156.66.50] (dialup-4.156.66.50.Dial1.Boston1.Level3.net [4.156.66.50])
	by smtp.nii.net (Postfix) with ESMTP
	id 1FF9633993; Fri, 21 May 2004 16:57:38 -0400 (EDT)
content-length: 1680            
message-id: <83FF18A8-AB67-11D8-8FF7-000A959B575E@nii.net>
X-Sieve: CMU Sieve 2.2
In-Reply-To: <rca990910851057981103181@rightcore.com>
Mime-Version: 1.0 (Apple Message framework v609)
Content-Type: text/plain; charset=US-ASCII; delsp=yes; format=flowed
Content-Transfer-Encoding: 7bit
Cc: dell@nii.net (A. Morano)
X-Mailer: Apple Mail (2.609)
X-DCC-MessageCare-Metrics: leviathan 1108; Body=1 Fuz1=1 Fuz2=1
X-Spam-Status: No, hits=-4.7 required=8.0
	tests=EMAIL_ATTRIBUTION,IN_REP_TO,QUOTED_EMAIL_TEXT,REFERENCES,
	SPAM_PHRASE_00_01,USER_AGENT_APPLEMAIL
	version=2.43
X-Spam-Level: From: Joe Meszaros <joe.meszaros@nii.net>
To: morano@computer.org (David Morano)
References: <rca990910851057981103181@rightcore.com>
Date: Fri, 21 May 2004 16:43:29 -0400
Subject: Re: Chornobyl "Ghost Town" story is a fabrication

Keep trying that site, it's pretty damning. That whole site, Urban  
Exploration Resource, is dedicated to exploring abandoned areas, so  
it's no airhead blog. If this guy's just blowing wind the regulars will  
cut him a new one.

 From what I've read there and on slashdot I'm convinced she's a fake.  
Notice how she has changed her site a few times, and her own  
explanation page with a non-apology apology.

Note that the only scam part is that she rode her motorcycle through  
the town. The pictures she took are real, but she was part of a guided  
tour, not riding on her own.

You and several others have joked about her being married. All joking  
aside, that fits into the scam. She was selling a total fantasy, and  
she did it like a pro. Likely she and her husband are natural liars,  
much like the Clintons. That's the impression I get.

There are other web sites with pictures from this town. It was the  
pretty (single) girl with motorcycle angle that set her site apart,  
indeed put the whole thing on everyone's radar.

Keep trying that site.

http://www.uer.ca/forum_showthread.asp?fid=1&threadid=8951

The SlashDot article is a mix of subjects:

http://slashdot.org/article.pl?sid=04/05/20/ 
236211&mode=thread&tid=103&tid=167&tid=98&tid=99

Elana's "apology:"

http://www.angelfire.com/extreme4/kiddofspeed/

If you can't get through I'll send the whole thing.

On May 20, 2004, at 10:16 PM, David Morano wrote:

>> "I am sorry to report that much of Elena's story is not true. She did
>
> Elena's web page is still there.  I can't get to the
> accuser's web page (it's off-line, broken, whatever).
> Who am I supposed to believe ? :-) :-)
>
> Dave
>

