Date: Wed, 6 Jan 2003 09:45:45 -0500 (EST)
x-Date: Wed, 6 Jan 2003 09:45:45 -0700 (MST)
from:    	d.a.morano <dam@other.rightcore.com> (Dave Morano)
to:      	morano@ele.uri.edu
subject:	test email (this is a test)

This is a test.  This is a test of the emergency email/posting
system.  This is only a test.  This test has been devised
as a means of testing email or bulletin board related operations.
If this had been an actual emergency, you would have been instructed
as to where to send email (for testing purposes !).
This concludes this test of the emergency email/posting system.

PCS Administrator
