#!/bin/ksh
# AUDIOPLAY-AIF


if [ -n "${1}" ] ; then
  FILES=${*}
else
  FILES="-"
fi

TF=${TMPDIR:-/tmp}/ap${$}

cleanup() {
  rm -f $TF
}


trap 'cleanup ; exit 1' 1 2 3 15 16 17

for F in $FILES ; do

  if [ -r $F ] ; then

    sox -r 44100 -c 2 $F -t au -r 44100 -c 2 $TF
    if [ -r $TF ] ; then
      audioplay -v 100 -p line $TF
    fi

  fi

done

cleanup


