#!/usr/bin/ksh
# CHANGE


NAMES=
NAMES="${NAMES} misc.h"


for F in "${@}" ; do

  if [[ -r "${F}" ]] ; then

    for N in $NAMES ; do

      fgrep "${N}" $F > /dev/null
      if [[ $? -eq 0 ]] ; then

      ed - $F <<\EOF
	g/misc.h/s//localmisc.h/g
	g/locallocalmisc.h/s//localmisc.h/g
	w
	q
EOF

      fi

    done

  fi

done


