.\"_
.TH BATCH 1 "1997-02-27" NCMP
.SH NAME
batch \- submit a shell script to a daemon for low-priority batched execution
.SH SYNOPSIS
.B batch
[
\fBoptions\fP
]
queue_name
[
shell_file ...
]
.br
.B batch
[
\fBoptions\fP
]
queue_name
\fB\-c\fR "command"
.SH DESCRIPTION
.B Batch
is used to submit a command or list of commands to be executed by the
shell possibly at a later time when system resources are available.
This allows the system to restrict the number of jobs of a particular
class that are executed simultaneously, and to adjust the number
based on criteria such as the current system load.
Jobs are started and stopped according to such criteria.
.PP
In the first form, the contents of the specified files are concatenated
together, saved away in a system spool directory, and then passed to the
shell (as set by environment variable $SHELL at the time
.I batch
was called) at execution time.
If no files are specified, the standard input is read.
.PP
In the second form, a command string is supplied using
.I \-c,
no input files may be given, and the standard input is not read.
.PP
Most, but not all, environment variables are also copied to the
beginning of the spooled command file.
.PP
The
.B queue_name
argument is the name of the queue to submit to.
Queues are often named by what kind of thing usually goes into them
or by what service they provide;
they can actually contain any kind of command script you like.
See the "QUEUE NAMES" section below.
.PP
Mail will be returned to you at the end of the job if the job exits with
a non-zero status return or produces any output.
Mail may also be sent to you, depending on the individual queue, upon
job start, system crash, or successful execution with no output.
If mail is sent, the first few lines of the batch command list
will be included to help make it obvious which command caused
the output.
.SH OPTIONS
.IP "\-P grade"
Set the job priority to \fBgrade\fP,
which should be a letter from
.I a
to
.I z.
This priority determines which job will be selected next after one of
the current jobs in the queue finishes.
The highest priority is
.I a
and the default is
.I q.
Priorities in the range from
.I a
to
.I g
are reserved to the super-user.
Once a job has started, it is never pre-empted; it runs until it finishes.
The queue priority merely adjusts which job will be selected next.
If selected when the batch system was compiled, the priority of new
jobs will be automatically lowered by taking into account how many
jobs you have already submitted to this queue; this is to try to prevent
a user from "hogging" the queue.
.IP \-v
Print the name of the spool file created.
.IP "\-j jobname"
Set the name of the job to \fBjobname\fR.
The job name appears in mail messages from the batch daemon.
.IP "\-m mailaddress"
Send mail concerning this job to \fBmailuser\fP
instead of the current user.
.IP \-f
For csh or tcsh users, the \-f option prevents shell from reading
the ~/.cshrc file (i.e. the -f flag is passed to the shell).
.IP "\-d directory"
.IP "\-p file"
.IP "\-u user"
The \-d, \-u and \-p options are for administrative use: \-d specifies
an alternate spool directory, \-p specifies the batch daemon's ``pidfile'',
and \-u submits the job as the named \fBuser\fP.
.SH QUEUE NAMES
Batch queue names and characteristics are set up by
your system adminstrator.
The command:
.PP
	ls SPOOLDIR
.PP
will list the queue directories available on your machine.
The characteristics of each queue are listed in the file named
.I profile
file in each directory.
The file SPOOLDIR/.README should contain information on
the available queues.
.SH "SEE ALSO"
batchd(1m), nice(1), renice(1m), batchqueue(1), batchcancel(1),
batchsignal(1), batchexamine(1)
.SH BUGS
.PP
If you don't have permission to determine the current working directory
then the shell file may execute under the spool directory when it runs.
.PP
Some queues are named by the type of thing that usually gets put into
them; they should be named by the type of service they provide.
.PP
Using letters to indicate priority is strange.
A numbering system would be more natural.
One based on
.IR nice (1)
wouldn't be too bad.
.\"_
