.\"_
.TH BATCHEXAMINE 1 "1997-02-27" NCMP
.SH NAME
batchexamine \- examine output from jobs running in specified batch queues
.SH SYNOPSIS
.B batchexamine
[
.B -q queue_name
]
.SH WHERE
.B queue_name
is the queue you want to check.
.SH EXAMPLES
batchexamine
.br
batchexamine -q 'vlsi*'
.SH DESCRIPTION
.I Batchexamine
displays the standard output for the jobs running in each of the specified 
batch queues.  The queue_name can be any regular expression needed to
specify the desired batch queue(s).
.PP
If no arguments are given, the output file from each running job is displayed.
You can only look at output from your own jobs.
.PP
.I Batchexamine
will use the program specified by the $PAGER environment
variable (default: "more") to page the output.
.PP
See
.IR batch (1)
for a description of queue priorities.
.PP
If the '.queueorder' file is present in the batch queue directory,
the queues are searched in the order they are listed in that file
(one queue name per line). The
.B \-q
option overrides this feature.
.SH FILES
.nf
.DT
SPOOLDIR/*/of[a-z]*		\- output files
SPOOLDIR/.queueorder		\- display queues in this order
.fi
.SH "SEE ALSO"
batchcancel(1), batch(1), batchqueue(1), batchsignal(1), batchd(1m)
.SH "NOTE"
User names and queuenames that are not valid
.IR regex(3)
regular expressions
will cause errors. (ie. '.' matches any one character. '*' matches any number
of the previous character. '^' denotes the start of text and '$' denotes 
the end.)
.\"_
