#!/usr/bin/ksh
# SUBTEST


for I in a b c d e f g h i j k l ; do
  {
  print print start
  print date
  print "# index=${I}"
  print print index=${I}
  print sleep 60
  print print end
  print date
  } | jobsub &
done



