#!/usr/extra/bin/ksh
# CHANGE

NAMES=
NAMES="${NAMES} %w"


DN=/dev/null
builtin fgrep 2> ${DN}


for F in "${@}" ; do

  if [[ -r "${F}" ]] ; then

    for N in ${NAMES} ; do

      if fgrep $N $F > ${DN} ; then

      ed - $F <<\EOF
	g/%w/s//%t/g
	w
	q
EOF

      fi

    done

  fi

done


