From mach1!mach2!other Thu Apr 17 02:12 EDT 1997
from:    	PCS_administrator <hocpa!dam>
Path: mach1!mach2
Return-Path: mach1!mach2!other
to:      	hocpa!dam
subject:	test email/posting 2
date:           02 Dec 93 12:26:33

This is a test.  This is a test of the emergency email/posting
system.  This is only a test.  This test has been devised
as a means of testing email or bulletin board related operations.
If this had been an actual emergency, you would have been instructed
as to where to send email (for testing purposes !).
This concludes this test of the emergency email/posting system.

PCS Administrator

