/* config */


#define	VERSION		"0a"
#define	WHATINFO	"@(#)TESTUSERINFO "
#define	BANNER		"Test UserInfo"
#define	SEARCHNAME	"testuserinfo"
#define	VARPRNAME	"LOCAL"

#ifndef	PROGRAMROOT
#define	PROGRAMROOT	"/usr/add-on/local"
#endif

#define	VARPROGRAMROOT1	"TESTUSERINFO_PROGRAMROOT"
#define	VARPROGRAMROOT2	VARPRNAME
#define	VARPROGRAMROOT3	"PROGRAMROOT"

#define	VARBANNER	"TESTUSERINFO_BANNER"
#define	VARSEARCHNAME	"TESTUSERINFO_NAME"
#define	VAROPTS		"TESTUSERINFO_OPTS"
#define	VAREFNAME	"TESTUSERINFO_EF"
#define	VARERRORFNAME	"TESTUSERINFO_ERRORFILE"

#define	VARDEBUGFNAME	"TESTUSERINFO_DEBUGFILE"
#define	VARDEBUGFD1	"TESTUSERINFO_DEBUGFD"
#define	VARDEBUGFD2	"DEBUGFD"

#define	VARNODE		"NODE"
#define	VARSYSNAME	"SYSNAME"
#define	VARRELEASE	"RELEASE"
#define	VARMACHINE	"MACHINE"
#define	VARARCHITECTURE	"ARCHITECTURE"
#define	VARCLUSTER	"CLUSTER"
#define	VARSYSTEM	"SYSTEM"
#define	VARNISDOMAIN	"NISDOMAIN"
#define	VARTERM		"TERM"
#define	VARPRINTER	"PRINTER"
#define	VARLPDEST	"LPDEST"
#define	VARPAGER	"PAGER"
#define	VARMAIL		"MAIL"
#define	VARORGANIZATION	"ORGANIZATION"
#define	VARLINES	"LINES"
#define	VARCOLUMNS	"COLUMNS"
#define	VARNAME		"NAME"
#define	VARFULLNAME	"FULLNAME"
#define	VARHZ		"HZ"
#define	VARTZ		"TZ"
#define	VARUSERNAME	"USERNAME"
#define	VARLOGNAME	"LOGNAME"

#define	VARHOMEDNAME	"HOME"
#define	VARTMPDNAME	"TMPDIR"
#define	VARMAILDNAME	"MAILDIR"
#define	VARMAILDNAMES	"MAILDIRS"

#define	VARPRLOCAL	"LOCAL"
#define	VARPRPCS	"PCS"

#define	TMPDNAME	"/tmp"

#define	CONFIGFNAME	"etc/testuserinfo/conf"
#define	LOGFNAME	"log/testuserinfo"
#define	HELPFNAME	"help"

#define	PO_SUFFIX	"suffix"
#define	PO_OPTION	"option"


