#!/usr/bin/ksh
# CHANGE


NAMES=
NAMES="${NAMES} secure_acctab"


for F in "${@}" ; do

  if [[ -r "${F}" ]] ; then

    for N in ${NAMES} ; do

      if fgrep "${N}" $F > /dev/null ; then

      ed - $F <<\EOF
	g/secure_acctab/s//secure_accfile/g
	w
	q
EOF

      fi

    done

  fi

done


