#!/usr/bin/ksh
# CHANGE


NAMES=
NAMES="${NAMES} sysmisc.hostinfo"


for F in "${@}" ; do

  if [[ -r "${F}" ]] ; then

    for N in $NAMES ; do

      fgrep "${N}" $F > /dev/null
      if [[ $? -eq 0 ]] ; then

      ed - $F <<\EOF
	g/sysmisc\.hostinfo/s//sysmisc_hostinfo/g
	w
	q
EOF

      fi

    done

  fi

done


