#!/usr/bin/ksh
# CHANGE


NAMES=
NAMES="${NAMES} f.unline"


for F in "${@}" ; do

  if [[ -r "${F}" ]] ; then

    for N in $NAMES ; do

      fgrep "${N}" $F > /dev/null
      if [[ $? -eq 0 ]] ; then

      ed - $F <<\EOF
	g/f.unline/s//f.bufun/g
	w
	q
EOF

      fi

    done

  fi

done


