From uucp Thu Sep 25 23:46:40 USEDT 2014 -0400 remote from rcb
>From uucp Thu Sep 25 23:47:40 USEDT 2014 -0400 remote from rca
>From a!dam  Thu Sep 25 23:48:40 USEDT 2014 -0400
x-priority: 5 (low)
from:    	PCS_administrator <mtgbcs!pcs>
path:		place
to:      	bb (ha, ha !)
subject:	test email/posting
newsgroups:	test

This is a test.  This is a test of the emergency email/posting
system.  This is only a test.  This test has been devised
as a means of testing email or bulletin board related operations.
If this had been an actual emergency, you would have been instructed
as to where to send email (for testing purposes !).
This concludes this test of the emergency email/posting system.

PCS Administrator
