/* config */


#define	VERSION		"0a"
#define	WHATINFO	"@(#)CAT "
#define	BANNER		"Concatenate"
#define	SEARCHNAME	"cat"
#define	VARPRNAME	"LOCAL"

#define	VARPROGRAMROOT1	"CAT_PROGRAMROOT"
#define	VARPROGRAMROOT2	VARPRNAME
#define	VARPROGRAMROOT3	"PROGRAMROOT"

#define	VARBANNER	"CAT_BANNER"
#define	VARSEARCHNAME	"CAT_NAME"
#define	VAROPTS		"CAT_OPTS"
#define	VARFTYPES	"CAT_FTYPES"
#define	VARSUFREQ	"CAT_SUFREQ"
#define	VARSA		"CAT_SUFACC"
#define	VARSR		"CAT_SUFREJ"
#define	VARTARDNAME	"CAT_TARDIR"
#define	VARAFNAME	"CAT_AF"
#define	VAREFNAME	"CAT_EF"

#define	VARDEBUGFNAME	"CAT_DEBUGFILE"
#define	VARDEBUGFD1	"CAT_DEBUGFD"
#define	VARDEBUGFD2	"DEBUGFD"

#define	VARNODE		"NODE"
#define	VARSYSNAME	"SYSNAME"
#define	VARRELEASE	"RELEASE"
#define	VARMACHINE	"MACHINE"
#define	VARARCHITECTURE	"ARCHITECTURE"
#define	VARCLUSTER	"CLUSTER"
#define	VARSYSTEM	"SYSTEM"
#define	VARNISDOMAIN	"NISDOMAIN"
#define	VARTERM		"TERM"
#define	VARPRINTER	"PRINTER"
#define	VARLPDEST	"LPDEST"
#define	VARPAGER	"PAGER"
#define	VARMAIL		"MAIL"
#define	VARORGANIZATION	"ORGANIZATION"
#define	VARLINES	"LINES"
#define	VARCOLUMNS	"COLUMNS"
#define	VARNAME		"NAME"
#define	VARFULLNAME	"FULLNAME"

#define	VARHOMEDNAME	"HOME"
#define	VARTMPDNAME	"TMPDIR"
#define	VARMAILDNAME	"MAILDIR"
#define	VARMAILDNAMES	"MAILDIRS"

#define	VARPRLOCAL	"LOCAL"
#define	VARPRPCS	"PCS"

#ifndef	PROGRAMROOT
#define	PROGRAMROOT	"/usr/add-on/local"
#endif

#define	TMPDNAME	"/tmp"

#define	CONFIGFNAME	"etc/cat/conf"
#define	LOGFNAME	"log/cat"
#define	HELPFNAME	"help"


