'\" t
.TH MXAUDIO 1 1995-02-13 NCMP
.SH NAME
mxaudio \- X-Window graphical MP3 audio player
.SH SYNOPSIS
.BR mxaudio
.SH DESCRIPTION
.sp
.SS Introduction
This program is an X-Window graphical user interface program
for playing MP3 audio files.
.SH SEE ALSO
rxaudio(1)
.\"_
.SH PATH TO
This program is currently located in the 
directory \fC/usr/add-on/ncmp/bin\fP.
This is often at
.MW "${NCMP}/bin"
on some systems.
.\"_
.SH CAVEATS
I really have no idea what the full extent of this program is.
.\"_
.SH WARNINGS
We do not have source code to this program.
It is from some company out on the Net !
.\"_
.SH AUTHOR
Xaudio company ?
.\"_
.SH ACKNOWLEDGEMENTS
Some company out on the Net.
.\"_
.\"_
