#!/usr/bin/ksh
# INSTALLPROG (libut)


: ${LOCAL:=/usr/add-on/local}
: ${NCMP:=/usr/add-on/ncmp}
: ${PCS:=/usr/add-on/pcs}
export LOCAL NCMP PCS




if [ -d /usr/sbin ] ; then
  MACH=$( uname -n )
  : ${OFD:-S5}
else
  MACH=$( hostname )
  PATH=/usr/5bin:${PATH}
  : ${OFD:-S4}
fi


TF=/tmp/ip${$}

cleanup() {
  rm -f $TF
}

trap 'cleanup ; exit 1' 1 2 3 15 16 17


makeit


find *.h -type f -print > $TF

for D in ${HOME} ${LOCAL} ${NCMP} ${PCS} ; do

  makeit SRCROOT=${D} install
  makenewer -af $TF -d ${D}/include/

done


cleanup



