#!/usr/bin/ksh
# CHECKIT


TF1=/tmp/base64a${$}
TF2=/tmp/base64b${$}

cleanup() {
  rm -f ${TF1} ${TF2}
}

trap 'cleanup ; exit 1' 1 2 3 15 16 17

find * -type f -print | while read F J ; do

   base64.x -e ${F} > ${TF1}
   base64.x -d ${TF1} > ${TF2}
   cmp ${F} ${TF2}
   if [[ $? -ne 0 ]] ; then
     echo "${0}: bad compare ${F}" >&2
   fi

done

cleanup


