.'\"_
.TH PCSMAIL 1 1997-05-16 PCS
.ad b
.SH NAME
pcsmail \- new improved mail sending service
.SH SYNOPSIS
pcsmail
[recipients]
[\f(CW-\fP]
[\(+-delivery]
[\(+-edit]
[\(+-notify]
[\(+-verify]
[\(+-filecopy]
[\(+-internet]
.br
.RS 10
[copy_to=[]]
.br
[bcc=[]]
.br
[subject=[]]
.br
[keywords=[]]
.br
[file=[]]
.br
[append=[]]
.br
[message=[]]
.RE

.\"_
.SH DESCRIPTION
.PP
The \f(CWpcsmail\fP program provides
enhancements over standard UNIX mail
that include
preparing and editing messages,
mailing to distribution lists,
addressing real names,
addressing in the ARPAnet RFC822 standard form,
notifying recipients of incoming mail,
acknowledging mail delivery, and notifying users in case of failure 
to deliver mail. 
This program is part of the
Personal Communication Services (PCS) system.
In addition, it provides an interface with the PCS 
bulletin board service.  The \f(CWpcsmail\fP program
can be used in lieu of bbpost to post
a bulletin board message.  It can also be used for posting articles on
the planetary NetNews network.  These interfaces are accessed by addressing the
message appropriately as described below.
.\"_
.SH "INVOCATION OF SMAIL"
.PP
The \f(CWpcsmail\fP program
is used for preparing and sending messages.
When called without arguments, it prompts for
information such as recipients (TO),
subject (SUBJECT),
and message.
It also optionally prompts
for a carbon-copy list (CC), blind-copy list (BCC) and keywords (KEYWORDS).
The \f(CWpcsmail\fP program
automatically adds
.MW FROM,
.MW MESSAGE-ID 
(if configured to do so)
and
.MW DATE
information.
After the message is entered, the user is prompted to enter one of the
following commands :
.RS 5
.TP 10
.I Command
.I Action
.TP
.B send
Send mail to recipients.
The user is prompted to enter one or more of the following options:
.RS 10
.TP 10
.B standard
Send mail without notifying recipient.
.TP
.B notify
Notify recipient of incoming mail.
.TP
.B delivery
Send delivery acknowledgement back to the sender when the mail is
actually delivered to the recipient. This feature, like notification, works 
across machine boundaries.
(normally, delivery is not acknowledged)
.TP
.B verify
Verify that all messages were sent.
(Normally, mail to recipients in mailing lists are not verified.)
.TP 
.B filecopy
Put a copy of the message in the user's copy file
.MW ("$HOME/mail/copy").
.RE
.TP 10
.B review
Print the message for review.
.TP
.B check
Print the translated names of the recipients.
.TP
.B edit
Edit the message (data fields can be edited).
.TP
.B quit
Quit without sending the message.
.RE
.PP
The user's environment variable
.\"_
.B SMAILOPTS
can be used to control the prompts and set default sending options
(see
.I VARIABLES
section).
.PP
Besides the recipients, a number of options and keywords may be
specified on the command line.  Each
option or keyword may be specified in as few characters
as necessary to distinguish
it from another valid option or keyword.
Options are preceded by a + ("yes") or - ("no").
Keywords are specified as "\fIkeyword_name=string_value\fP",
for example : 
.MW "copy=schatz"
or 
.MW "file=mail.doc"
\&.
When called with these arguments,
the \fIpcsmail\fP program
does the following:
.RS 6
.TP 12
.I Option
.I Action
.TP
.B -
Suppresses all prompting.  This is useful for sending mail with the mail
message on standard input when the standard input is a character special
device.  Normally, when standard input is a character special device,
\f(CWpcsmail\fP goes into interactive mode (the usual case).
.TP
.B edit
Invoke the editor to enter the message.
.TP
.B notify
Notify recipient of incoming mail.
.TP
.B delivery
Send delivery acknowledgement to the sender.
.TP
.B verify
Verify that all messages were sent.
.TP
.B filecopy
Put copy of message in user's copy file.
.TP
.B internet
Add address in the FROM: field in the internet form.
.TP 12
.I Keyword
.I Action
.TP
.B copy_to
Send a carbon copy to the remaining recipients
named in argument.
Prompt if none are named.
.TP
.B bcc
Send blind copy to the recipients named in the argument.
Prompt if none are named.
.TP
.B subject
Use  argument as the subject field.
.TP
.B keywords
Use argument
for keywords.  Prompt if none is provided.
.TP
.B file
Use the file named in the argument
for the message.
This option can be used to redirect
dead letters (eg, \f(CWpcsmail newperson file=dead.letter\fP).
.TP
.B message
Use argument for the message.
.TP
.B append
Append the file named in argument
to the message.
.RE
.\"_
.SH "MAIL ADDRESSING"
.PP
Several forms of email addresses are recognized.  Most addresses
are interpreted
by the \f(CWpcsmail\fP user agent program itself, but system aliases
are currently only interpreted by mail delivery agents like
\fIsendmail(8)\fP.  Note that addresses are interpreted in a priority
fashion.  The order of address interpretation is aligned with the
procedure described for the AT&T Electronic Mail System.
The recipients may be addressed as any of the following in the
order of first recognized to last recognized :
.RS 8
.TP 15
.B !login
A login name (ie: \f(CW!dam\fP).  This form forces the address is be
interpreted as a login name on the local machine cluster.
.TP
.B login
A login name (eg, \f(CWdam\fP)
.TP
.B name
A real name
(eg, \f(CWd.a.morano\fP, or \f(CWmorano\fP).  This form of address is
referred to as an \fBE\fPlectronic \fBM\fPail \fBN\fPame (or
\fBEMN\fP) according to the AT&T Electronic Mail System.
.TP
.B initials
Initials (ie: \f(CWd.a.m.\fP).
.TP
.B alias
An alias (eg, \f(CWadmin\fP).
.TP
.B \~list
A distribution list (ie: \f(CW~j-d-palframan\fP, 
alternatively \f(CW_j-d-palframan\fP).
.TP
.B system!login
An explicit login name (eg, \f(CWmtgbcs!dam\fP).  This form of address
is referred to as an \fBE\fPlectronic \fBM\fPail \fBA\fPddress (or
\fBEMA\fP as an abreviation) according to the 
AT&T Electronic Mail System.
.TP
.B user@system[.domain]
An internet address (eg, \f(CWdam@mtgbcs\fP,
\f(CWjohnp@mtgbcs\fP, \f(CWother.person@hocsd.uucp\fP, 
\f(CWother.again@mit-mc.arpa\fP).
.RE
.sp
All unrecognized addresses (except explicit login names using the
\f(CW!login\fP address form) are passed on to a configured mail delivery agent
for possible interpretation by it.
.PP
All non-login addresses are mapped into login addresses using a master 
translation table.
The master translation table is
formed from the files specified in a default list. 
If the shell variable
\f(CWSMAILNAMES\fP is defined then it overrides the default list, and
a list of tables is picked up from it.
The file names must be separated by colons (':'s), e.g. 
\f(CWa/b/c:p/q/r:d/e\fP.
These include personal, standard, and public tables.
.PP
If the name is not found in any of these tables, then
\f(CWpcsmail\fP
performs an AT&T POST query on the name.  This searches the
the AT&T corporate name directory for a possible email address.
.PP
All names, except explicit login names or network addresses, are
translated to system and login names using the master PCS
translation database or the AT&T corporate POST database.
The standard PCS name directory database is
maintained by the local system
administrator and usually contains information about local or remote users
which is not known (or not correct) in the AT&T corporate POST database.
.PP
The \f(CWpcsmail\fP program
prefers unique references to names and complains otherwise.
Certain names, such as "\f(CWmiller\fP" and "\f(CWjam\fP",
are ambiguous and require a more specific reference 
(eg, "\f(CWj.a.miller\fP").
In any event, when such an ambiguous address specification is encountered,
the user is given an opportunity to select one of the several that the
specification matched.
.PP
Addresses to a machine in the planetary UUCP domain should be
qualified with at least the top level domain of \f(CBuucp\fP.
For example, to mail to a \fBem\fPail \fBa\fPddress
\&(EMA) 
.MW "ucbvax!john"
where the machine 
.MW ucbvax
is outside of AT&T and accessible by 
the planetary UUCP
network, the EMA address should be given as 
.MW "ucbvax.uucp!john"
instead.  Otherwise the address might be confused with an internal AT&T
machine.  All EMAes given in the form \f(CWmachine!user\fP are
strictly interpreted to refer to firstly as a machine locally
accessable to the local machine and next as a machine within AT&T
which is registered with AT&T Action Central.
.PP
Some addresses are recognized as special.  If an address is given
in the form \f(CWd.a.morano@att.com\fP, a search is performed on the
name using the local translation database and failing that, the
AT&T corporate POST name directory database.
.\"_
.SH "STRUCTURE OF THE MESSAGE"
.PP
A mail message as constructed by
\f(CWpcsmail\fP
consists of a header, followed by a blank line, followed by the body of the
message. Each line in the header constitutes a header field
of a specific type. The type of the field
is identified by the first word of the line. 
This word is the keyword that
identifies the field, and must be in capital letters, ending in a ':'.
The rest of the line is
interpreted according to the type of the line.
The header fields and the corresponding
keywords are as follows:
.RS 4
.TP 12
.I field
.I keyword
.TP
from
FROM:
.TP
to
TO:
.TP
date
DATE:
.TP
sender
SENDER:
.TP
copy_to
CC:
.TP
bcc
BCC:
.TP
subject
SUBJECT:
.TP
keywords
KEYWORDS:
.TP
reference
REFERENCE:
.TP
message ID
MESSAGE-ID:
.RE
.PP
The TO:, CC:, and BCC: fields consist of a list of addresses separated by
commas. 
\f(CWpcsmail\fP
can be forced to use a particular address for a particular name by
specifying the address enclosed withinin a "<>" pair following the name. For
example, "d.a.morano\ <mtother!dam>" will 
force the mail to be sent to "mtother!dam"
although, "d.a.morano" normally translates to "mtgbcs!dam".
.PP
The fields mentioned above can  be added to the message by editing the
appropriate line into the header. For example, the line "SUBJECT:\ test"
added to the beginning of the message has the same effect as typing
"subj=test" in the command line. 
.PP
Any line in the body of the message that begins with a CC: or a BCC: is
assumed to be part of the header. They are moved from the body of the
message to the header and the rest of the line is interpreted as a list of
recipients, as if the line had originally been typed into the header.
Use of multiple CC: and BCC: lines are thus permitted. None of the other
header lines are picked up from the body of the message. They must appear
in the header of the message to be effective, and there must  be at most one
of them in the header. The TO: field is mandatory.
.PP
If the FROM: line is found to have been changed by the user, 
\f(CWpcsmail\fP
will add a SENDER: line to the header containing the true identity of the
sender. The FROM: line will be left unchanged.
.SH ENVIRONMENT VARIABLES
.PP
This program uses a number of environment variables to
set default actions for the program.
The PCS program \fIpcssetup\fP is normally used to set a user up
initially with some reasonable defaults for these variables but
a user may modify these as desired also.
.PP
.TP 12
.B ED
The program to use for the editor.
.TP
.B SMAILOPTS
Default options,
separated by a ":", are selected from the following list :
.nf
	standard
	notify
	verify
	filecopy
	edit
	copyto
	keywords  
	internet
	delivery
	name
	fullname
.fi
.sp
For example \f(CWSMAILOPTS=+standard:+edit:+delivery\fP
.TP 12
.B SMAILLISTS
A list of directories, separated by a ":",
which contain mailing lists. If SMAILLISTS is not defined, a 
default set of directories are used.
.TP
.B SMAILNAMES
A list of files, separated by a ":", which contain
translation information. 
If the SMAILNAMES variable is not set, a default list is used.
The default list does not contain a file for user's personal list.
.SH FILES
.PD 0
.TP 30
\f(CW${PCS)/lib/pcsmail\fP
directory for translation and path tables
.TP
\f(CW${PCS}/bin/pcsmail\fP
executable program
.TP
\f(CW/tmp/pcsmailXXXXXX\fP
temporary file for message
.TP
\f(CW/var/spool/mail/${LOGNAME}\fP
file for incoming mail
.TP
\f(CW${HOME}/mail/copy\fP
file for mail copies
.PD
.\"_ .SH CAVEATS
.\"_
.SH "SEE ALSO"
profiler(PCS), vmail(PCS), readnews(NCMP), pc(PCS), pcsinfo(PCS)
.\"_
