#!/usr/bin/ksh
# CHANGE


NAMES=
NAMES="${NAMES} entered"


for F in "${@}" ; do
  if [[ -r "${F}" ]] ; then
    for N in ${NAMES} ; do
      if fgrep "${N}" $F > /dev/null ; then
      ed - $F <<\EOF
	g/: entered/s//: ent/g
	w
	q
EOF
      fi
    done
  fi
done


