#!/usr/bin/ksh
# CHANGE


NAMES=
NAMES="${NAMES} subinfo_init locinfo_init"


for F in "${@}" ; do

  if [[ -r "${F}" ]] ; then

    for N in "${NAMES}" ; do

      if fgrep "${N}" $F > /dev/null ; then

      ed - $F <<\EOF
	g/subinfo_init/s//subinfo_start/g
	g/locinfo_init/s//locinfo_start/g
	w
	q
EOF

      fi

    done

  fi

done


