TELNETD

You need to use the program 'makeit' to make this program.  This is
needed so that we can remove the stupid AST library path that may be
present in the LD_LIBRARY_PATH environment variable.

Synopsis:

$ makeit telnetd.x



