#!/bin/ksh
# TROFF-FILE

HERE=/home/dam/src/mansrc
F_DEBUG=0


if [ $F_DEBUG -ne 0 ] ; then
  exec 3> ${HERE}/troff-file.deb
fi


dprint() {
  if [ $F_DEBUG -ne 0 ] ; then
    echo $* >&3
  fi
}


dprint PWD=${PWD}
dprint pwd=$( pwd )

TYPE=
MP=

while getopts T:m: key ; do

  case $key in

  'T' )
    TYPE=${OPTARG}
    ;;

  'm' )
    MP=${OPTARG}
    ;;

  '?' )
    echo "${0}: unknown argument option" >&2
    exit 2
    ;;

  esac

done

dprint TYPE=${TYPE}
dprint MP=${MP}

shift $(( $OPTIND - 1 ))

dprint OPTIND=${OPTIND}

FILES="${*}"
dprint "FILES=>${FILES}<"

if [ -n "${FILES}" ] ; then

  (( c = 0 ))
  for F in $FILES ; do
    if [ $F == '-' ] ; then
      cat > file${c}.troff
    else
      cp $F file${c}.troff
    fi
    (( c += 1 ))
  done

else

  cat > file0.troff

fi



