From mach1!mach2!other Thu Apr 17 02:12 EDT 1997
>From mach1 Thu Apr 17 02:12 EDT 1997
>From mach1 Thu Apr 17 02:12 EDT 1997 remote from person
From mach1!mach2!other Thu Apr 17 02:12 EDT 1997 remote from person2!bad
from:    	PCS_administrator <hocpa!dam>
Path:mach1!mach2
subject:				  	
Return-Path: mach1!mach2
to:      	hocpa!dam,
	more,
	more1,
	more2
subject:	test email/posting 2
date:           02 Dec 93 12:26:33
subject:	 
	again
	
		more_subject
x-other:	bla, bla, bla !
subject:				  	

This is a test.  This is a test of the emergency email/posting
system.  This is only a test.  This test has been devised
as a means of testing email or bulletin board related operations.
If this had been an actual emergency, you would have been instructed
as to where to send email (for testing purposes !).
This concludes this test of the emergency email/posting system.

PCS Administrator

