From jskalko@lucent.com Tue May 27 07:08 EDT 1997
Return-Path: <jskalko@lucent.com>
Received: from nj7460exch001h.wins.lucent.com (nj7460exch001h.ho.lucent.com) by hocpa.ho.lucent.com (5.x/EMS-L sol2)
	id AA20510; Tue, 27 May 1997 07:07:54 -0400
Received: by nj7460exch001h.wins.lucent.com with SMTP (Microsoft Exchange Server Internet Mail Connector Version 4.0.994.63)
	id <01BC6A6C.56D67A00@nj7460exch001h.wins.lucent.com>; Tue, 27 May 1997 07:05:20 -0400
Message-Id: <c=US%a=_%p=Lucent%l=NJ7460EXCH002U-970527110456Z-374@nj7460exch001h.wins.lucent.com>
From: "Skalko, John  (John)" <jskalko@lucent.com>
To: WTPC Piscataway Users <wtpcpiscataway@holmdel.exchange.lucent.com>
Cc: "Boyce, David H (David)" <dhboyce@cp.lucent.com>,
        "Taylor, Elaine R (Elaine)" <etaylor@cp.lucent.com>,
        "Bikle, David  (David)" <dbikle@cp.lucent.com>,
        "Meier, Elizabeth V (Beth)" <bmeier@cp.lucent.com>,
        "Sidhu, Suzanne  (Suzanne)" <ssidhu@cp.lucent.com>,
        "Younkin, Janet  (Janet)" <jyounkin@cp.lucent.com>
Cc: "Sasvari, Jean A (Jean)" <jsasvari@cp.lucent.com>,
        "Brown, Frances  (Frances)" <fbrown@cp.lucent.com>
Subject: AT&T and SBC in merger talks - WSJ
Date: Tue, 27 May 1997 07:04:56 -0400
X-Mailer:  Microsoft Exchange Server Internet Mail Connector Version 4.0.994.63
Mime-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: text/plain; charset="us-ascii"

May 27, 1997

Folks:

The Wall Street Journal reports on merger talks between AT&T and SBC

John Skalko


DJ   05/27 0559  AT&T, SBC Holding Talks To Merge In $50B Deal

   By John J. Keller
   Staff Reporter of The Wall Street Journal

Telecom powerhouses AT&T Corp. and SBC Communications Corp. are holding
talks to join forces in a $50 billion-plus merger, which would easily
be the largest such transaction in history.

People close to the talks emphasized that numerous issues could block a
deal, including a federal ban on SBC entering the long-distance market
until its own local-phone market is open to competitors. Negotiators
also are struggling over the transaction's financial structure, the new
company's management, its name and base of operations.

Competitors and regulators are sure to take aim at any deal. Combined,
AT&T and SBC would have nearly $80 billion in annual revenue, 230,000
workers, more than 60% of the $80 billion U.S. long-distance market and
a virtual vise grip on local-phone and wireless services throughout the
Southwest and California. SBC provides local phone services in seven of
the 10 largest U.S. cities.

Public confirmation of the talks could come soon, as AT&T, the nation's
largest telecommunications carrier, and SBC, owner of the vast
Southwestern Bell and Pacific Telesis Group local-phone systems, draw
closer to a definitive merger pact, people close to the negotiations
said. Neither AT&T nor SBC would comment.

"The discussions have grown very serious in the last month," said one
person familiar with the talks. Others said New York-based AT&T has put
some business transactions on hold, given the material nature of the
current discussions.

One stunning possibility is that SBC's younger managers could end up
running the merged company, one executive said. AT&T Chairman Robert E.
Allen is nearing retirement, and the company's new president, John R.
Walter, has been with AT&T just seven months.

A merger between AT&T and SBC, which only recently paid $16.7 billion
for California-based Pacific Telesis, would be the first combination
between AT&T and a Bell since the landmark 1984 breakup of the old
American Telephone & Telegraph Co. That divestiture, which settled a
grueling federal antitrust suit, split long-distance carrier AT&T from
seven regional Bell phone companies.

"The Justice Department will take a long, hard look at this deal," said
one executive, "especially given that AT&T would seem to be putting
itself back together again at a time when new telecom laws are
attempting to open all markets and nurture smaller rivals."

could make it harder for smaller players to survive, especially
start-ups that have bet billions on everything from wireless licenses
to Internet-access services.  Telecommunications services have always
demanded scale and scope. Only the strongest providers can shoulder the
massive financial investments and huge work forces needed to maintain
big global networks.

Indeed, the AT&T-SBC talks underscore the scramble among the world's
telecom titans to join assets to satisfy business and consumer demands
for bundled communications services. British Telecommunications PLC is
about to complete its takeover of U.S. long-distance icon MCI
Communications Corp. Sprint Corp. is 20% owned by the national carriers
of France and Germany.

An AT&T-SBC combo would be twice as big as any other deal, dwarfing the
$27 billion merger between Sandoz Ltd. and Ciba-Geigy Ltd., which
formed drug-giant Novartis; the $25 billion leveraged buyout of RJR
Nabisco; and the planned $23 billion merger of Bell Atlantic Corp. and
Nynex Corp.

Based on the closing stock price Friday of $36.125 on the New York
Stock Exchange and its 1.62 billion shares, AT&T's market value is
nearly $59 billion.  SBC, which on Friday closed at $56.875 on the same
exchange, has a market value of just under $52 billion, with 912
million shares outstanding.

The transaction could take one of several forms. If AT&T is the
surviving entity, SBC shareholders would get a certain amount of AT&T
stock for each SBC share held; the reverse would occur if SBC is the
survivor. Under another scenario, the companies' respective
shareholders would get new stock in the new combined company.
Ultimately, executives said, the deal would likely be priced at the
stock-market values of the two companies when a deal is finally
struck.

To cover its bases, AT&T, while conducting its talks with SBC, has held
parallel discussions with Southeast giant BellSouth Corp. "SBC and
BellSouth are the two AT&T has been interested in," said one person
close to AT&T.  "BellSouth has a hellacious stronghold in the South,
but SBC is the one AT&T lusts after the most. It's also the one where
the talks are farthest along."

With SBC, AT&T gets access to the fast-growing Southwest market, the
executive said, and SBC "is a two-fer; you get two Bells for one,"
including PacTel's lucrative California and Nevada markets. BellSouth
has indicated in the past that it would prefer to go it alone.

AT&T has had other companies in its sights. It has been talking to
Cable & Wireless PLC for some time about a possible combination
overseas to attack the international market. The two are still talking.
AT&T has also looked hard at GTE Corp., but people close to both
companies said they haven't held talks to merge.

Final details of a combination with SBC are still being worked out and
are said to be complicated somewhat by AT&T's three-way breakup last
year, in which telecom equipment maker Lucent Technologies Inc. and
computer supplier NCR Corp.  were spun off.

Current federal accounting rules governing spinoffs preclude AT&T from
structuring any transaction on a "pooling-of-interests" basis until the
fourth quarter of 1998. Pooling allows a company to report higher
earnings after a merger than purchase accounting. AT&T may be able to
sidestep this problem since the merger would likely take as much as two
years to complete.

If completed, the unprecedented combination could spur more mergers as
executives race to position their companies for new competition. One
possibility: Bell Atlantic/Nynex may seek a major long-distance
connection, possibly with the nation's No. 3 carrier Sprint.

Each giant new player could eventually comprise a sort of global
high-tech Bell System where one company would provide all services and
charge a customer via a single itemized monthly bill. "You can't have
an island of assets; a Bell is just a local or regional carrier, while
a long-distance carrier has only intercity network assets," said one
expert familiar with the AT&T-SBC talks.  "Business customers want a
vendor that owns and controls networks end-to-end, especially when
sensitive data transmission is on the rise, along with Internet
services."

The biggest roadblocks to a merger are sure to be antitrust scrutiny
and resistance from competitors in long-distance and local services. As
a Bell company, SBC is prohibited from entering the long-distance
business until its local markets are deemed competitive. Just two weeks
ago the Justice Department recommended that the Federal Communications
Commission reject SBC's application to offer long-distance services in
Oklahoma where SBC has practically no competition in local services.

Neither AT&T nor SBC is viewed as particularly pro-competitive. AT&T
has stridently resisted most Bell moves into new businesses since its
1984 breakup, including any forays near its long-distance preserve. And
true to its Southwest origins, SBC has a gunslinger's reputation for
eliminating rivals in its territories, most prominently Texas.

In the current competitive environment, AT&T finds itself in a race to
join forces with other players, partly because it has been hurt in the
last couple of years by management missteps and unsuccessful
investments by its chairman Mr.  Allen. His recent three-way breakup
helped to better focus the company on its services business, but it
also caused AT&T to shed Bell Laboratories and its telecom equipment
and computer arms -- assets that gave AT&T its powerful mystique in an
era of commodity-type phone services.

SBC is suffering none of the problems of its former parent. Under its
chairman and chief executive, Edward E. Whitacre Jr., SBC has become
one of the best-run, most aggressive Bells. SBC has taken full
advantage of its massive base in the Southwest and one of the
fastest-growing, technically astute populations in the country to turn
its phone network into one of the industry's most profitable.

In 1996, SBC posted its fifth consecutive year of double-digit earnings
growth. Also, Mr. Whitacre, 56 years old, is viewed as an adroit
investor. SBC invested early in Mexico's Telefonos de Mexico. The
company has placed bets in at least eight countries, including Britain,
France and Switzerland, and it is leading a consortium to provide local
phone services in South Africa.

Local-phone companies such as SBC are expected to capture a giant share
of AT&T's long-distance business in the next few years as they simply
tune their ubiquitous local networks to carry voice and data traffic
over longer distances.  AT&T, more than any other long-distance player,
is acutely vulnerable to the Bell offensive. As much as 80% of AT&T's
90 million customers are residential consumers. They generate about 60%
of AT&T's $52 billion in annual revenue.  MCI's split, by contrast, is
almost the exact reverse, leaving MCI far less vulnerable to a
consumer-marketing war.

just a year has taken more than 6% of the available long-distance
customers in its territories -- more than 82% of these AT&T
subscribers. Southern New England Telecommunications Corp. has taken
more than 30% of the long-distance market in Connecticut, mostly from
AT&T.

for favorable financial terms that would allow it to resell local-phone
services to customers through already-connected Bell lines. It would be
a lot easier, not to mention more profitable, for AT&T to merge with a
Bell to get big in local services quickly.

The impact of an AT&T-SBC merger would have a ripple effect on
suppliers such as Lucent, Northern Telecom Ltd. and Telefon AB L.M.
Ericsson. AT&T and SBC have overlapping wireless strategies, for
example, leaving open the possibility that AT&T could cancel or shift
billions of dollars in investments in wireless licenses and equipment
orders. The combination could use SBC's wireless assets in many areas,
including Chicago, where AT&T recently obtained rights to a wireless
phone offering the industry calls "personal communications services."
AT&T plans to deploy a new wireless residential phone service in
Chicago, using the new licenses.

But under law an AT&T-SBC combined company would have to shed these
licenses or divest itself of SBC's cellular business there. SBC's
recent acquisition, PacTel, might also have to scratch its own
multibillion-dollar effort to build a PCS network in California since
AT&T already has extensive cellular systems there.

Management and personnel of the two companies would also undergo a
major reshuffling. In the past several years, AT&T has lost some of its
most seasoned managers. Mr. Allen's No. 2 and chief of operations,
Victor Pelson, quit around the time of AT&T's recent three-way split.
Alex J. Mandl, who preceded Mr.  Walter as president, left last summer
to run a wireless start-up. James Barksdale departed AT&T's wireless
unit a couple of years ago to head Internet pioneer Netscape
Communications Corp. Joseph Nacchio, AT&T's consumer chief, quit in
December to build a competitive fiber-optic network, Qwest
Communications Corp.

AT&T's president, Mr. Walter, joined the company only last November as
the designated successor to 62-year-old Mr. Allen after a widely
publicized search.  Plucked from printer R.R. Donnelley & Sons Co., Mr.
Walter, 50, quickly took charge as AT&T's new operations chief. He
toughened AT&T's cost controls, reassigned key executives to simplify
AT&T's planning and marketing, and took command of AT&T's botched
efforts to design a new billing system.

But Mr. Walter could take the No. 2 spot in the new company or find
himself out of the running altogether. SBC's Bell veterans, led by Mr.
Whitacre, are likely to take eventual command of the new company,
executives said. And Mr.  Allen, who accelerated his retirement by two
years to make room for Mr.  Walter, now may stay on at AT&T for the two
years it could take to complete a deal.

A merger would likely produce layoffs in various areas. AT&T, halfway
through an effort to cut 17,000 jobs, has erected a big local-phone
operation as it prepares to enter that market; some jobs there could be
deemed redundant.  Indeed, everything from human resources to network
engineering and marketing could be trimmed when combined with SBC's
force.

On the regulatory front, the government would be expected to scrutinize
how an AT&T-SBC deal might affect pricing for services and the
structure of rates everywhere. If PacTel cancels billions of dollars in
new networks, for example, how will businesses and consumers, who have
already contributed to the new construction, be compensated in
California?

Meanwhile, will the new combination have a further, major impact on the
restructuring of international rates? BT merged with MCI and promptly
cut pricing on phone calls between the U.S. and Britain to just 12
cents a minute.  Other players such as AT&T and Sprint were forced to
follow suit. If a price war breaks out, depleting profits, will
consumers of other services be billed at higher rates?

Because of the potential fallout from such a giant deal, the Justice
Department could impose onerous -- and possibly deal-breaking --
conditions on the merger. The agency could force AT&T and SBC to
structurally separate their local and long-distance businesses, making
the combination less efficient and less fearsome to competitors.

Under another scenario, AT&T could be barred from combining its
long-distance marketing with SBC's local services until rivals can set
up shop to compete.

"You know competitors are going to take full advantage of the
distraction of merging to try and steal customers," said one executive
familiar with the talks.

  (END) DOW JONES NEWS 05-27-97
   6 03 AM

