Return-Path: <micro_publicity-bounces@crhc.uiuc.edu>
Received: from orca.ele.uri.edu (131.128.51.63)
	by localhost with POP3 (fetchmail-6.2.5)
	for dam@localhost (single-drop); Wed, 23 Mar 2011 20:38:38 -0400 (EDT)
Received: from orca.ele.uri.edu ([unix socket])
	 by ele.uri.edu with LMTPA;
	 Mon, 21 Mar 2011 13:27:12 -0400
X-Sieve: CMU Sieve 2.3
Received: from mailman.csl.uiuc.edu (goose.csl.illinois.edu [130.126.136.143])
	by orca.ele.uri.edu (8.14.3/8.14.3) with ESMTP id p2LHR8kq029293;
	Mon, 21 Mar 2011 13:27:10 -0400
Received: from mailman.csl.uiuc.edu (localhost [127.0.0.1])
	by mailman.csl.uiuc.edu (Postfix) with ESMTP id 30B1B1000B47;
	Mon, 21 Mar 2011 12:26:52 -0500 (CDT)
X-Original-To: micro_publicity@mailman.csl.illinois.edu
Delivered-To: micro_publicity@mailman.csl.illinois.edu
Received: from usps.crhc.uiuc.edu (usps2.crhc.illinois.edu [130.126.143.231])
	by mailman.csl.uiuc.edu (Postfix) with ESMTP id 6511F1000B3F
	for <micro_publicity@mailman.csl.illinois.edu>;
	Mon, 21 Mar 2011 01:22:37 -0500 (CDT)
Received: from usps.crhc.uiuc.edu (localhost [127.0.0.1])
	by usps.crhc.uiuc.edu (Postfix) with ESMTP id 4B5B13400092
	for <micro_publicity@crhc.uiuc.edu>;
	Mon, 21 Mar 2011 01:22:37 -0500 (CDT)
Received: by usps.crhc.uiuc.edu (Postfix, from userid 65534)
	id 35B8B3400095; Mon, 21 Mar 2011 01:22:36 -0500 (CDT)
X-Spam-Checker-Version: SpamAssassin 3.2.5 (2008-06-10) on usps2.crhc.uiuc.edu
X-Spam-Level: 
X-Spam-Status: No, score=-2.5 required=5.0 tests=AWL,BAYES_00,
	SUBJECT_NEEDS_ENCODING autolearn=disabled version=3.2.5
Received: from york-pps.york.cuny.edu (pps.york.cuny.edu [198.61.16.43])
	(using TLSv1 with cipher DHE-RSA-AES256-SHA (256/256 bits))
	(No client certificate requested)
	by usps.crhc.uiuc.edu (Postfix) with ESMTPS id 83C143400092
	for <micro_publicity@crhc.uiuc.edu>;
	Mon, 21 Mar 2011 01:22:28 -0500 (CDT)
Received: from www4.york.cuny.edu (www4.york.cuny.edu [198.61.27.188])
	by york-pps (8.14.4/8.14.4) with ESMTP id p2L60PSE011300
	for <micro_publicity@crhc.uiuc.edu>; Mon, 21 Mar 2011 02:00:25 -0400
Received: by www4.york.cuny.edu (Postfix, from userid 99)
	id 361B3BFDD58; Mon, 21 Mar 2011 02:00:25 -0400 (EDT)
From: "Extended Deadline to March 31st - Call for Papers - 3rd Cellular Automata\, Theory and Applications Workshop (CA-CSCX11) - July 18-21\, 2011" <ldalotto@york.cuny.edu>
To: micro_publicity@crhc.uiuc.edu
X-Priority: 3
List: louslist
List-Owner: <ldalotto@york.cuny.edu>
List-URL: <http://faculty.york.cuny.edu/cgi-bin/dada/mail.cgi/list/louslist/>
Message-ID: <20110321012346.33199664@york.cuny.edu>
X-Mailer: Pro Dada 2.10.12 
Content-Disposition: inline
MIME-Version: 1.0
Subject: Extended Deadline to March 31st - Call for Papers - 3rd Cellular Automata, Theory and Applications Workshop (CA-CSCX11) - July 18-21, 2011 Message
Date: Mon, 21 Mar 2011 02:00:25 -0400 (EDT)
X-Virus-Scanned: ClamAV using ClamSMTP
X-Mailman-Approved-At: Mon, 21 Mar 2011 12:26:50 -0500
X-BeenThere: micro_publicity@crhc.uiuc.edu
X-Mailman-Version: 2.1.11
Precedence: list
Reply-To: "Extended Deadline to March 31st - Call for Papers - 3rd Cellular Automata, Theory and Applications Workshop \(CA-CSCX11\) - July 18-21, 2011" <ldalotto@york.cuny.edu>
List-Id: <micro_publicity.crhc.uiuc.edu>
List-Unsubscribe: <http://mailman.crhc.uiuc.edu/mailman/options/micro_publicity>, 
	<mailto:micro_publicity-request@crhc.uiuc.edu?subject=unsubscribe>
List-Post: <mailto:micro_publicity@crhc.uiuc.edu>
List-Help: <mailto:micro_publicity-request@crhc.uiuc.edu?subject=help>
List-Subscribe: <http://mailman.crhc.uiuc.edu/mailman/listinfo/micro_publicity>,
	<mailto:micro_publicity-request@crhc.uiuc.edu?subject=subscribe>
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable
Sender: micro_publicity-bounces@crhc.uiuc.edu
Errors-To: micro_publicity-bounces@crhc.uiuc.edu
X-Spam-Score: 1.277
X-Spam-Report: SUBJECT_NEEDS_ENCODING
X-Greylist: excluded
X-Scanned-By: MIMEDefang 2.64 on 131.128.51.63

(Mailing list information, including unsubscription instructions, =

is located at the end of this message.)
__ =


Apologies for multiple and cross posting
 =

************************************************************************
Call for Papers (Deadline Extended)
3rd Cellular Automata, Theory and Applications Workshop (CA-CSC=9211)
within The 2011 International Conference on Scientific Computing (CSC'11)
 =

July 18-21, 2011, Las Vegas, USA
 =

DEADLINE EXTENDED To March 31st, 2011
************************************************************************
 =

 =

Dear Professionals and Research Students working in areas involving Cellula=
r Automata from both theory and application fields, we are inviting you to =
join us for our:
3rd Cellular Automata, Theory and Applications Workshop within The 2011 Int=
ernational Conference on Scientific Computing (CSC'11: July 18-21, 2011, Mo=
nte Carlo Resort, Las Vegas, USA),
one of 22 conferences at WORLDCOMP'11 - The 2011 World Congress in Computer=
 Science, Computer Engineering, and Applied Computing.
 =

Chairs of Session: Lou D'Alotto*, J.F. Nystrom**, William Spataro***
 =

* York College/CUNY, New York, USA, dalotto@york.cuny.edu
**Ferris State University, Michigan, USA, JamesNystrom@ferris.edu
***University of Calabria, Italy, spataro@unical.it
 =

Deadline for the full paper submission is March 31st, 2011.
 =

Official CFP
Cellular Automata, a computational paradigm of Scientific Computing, are pa=
rallel computing models and discrete dynamical systems, utilized for modeli=
ng and simulating complex systems whose evolution can be described in terms=
 of local interactions. Following the success of our first two Cellular Aut=
omata, Theory and Applications Workshop (in 2009 and 2010), which included =
exciting keynotes addressed from a leading Cellular Automata researcher, Pr=
of. Dr. Peter Sloot, and by Prof. Yaroslav D. Sergeyev, father of the Infin=
ity Computer, we are glad to invite you to our third edition.
 =

The main objective of this Workshop, organized within the 2011 World Congre=
ss in Computer Science, Computer Engineering, and Applied Computing (WORLDC=
OMP'11), is to offer scientists, researchers and engineers an opportunity t=
o express and confront their views on trends, challenges, and state-of-the =
art in both theory and diverse application fields such as engineering, phys=
ics, chemistry, biology, geology, medicine, ecology, sociology, traffic con=
trol, economy, etc.
 =

Distinguished papers will have the opportunity to be published in a special=
 issue of the Journal of SuperComputing, a leading ISI research journal pub=
lishing theoretical, practical, tutorial and survey papers on all aspects o=
f supercomputing.
 =

Please see other publication details below.
 =

SCOPE:
Topics of applied interest include, but are not limited to:
- cellular automata as models of parallelism,
- cellular automata as complex systems,
- cellular automata as dynamical systems,
- cellular automata models for real phenomena,
- cellular automata models based on geometrical forms,
- cellular automata in system biology,
- cellular automata in natural computing,
- theoretical issues on cellular automata (algebraic properties, etc)
- parallel implementations of cellular automata models
 =

SUBMISSION:
Prospective authors are invited to submit their draft papers directly to th=
e Workshop Chairs (see emails above). Please include =93CA =96 CSC=9211=94 =
in the email subject header. Submissions must be received by March 31st, 20=
11 and they must be in either MS doc (not docx) or pdf formats (about 5 to =
7 pages - single space, font size of 10 to 12). All reasonable typesetting =
formats are acceptable (later, the authors of accepted papers will be asked=
 to follow a particular typesetting format to prepare their papers for publ=
ication.) The length of the Camera-Ready papers (if accepted) will be limit=
ed to 7 (IEEE style) pages. Papers must not have been previously published =
or currently submitted for publication elsewhere. The first page of the dra=
ft paper should include: title of the paper, name, affiliation, postal addr=
ess, and email address for each author. The first page should also identify=
 the name of the Contact Author and a maximum of 5 topical keywords that wo=
uld best represent the =



content of the paper. Finally, the name of the conference (CSC'11) must be =
stated on the first page.
 =

IMPORTANT DATES:
March 31, 2011: Submission of papers (about 5 to 7 pages)
April 20, 2011:  Notification of acceptance
May 7, 2011:  Final papers + Copyright + Registration
July 18-21, 2011: The 2011 World Congress in Computer Science, Computer Eng=
ineering, and Applied Computing (WORLDCOMP'11 - 22 joint conferences)
 =

CATEGORIES OF ACCEPTED PAPERS:
(RRP)  Regular Research Papers: 7-page IEEE-style publication in the procee=
dings. 20-minute formal presentation slot.
(RRR)  Regular Research Reports: 7-page IEEE-style publication in the proce=
edings. Presentation in an informal setting (during Discussion Sessions.) T=
ypically, those authors with language difficulties prefer this mode of pres=
entation.
(SRP)  Short Research Papers: 4-page IEEE-style publication in the proceedi=
ngs. Presentation in an informal setting (during Discussion Sessions.)  Sam=
e presentation mode as RRR papers.
(PST)   Posters 1-page IEEE-style publication in the proceedings. Presentat=
ion in an informal setting (during Discussion Sessions.
 =

PUBLICATION:
All accepted papers will be published in the general CSC conference proceed=
ings (in both, printed book form as well as online). The proceedings will b=
e indexed in Inspec / IET /The Institute for Engineering and Technology, DB=
LP / Computer  Science Bibliography, and others.) The printed proceedings w=
ill be available for distribution on site at the conference.
 =

MORE:
The 3rd Cellular Automata, Theory and Applications Workshop, together with =
all other WORLDCOMP Workshops and Conferences, will be held at Monte Carlo =
Resort, Las Vegas, Nevada, USA (with any overflows at other near-by hotels)=
. This is a mega hotel with excellent conference facilities and over 3,000 =
rooms. It is minutes from the airport with 24-hour shuttle service to and f=
rom the airport. This hotel has many recreational attractions, including: w=
aterfalls, spa, pools, sunning decks, Easy River, wave pool, nightly shows,=
 many restaurants, etc. The negotiated room rate for conference attendees i=
s very reasonable.
More information about the general CSC 2011 conference and the WorldComp=92=
11 congress can be found at the conference website:
 =

http://www.world-academy-of-science.org/worldcomp11/ws/conferences/csc11
 =

We are looking forward to welcoming you in Las Vegas!
Lou D'Alotto, J.F. (Jim) Nystrom, and William Spataro, Co-chairs
 =



-- =

The following information is a reminder of your current mailing
list subscription: =


You are subscribed to the following list: =

	Extended Deadline to March 31st - Call for Papers - 3rd Cellular Automata,=
 Theory and Applications Workshop (CA-CSC=9211) - July 18-21, 2011
	=

using the following email:
	micro_publicity@crhc.uiuc.edu

You may automatically unsubscribe from this list at any time by =

visiting the following URL:

<http://faculty.york.cuny.edu/cgi-bin/dada/mail.cgi/u/louslist/>

If the above URL is inoperable, make sure that you have copied the =

entire address. Some mail readers will wrap a long URL and thus break
this automatic unsubscribe mechanism. =


You may also change your subscription by visiting this list's main screen: =


<http://faculty.york.cuny.edu/cgi-bin/dada/mail.cgi/list/louslist>

If you're still having trouble, please contact the list owner at: =


	<mailto:ldalotto@york.cuny.edu>

The following physical address is associated with this mailing list: =


Lou D'Alotto
Department of Math and Computer Science
York College/City University of New York
ldalotto@york.cuny.edu
_______________________________________________
micro_publicity mailing list
micro_publicity@crhc.uiuc.edu
http://mailman.crhc.uiuc.edu/mailman/listinfo/micro_publicity
