From dmorano@gateway.ece.neu.edu Fri Mar  4 21:26:20 EST 2011 -0500
Return-Path: <dmorano@gateway.ece.neu.edu>
X-Original-To: dam@rightcore.com
Delivered-To: dam@rightcore.com
Received: from gateway.ece.neu.edu (gateway.ece.neu.edu [129.10.60.71])
	by mail.rightcore.com (RCMAILER) with ESMTP id D1E5D2342A
	for <dam@rightcore.com>; Fri,  4 Mar 2011 21:26:19 -0500 (EST)
Received: from gateway.ece.neu.edu (localhost [127.0.0.1])
	by gateway.ece.neu.edu (8.13.8+Sun/8.13.8) with ESMTP id p252PIwD008109
	for <dam@rightcore.com>; Fri, 4 Mar 2011 21:25:18 -0500 (EST)
Received: (from dmorano@localhost)
	by gateway.ece.neu.edu (8.13.8+Sun/8.13.8/Submit) id p252PIfR008108
	for dam@rightcore.com; Fri, 4 Mar 2011 21:25:18 -0500 (EST)
Date: Fri, 4 Mar 2011 21:25:18 -0500 (EST)
Message-Id: <201103050225.p252PIfR008108@gateway.ece.neu.edu>
content-type: text/plain ; charset=iso-8859-1
content-transfer-encoding: 8bit
organization: New Century Bibles
from: (David Morano) dmorano@gateway.ece.neu.edu
x-sender: dam@rightcore.com
x-to: coldspacemachine@gmail.com
to: pcs@rightcore.com
x-cc: guest
x-bcc: pcs
Subject: try this!
X-Bogosity: Unsure, tests=bogofilter, spamicity=0.520000, version=1.1.5


Hello, my name is Hérnädéz!


