From rca!dam Wed Jan 01 16:04:19 USEST 2014 -0500
received: from incoming.verizon.net (206.46.232.10)
 by localhost with POP3 (fetchmail-6.2.5)
 for dam@localhost (single-drop); Thu, 08 Apr 2010 03:22:27 -0400 (EDT)
from: dam@rightcore.com (David A. Morano)
TO: dam (this is an EMA-comment) 
bcc: pcs (this is another EMA-comment)
errors-to: pcs (Personal Communication Services)
article-id: rca86576576
subject: test10
content-type:  (Wilt)
	(the) text/plain ; (stilt)
	(cham) charset=iso-8859-1 (berlin)
content-transfer-encoding:	(the place) 7bit (jack)

to: dam
