From acm.org!SRS0=ca1bc58c3f5b2dae898787683dcb4e92061e8392=239=gmail.com=eve.s.silver Fri Nov 27 10:40:19 EST 2009 -0500
return-path: 
 
 <SRS0=ca1bc58c3f5b2dae898787683dcb4e92061e8392=239=gmail.com=eve.s.silver@acm.org>
received: from acm26-4.acm.org (acm26-4.acm.org [199.222.69.109])
 by mail.rightcore.com (RCMAILER) with ESMTP id 9C29B2342A
 for <dam@rightcore.com>; Fri, 27 Nov 2009 10:40:19 -0500 (EST)
received: from psmtp.com ([74.125.149.99])
 by acm26-4.acm.org (ACM Email Forwarding Service) with SMTP id IAP48419
 for <morano@acm.org>; Fri, 27 Nov 2009 10:40:19 -0500
received: from source ([209.85.216.197]) by na3sys009amx173.postini.com ([74.125.148.10]) with SMTP;
 Fri, 27 Nov 2009 10:40:19 EST
received: by pxi35 with SMTP id 35so1070105pxi.18
 for <morano@acm.org>; Fri, 27 Nov 2009 07:40:18 -0800 (PST)
received: by 10.142.3.37 with SMTP id 37mr112301wfc.146.1259336416076; Fri, 27
 Nov 2009 07:40:16 -0800 (PST)
content-length: 77                  
content-lines: 3                   
x-message-id: <7e693b330911270739h3b9bbae6h218e6935b72f8e69@mail.gmail.com>
x-original-to: dam@rightcore.com
delivered-to: dam@rightcore.com
dkim-signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
 d=gmail.com; s=gamma;
 h=domainkey-signature:mime-version:sender:received:from:date
 :x-google-sender-auth:message-id:subject:to:content-type;
 bh=8Ob5TPkx6AnhexioFY1XNsQhPcrq4b5FNIjDUycl4Fs=;
 b=HIM5urOEp13gbTXiEVDMJ06rfB8dhrVo1a4S09QlW+TqS1eb9J5M6B5h36rYo50XGk
 BBzCMfr7gFH0yuMwJ5lv9S7NcO4xCVlu9wA0VKG4wwA4dekOn/blKfExi0jFiklCD8Gq
 pB7caMF38yNo93PPBmABJLjCuV16OOcvPDy+A=
domainkey-signature: a=rsa-sha1; c=nofws;
 d=gmail.com; s=gamma;
 h=mime-version:sender:from:date:x-google-sender-auth:message-id
 :subject:to:content-type;
 b=qbk5LtDnGbQuW4ttBc6GrFcTjkaLTPshvJpGk3WJLqijHaYWCQh25HoLNEZcjwMQbZ
 7uJZ8/bLse7D1b7KGgsWQHCssaGhOhEzzVVzaBv9dB2viW3c8EuOFcvvCrGD9vTBBSc+
 f3MgGHeFuzmLHSXeEe9+ucmL18DbnGvy2EQ3Q=
mime-version: 1.0
sender: eve.s.silver@gmail.com
x-google-sender-auth: 41b1648b85d5bf1f
content-type: text/plain; charset=UTF-8
x-pstn-neptune: 0/0/0.00/0
x-pstn-levels: (S:68.59706/99.90000 CV:99.9000 FC:95.5390 LC:95.5390 R:95.9108 P:95.9108 M:97.0282 C:98.6951 )
x-pstn-settings: 3 (1.0000:1.0000) s cv gt3 gt2 gt1
x-pstn-addresses: from <eve@evesilver.com> forward (user good) [3093/153]
status: 
From: Eve Silver <eve@evesilver.com>
To: Dave Morano <morano@ieee.org>,
 David Morano <coldspacemachine@gmail.com>, David Morano <morano@acm.org>,
 David Morano <morano@computer.org>
Date: Fri, 27 Nov 2009 09:39:56 -0600
Subject: Chad and Li are doing great! :)

I am floored at how well they are doing. Can't wait to talk to you ! :)

Eve
