From morano Tue Oct 25 14:08:42 EDT 2005 -0400
return-path: <zerotheigenvector@yahoo.com>
received: from orca.ele.uri.edu
	by localhost with POP3 (fetchmail-6.2.5)
	for morano@localhost (single-drop); Tue, 25 Oct 2005 14:08:42 -0400 (EDT)
received:  from leviathan.ele.uri.edu (leviathan [131.128.51.64])
	by ele.uri.edu (Cyrus v2.2.3) with LMTP; Tue, 25 Oct 2005 14:08:06 -0400
received:  from cs-ems3.ieee.org (cs-ems3.ieee.org [140.98.193.209])
	by leviathan.ele.uri.edu (8.12.9/8.12.9) with ESMTP id j9PI7x4r027357
	for <morano@ele.uri.edu>; Tue, 25 Oct 2005 14:08:00 -0400 (EDT)
received:  from gemini4.ieee.org (gemini4.ieee.org [140.98.193.189])
	by cs-ems3.ieee.org (8.12.11/8.12.11) with ESMTP id j9PI7nOV016416
	for <morano@computer.org>; Tue, 25 Oct 2005 14:07:49 -0400
received:  from hormel7.ieee.org (hormel7.ieee.org [140.98.193.230])
	by gemini4.ieee.org (Postfix) with ESMTP id 81D0727E1A
	for <morano@computer.org>; Tue, 25 Oct 2005 14:06:51 -0400 (EDT)
received:  from web53015.mail.yahoo.com (web53015.mail.yahoo.com [206.190.49.45])
	by hormel7.ieee.org (8.12.10+Sun/8.12.10) with SMTP id j9PI7mux017828
	for <morano@computer.org>; Tue, 25 Oct 2005 14:07:48 -0400 (EDT)
received:  (qmail 99281 invoked by uid 60001); 25 Oct 2005 18:07:58 -0000
received:  from [204.8.197.135] by web53015.mail.yahoo.com via HTTP; Tue, 25 Oct 2005 11:07:58 PDT
x-message-id: <20051025180758.99279.qmail@web53015.mail.yahoo.com>
X-Sieve: CMU Sieve 2.2
DomainKey-Signature: a=rsa-sha1; q=dns; c=nofws;
	s=s1024; d=yahoo.com;
	h=Message-ID:Received:Date:From:Reply-To:Subject:To:MIME-Version:Content-Type:Content-Transfer-Enc oding;
	b=Adf/wx6lVUMOT/8Rc7HFc/yl2DnstpqvtxakgNIYcmnTVJtimOPdlUTi5vg+uspvzjKZ2td6MoIuZeBPCexms0EZfI7MtIdZ +aVleEealL0w/+7yBAAAGZrbOR94VSlGqui4Z1a+X62U76TSz4d1gb4nzAhXAP40LnbsE+vyGrk=  ;
Reply-To: eve@evesilver.com
MIME-Version: 1.0
Content-Type: text/plain; charset=iso-8859-1
Content-Transfer-Encoding: 8bit
X-UCE-Filter-Settings: morano@computer_society redirected to 90_OPT_OUT
X-Spam-Score: undef - spam-scanning disabled
X-Scanned-By: IEEE UCE Filtering Service (uce . ieee . org) on 140.98.193.230
X-Spam-Status: NO ; VERY LOW ; 0.40
X-Spam-Report: 0.40 hits
	0.4 DNS_FROM_RFC_ABUSE     RBL: Envelope sender in abuse.rfc-ignorant.org
From: Eve Silver <zerotheigenvector@yahoo.com>
To: "David A. D. Morano" <morano@computer.org>
Date: Tue, 25 Oct 2005 11:07:58 -0700 (PDT)
Subject: Got mail Thanks anyway! :)


Just a slow day I guesS!!!

Eve
