#!/usr/bin/ksh
# OURPING


RF_DEBUG=0

echo "machine $1 is \c"

if [[ ${RF_DEBUG} -ne 0 ]] ; then

C=0
while [[ $C -lt 100 ]] ; do 
  sleep 1 ; 
  echo "jjjjkkkkkkkkkkkkkkjjjjjjjjjjjjjjjjjjjjjjjjjja\c" 
  C=`expr $C + 1 ` 
done

fi

echo "ok"

sleep 500
echo "alive\c"


