From gmail.com!a01.morano+caf_=a01.morano=rightcore.com Sun Oct 30 09:01:59 EDT 2016 -0400
return-path:  <a01.morano+caf_=a01.morano=rightcore.com@gmail.com>
received: from mail-oi0-f50.google.com (mail-oi0-f50.google.com 
	[209.85.218.50])
 by mail.rightcore.com (RCMAILER) with ESMTP id 03E632EF45
 for <a01.morano@rightcore.com>; Sun, 30 Oct 2016 09:01:57 -0400 (EDT)
received: by mail-oi0-f50.google.com with SMTP id v84so16864583oie.3
 for <a01.morano@rightcore.com>; Sun, 30 Oct 2016 06:01:58 -0700 (PDT)
received: by 10.202.196.71 with SMTP id u68csp2017917oif;
 Sun, 30 Oct 2016 06:01:56 -0700 (PDT)
received: from mail207.atl21.rsgsv.net (mail207.atl21.rsgsv.net. 
	[205.201.133.207])
 by mx.google.com with ESMTPS id y62si8400647yba.259.2016.10.30.06.01.56
 for <a01.morano@gmail.com>
 (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
 Sun, 30 Oct 2016 06:01:56 -0700 (PDT)
received: from (127.0.0.1) by mail207.atl21.rsgsv.net id h2nnk81lgi4t for 
	<a01.morano@gmail.com>; Sun, 30 Oct 2016 13:01:54 +0000 
	(envelope-from 
	<bounce-mc.us3_22750259.1035509-a01.morano=gmail.com@mail207.atl21.rsgsv.net>)
content-length: 58493               
x-original-to: a01.morano@rightcore.com
delivered-to: a01.morano@rightcore.com
delivered-to: a01.morano@gmail.com
x-google-dkim-signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
 d=1e100.net; s=20130820;
 h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature
 :subject:from:reply-to:to:date:message-id:list-id:list-unsubscribe
 :sender:mime-version;
 bh=SlkixT8dqbj4TxBPFP7hl5RUrT0JaFUFaYmKs9pns5k=;
 b=GYWcKMzXnv/OEiMsvD3JRr5t+RqSR418Xa3Ty2+EPkOQJPC7dwXFXBVvhSAuazRxqM
 lQizzRVUDkDzWhkrRxw2iWOCZKsPNg2CWrDwPAU9ofFvKVS39IUKScwWWijcgqfD8BrC
 SOQNOVCQn51eiGstRIWhEyB7wtQvCpkxGt874kbOF+qOXLZImS5lxNu0IS+Rjz2tVEuH
 iCuzUswzn9UKZVEJyzMmf4qGsSohysyvhnPUoPu7F/tVDuMRDX1mBvO7rQKzrPRgNJUQ
 s1nocunR04aqAbl2+WybufwJlxxFplYR0aOkE1+dCctbCQKT75FYrvkBk91N+Xx7uOF5
 u9EA==
x-gm-message-state: 
	ABUngvcB9+vuiSXFDSD88jdKCOiYZ+2WE4qGhZCCT6ivXRVjCHeKekY7/XMXV7u5IjS7o3lRGQxz0T9CJQZrhAqPmPBCDMo=
x-received: by 10.157.29.240 with SMTP id w45mr3942938otw.132.1477832517305;
 Sun, 30 Oct 2016 06:01:57 -0700 (PDT)
x-received: by 10.129.78.71 with SMTP id c68mr13553956ywb.21.1477832516542;
 Sun, 30 Oct 2016 06:01:56 -0700 (PDT)
x-forwarded-to: a01.morano@rightcore.com
x-forwarded-for: a01.morano@gmail.com a01.morano@rightcore.com
received-spf: pass (google.com: domain of 
	bounce-mc.us3_22750259.1035509-a01.morano=gmail.com@mail207.atl21.rsgsv.net
	designates 205.201.133.207 as permitted sender) 
	client-ip=205.201.133.207;
authentication-results: mx.google.com;
 dkim=pass header.i=@mail207.atl21.rsgsv.net;
 dkim=pass header.i=@gmail.mcsv.net;
 spf=pass (google.com: domain of 
	bounce-mc.us3_22750259.1035509-a01.morano=gmail.com@mail207.atl21.rsgsv.net
	designates 205.201.133.207 as permitted sender) 
	smtp.mailfrom=bounce-mc.us3_22750259.1035509-a01.morano=gmail.com@mail207.atl21.rsgsv.net
dkim-signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=k1; 
	d=mail207.atl21.rsgsv.net;
 h=Subject:From:Reply-To:To:Date:Message-ID:List-ID:List-Unsubscribe:Sender:Content-Type:MIME-Version;
	i=William=3DRightSideNews.com@mail207.atl21.rsgsv.net;
 bh=5bd9/+IbsxpALj6ltj0KMAFyW8o=;
 b=t04OyUzJGu/Axf3X8UgILqYAJ5A4Ce7RspgUVOw2UC85U9/x+vTvbB+z/5vo3JUPq4kV5I95hwGM
 YabCVdDgSX/NcO+M1dCUD18AQAscTpMO/RAnSN6O4Et7RVBbCj97BLoIFPXhgEYutq25gRrs9Gh1
 dFOu67sPd/49DGnyWjM=
dkim-signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=k1; d=gmail.mcsv.net;
 h=Subject:From:Reply-To:To:Date:Message-ID:X-Feedback-ID:List-ID:List-Unsubscribe:Sender:Content-Type:MIME-Version;
 bh=5bd9/+IbsxpALj6ltj0KMAFyW8o=;
 b=TPzkyzufpnaGAppQVqFgIw2hEIvLpLkbTAnncHm0o27ylJKOEtW5wDmmF+CaOBcH7VTBR54L/TV0
 SnbRkB5q9zr3yDSnB5fjvl7oR3LVEP5t+2yw5vmvIZ2q9RzbfB9u1Il5omPvGYR8z0W2W+cbKF/r
 b4QMpjO1kMvE1lPPAQk=
reply-to: =?utf-8?Q?Right=20Side=20News?= <William@RightSideNews.com>
x-mailer: MailChimp Mailer - **CIDd530a6546a84cf9d0f56**
x-campaign: mailchimp16fae18c4307c7f4c291009ac.d530a6546a
x-campaignid: mailchimp16fae18c4307c7f4c291009ac.d530a6546a
x-report-abuse: Please report abuse for this campaign here: 
	http://www.mailchimp.com/abuse/abuse.phtml?u=16fae18c4307c7f4c291009ac&id=d530a6546a&e=84cf9d0f56
x-mc-user: 16fae18c4307c7f4c291009ac
x-feedback-id: 22750259:22750259.1035509:us3:mc
list-id: 16fae18c4307c7f4c291009acmc list 
	<16fae18c4307c7f4c291009ac.215809.list-id.mcsv.net>
x-accounttype: pd
list-unsubscribe: 
	<mailto:unsubscribe-mc.us3_16fae18c4307c7f4c291009ac.d530a6546a-84cf9d0f56@mailin1.us2.mcsv.net?subject=unsubscribe>,
	<http://rightsidenews.us3.list-manage2.com/unsubscribe?u=16fae18c4307c7f4c291009ac&id=12c31c183e&e=84cf9d0f56&c=d530a6546a>
sender: "Right Side News" 
	<William=RightSideNews.com@mail207.atl21.rsgsv.net>
x-mcda: FALSE
content-type: multipart/alternative; 
	boundary="_----------=_MCPart_1387133383"
mime-version: 1.0
x-bogosity: Unsure, tests=bogofilter, spamicity=0.500000, version=1.1.5
status:           
From:  =?utf-8?Q?Right=20Side=20News?= <William@RightSideNews.com>
To:  =?utf-8?Q?David?= <a01.morano@gmail.com>
Date: Sun, 30 Oct 2016 13:01:54 +0000
Subject: 
	=?utf-8?Q?Posts= 2 0from=20Right=20Side=20News=20for=2010=2F30= 2F2016?=

This is a multi-part message in MIME format

--_----------=_MCPart_1387133383
Content-Type: text/plain; charset="utf-8"; format="fixed"
Content-Transfer-Encoding: quoted-printable

Daily Updates from Right Side News

View this email in your browser (http://us3.campaign-archive1.com/?u=3D16f=
ae18c4307c7f4c291009ac&id=3Dd530a6546a&e=3D84cf9d0f56)

Updates from


** Right Side News
------------------------------------------------------------



** Vets=C2=A0Demand=C2=A0Hillary=C2=A0Clinton=C2=A0Cut=C2=A0Ties=C2=A0 wit=
h=C2=A0Abedin=2C=C2=A0Mills=C2=A0and=C2=A0Samuelson=C2=A0 (http://www.righ=
tsidenews.com/editorial/us-opinion-and-editorial/vets-demand-hillary-clint=
on-cut-ties-abedin-mills-samuelson/)
------------------------------------------------------------
Posted on Oct 29=2C 2016 01:07 pm
Read in browser =C2=BB (http://www.rightsidenews.com/editorial/us-opinion-=
and-editorial/vets-demand-hillary-clinton-cut-ties-abedin-mills-samuelson/=
)
http://twitter.com/share?url=3Dhttp%3A%2F%2Fwww.rightsidenews.com%2Feditor=
ial%2Fus-opinion-and-editorial%2Fvets-demand-hillary-clinton-cut-ties-abed=
in-mills-samuelson%2F&text=3DVets%C2%A0Demand%C2%A0Hillary%C2%A0Clinton%C2=
%A0Cut%C2%A0Ties%C2%A0+with%C2%A0Abedin%2C%C2%A0Mills%C2%A0and%C2%A0Samuel=
son%C2%A0&count=3Dnone http://us3.campaign-archive1.com/?u=3D16fae18c4307c=
7f4c291009ac&id=3Dd530a6546a&fblike=3Dfblike-94c8793d&e=3D[UNIQID]&social=
proxy=3Dhttp%3A%2F%2Fus3.campaign-archive1.com%2Fsocial-proxy%2Ffacebook-l=
ike%3Fu%3D16fae18c4307c7f4c291009ac%26id%3Dd530a6546a%26url%3Dhttp%253A%25=
2F%252Fwww.rightsidenews.com%252Feditorial%252Fus-opinion-and-editorial%25=
2Fvets-demand-hillary-clinton-cut-ties-abedin-mills-samuelson%252F%26title=
%3DVets%25C2%25A0Demand%25C2%25A0Hillary%25C2%25A0Clinton%25C2%25A0Cut%25C=
2%25A0Tie...




** FBI Found =E2=80=9CTens Of Thousands Of Emails=E2=80=9D Belonging To Hu=
ma Abedin On Weiner=E2=80=99s Laptop (http://www.rightsidenews.com/editori=
al/us-opinion-and-editorial/fbi-found-tens-thousands-emails-belonging-huma=
-abedin-weiners-laptop/)
------------------------------------------------------------
Posted on Oct 29=2C 2016 11:41 am
Read in browser =C2=BB (http://www.rightsidenews.com/editorial/us-opinion-=
and-editorial/fbi-found-tens-thousands-emails-belonging-huma-abedin-weiner=
s-laptop/)
http://twitter.com/share?url=3Dhttp%3A%2F%2Fwww.rightsidenews.com%2Feditor=
ial%2Fus-opinion-and-editorial%2Ffbi-found-tens-thousands-emails-belonging=
-huma-abedin-weiners-laptop%2F&text=3DFBI+Found+%E2%80%9CTens+Of+Thousands=
+Of+Emails%E2%80%9D+Belonging+To+Huma+Abedin+On+Weiner%E2%80%99s+Laptop&co=
unt=3Dnone http://us3.campaign-archive2.com/?u=3D16fae18c4307c7f4c291009ac=
&id=3Dd530a6546a&fblike=3Dfblike-9327ff71&e=3D[UNIQID]&socialproxy=3Dhttp=
%3A%2F%2Fus3.campaign-archive1.com%2Fsocial-proxy%2Ffacebook-like%3Fu%3D16=
fae18c4307c7f4c291009ac%26id%3Dd530a6546a%26url%3Dhttp%253A%252F%252Fwww.r=
ightsidenews.com%252Feditorial%252Fus-opinion-and-editorial%252Ffbi-found-=
tens-thousands-emails-belonging-huma-abedin-weiners-laptop%252F%26title%3D=
FBI%2520Found%2520%25E2%2580%259CTens%2520Of%2520Thousands%2520Of%2520Emai=
ls...




** Recent Articles:
------------------------------------------------------------
** Federal Outlaws Brutally Attack Bundy Defense Attorney Marcus Mumford (=
http://www.rightsidenews.com/editorial/us-opinion-and-editorial/federal-ou=
tlaws-brutally-attack-bundy-defense-attorney-marcus-mumford/)
** Americans Want Hillary in Jail =E2=80=93 Rightly So! (http://www.rights=
idenews.com/life-and-science/culture-wars/americans-want-hillary-jail-righ=
tly/)
** More Islamist Money Flows to Hillary Clinton (http://www.rightsidenews.=
com/us/islam-in-america/islamist-money-flows-hillary-clinton/)
** James Comey Internal Memo =E2=80=93 Explains Why He Informed Congress o=
f Clinton Investigation (http://www.rightsidenews.com/editorial/us-opinion=
-and-editorial/james-comey-internal-memo-explains-informed-congress-clinto=
n-investigation/)
** Will Barack Obama Delay Or Suspend The Election If Hillary Is Forced Ou=
t By The New FBI Email Investigation? (http://www.rightsidenews.com/editor=
ial/us-opinion-and-editorial/will-barack-obama-delay-or-suspend-the-electi=
on-if-hillary-is-forced-out-by-the-new-fbi-email-investigation/


** Help Spread The News!
------------------------------------------------------------
Subscribe to email (http://eepurl.com/bBbJ6v)

Grab our RSS Feed (http://www.rightsidenews.com/feed/)

Tip Jar (http://www.rightsidenews.com/uncategorised/right-side-news-needs-=
your-help/)
https://www.facebook.com/RightSideNewsUS?utm_source=3DRight+Side+News&utm_=
campaign=3D0d0f4f4ca8-daily-rss-newsletter&utm_medium=3Demail
https://twitter.com/rightsidenews?utm_source=3DRight+Side+News&utm_campaig=
n=3D0d0f4f4ca8-daily-rss-newsletter&utm_medium=3Demail

=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=
=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=
=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D
Copyright =C2=A9 2016 Right Side News=2C All rights reserved.
 You are receiving this because you opted in to receive our newsletter

Our mailing address is:
Right Side News
2711 Buford Road=2C Suite 105
North Chesterfield=2C Virginia 23235
USA
Want to change how you receive these emails?
You can ** update your preferences (http://rightsidenews.us3.list-manage.c=
om/profile?u=3D16fae18c4307c7f4c291009ac&id=3D12c31c183e&e=3D84cf9d0f56)
or ** unsubscribe from this list (http://rightsidenews.us3.list-manage2.co=
m/unsubscribe?u=3D16fae18c4307c7f4c291009ac&id=3D12c31c183e&e=3D84cf9d0f56&c=
=3Dd530a6546a)
--_----------=_MCPart_1387133383
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.or=
g/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns=3D"http://www.w3.org/1999/xhtml">
    <head>
    =09<!-- NAME: RIGHT SIDEBAR RSS -->
        <meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3D=
UTF-8">
        <meta name=3D"viewport" content=3D"width=3Ddevice-width=2C initial=
-scale=3D1.0">
        <title>Posts from Right Side News for 10/30/2016</title>

    <style type=3D"text/css">
=09=09body=2C#bodyTable=2C#bodyCell{
=09=09=09height:100% !important;
=09=09=09margin:0;
=09=09=09padding:0;
=09=09=09width:100% !important;
=09=09}
=09=09table{
=09=09=09border-collapse:collapse;
=09=09}
=09=09img=2Ca img{
=09=09=09border:0;
=09=09=09outline:none;
=09=09=09text-decoration:none;
=09=09}
=09=09h1=2Ch2=2Ch3=2Ch4=2Ch5=2Ch6{
=09=09=09margin:0;
=09=09=09padding:0;
=09=09}
=09=09p{
=09=09=09margin:1em 0;
=09=09=09padding:0;
=09=09}
=09=09a{
=09=09=09word-wrap:break-word;
=09=09}
=09=09.ReadMsgBody{
=09=09=09width:100%;
=09=09}
=09=09.ExternalClass{
=09=09=09width:100%;
=09=09}
=09=09.ExternalClass=2C.ExternalClass p=2C.ExternalClass span=2C.ExternalC=
lass font=2C.ExternalClass td=2C.ExternalClass div{
=09=09=09line-height:100%;
=09=09}
=09=09table=2Ctd{
=09=09=09mso-table-lspace:0pt;
=09=09=09mso-table-rspace:0pt;
=09=09}
=09=09#outlook a{
=09=09=09padding:0;
=09=09}
=09=09img{
=09=09=09-ms-interpolation-mode:bicubic;
=09=09}
=09=09body=2Ctable=2Ctd=2Cp=2Ca=2Cli=2Cblockquote{
=09=09=09-ms-text-size-adjust:100%;
=09=09=09-webkit-text-size-adjust:100%;
=09=09}
=09=09#templatePreheader=2C#templateHeader=2C#templateBody=2C#templateSide=
bar=2C#templateSidebarInner=2C#templateBodyInner=2C#templateFooter{
=09=09=09min-width:100%;
=09=09}
=09=09#bodyCell{
=09=09=09padding:20px;
=09=09}
=09=09.mcnImage{
=09=09=09vertical-align:bottom;
=09=09}
=09=09.mcnTextContent img{
=09=09=09height:auto !important;
=09=09}
=09=09body=2C#bodyTable{
=09=09=09background-color:#F2F2F2;
=09=09}
=09=09#bodyCell{
=09=09=09border-top:0;
=09=09}
=09=09#templateContainer{
=09=09=09border:0;
=09=09}
=09=09h1{
=09=09=09color:#606060 !important;
=09=09=09display:block;
=09=09=09font-family:Helvetica;
=09=09=09font-size:40px;
=09=09=09font-style:normal;
=09=09=09font-weight:bold;
=09=09=09line-height:125%;
=09=09=09letter-spacing:-1px;
=09=09=09margin:0;
=09=09=09text-align:left;
=09=09}
=09=09h2{
=09=09=09color:#404040 !important;
=09=09=09display:block;
=09=09=09font-family:Helvetica;
=09=09=09font-size:26px;
=09=09=09font-style:normal;
=09=09=09font-weight:bold;
=09=09=09line-height:125%;
=09=09=09letter-spacing:-.75px;
=09=09=09margin:0;
=09=09=09text-align:left;
=09=09}
=09=09h3{
=09=09=09color:#606060 !important;
=09=09=09display:block;
=09=09=09font-family:Helvetica;
=09=09=09font-size:18px;
=09=09=09font-style:normal;
=09=09=09font-weight:bold;
=09=09=09line-height:125%;
=09=09=09letter-spacing:-.5px;
=09=09=09margin:0;
=09=09=09text-align:left;
=09=09}
=09=09h4{
=09=09=09color:#808080 !important;
=09=09=09display:block;
=09=09=09font-family:Helvetica;
=09=09=09font-size:16px;
=09=09=09font-style:normal;
=09=09=09font-weight:bold;
=09=09=09line-height:125%;
=09=09=09letter-spacing:normal;
=09=09=09margin:0;
=09=09=09text-align:left;
=09=09}
=09=09#templatePreheader{
=09=09=09background-color:#FFFFFF;
=09=09=09background-image:none;
=09=09=09background-repeat:no-repeat;
=09=09=09background-position:center;
=09=09=09background-size:cover;
=09=09=09border-top:0;
=09=09=09border-bottom:0;
=09=09}
=09=09.preheaderContainer .mcnTextContent=2C.preheaderContainer .mcnTextCo=
ntent p{
=09=09=09color:#606060;
=09=09=09font-family:Helvetica;
=09=09=09font-size:11px;
=09=09=09line-height:125%;
=09=09=09text-align:left;
=09=09}
=09=09.preheaderContainer .mcnTextContent a{
=09=09=09color:#606060;
=09=09=09font-weight:normal;
=09=09=09text-decoration:underline;
=09=09}
=09=09#templateHeader{
=09=09=09background-color:#FFFFFF;
=09=09=09background-image:none;
=09=09=09background-repeat:no-repeat;
=09=09=09background-position:center;
=09=09=09background-size:cover;
=09=09=09border-top:0;
=09=09=09border-bottom:0;
=09=09}
=09=09.headerContainer .mcnTextContent=2C.headerContainer .mcnTextContent=
 p{
=09=09=09color:#606060;
=09=09=09font-family:Helvetica;
=09=09=09font-size:15px;
=09=09=09line-height:150%;
=09=09=09text-align:left;
=09=09}
=09=09.headerContainer .mcnTextContent a{
=09=09=09color:#6DC6DD;
=09=09=09font-weight:normal;
=09=09=09text-decoration:underline;
=09=09}
=09=09#templateBody{
=09=09=09background-color:#FFFFFF;
=09=09=09border-top:0;
=09=09=09border-bottom:0;
=09=09}
=09=09#templateSidebar{
=09=09=09border-left:0;
=09=09}
=09=09.bodyContainer .mcnTextContent=2C.bodyContainer .mcnTextContent p{
=09=09=09color:#606060;
=09=09=09font-family:Helvetica;
=09=09=09font-size:15px;
=09=09=09line-height:150%;
=09=09=09text-align:left;
=09=09}
=09=09.bodyContainer .mcnTextContent a{
=09=09=09color:#0b53b1;
=09=09=09font-weight:normal;
=09=09=09text-decoration:underline;
=09=09}
=09=09#templateSidebar{
=09=09=09background-color:#FFFFFF;
=09=09}
=09=09#templateSidebarInner{
=09=09=09border-left:0;
=09=09}
=09=09.sidebarContainer .mcnTextContent=2C.sidebarContainer .mcnTextConten=
t p{
=09=09=09color:#606060;
=09=09=09font-family:Helvetica;
=09=09=09font-size:13px;
=09=09=09line-height:125%;
=09=09=09text-align:left;
=09=09}
=09=09.sidebarContainer .mcnTextContent a{
=09=09=09color:#6DC6DD;
=09=09=09font-weight:normal;
=09=09=09text-decoration:underline;
=09=09}
=09=09#templateFooter{
=09=09=09background-color:#FFFFFF;
=09=09=09background-image:none;
=09=09=09background-repeat:no-repeat;
=09=09=09background-position:center;
=09=09=09background-size:cover;
=09=09=09border-top:0;
=09=09=09border-bottom:0;
=09=09}
=09=09.footerContainer .mcnTextContent=2C.footerContainer .mcnTextContent=
 p{
=09=09=09color:#606060;
=09=09=09font-family:Helvetica;
=09=09=09font-size:11px;
=09=09=09line-height:125%;
=09=09=09text-align:left;
=09=09}
=09=09.footerContainer .mcnTextContent a{
=09=09=09color:#606060;
=09=09=09font-weight:normal;
=09=09=09text-decoration:underline;
=09=09}
=09@media only screen and (max-width: 480px){
=09=09body=2Ctable=2Ctd=2Cp=2Ca=2Cli=2Cblockquote{
=09=09=09-webkit-text-size-adjust:none !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09body{
=09=09=09width:100% !important;
=09=09=09min-width:100% !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09td[id=3DbodyCell]{
=09=09=09padding:10px !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09table[class=3DmcnTextContentContainer]{
=09=09=09width:100% !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09.mcnBoxedTextContentContainer{
=09=09=09max-width:100% !important;
=09=09=09min-width:100% !important;
=09=09=09width:100% !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09table[class=3Dmcpreview-image-uploader]{
=09=09=09width:100% !important;
=09=09=09display:none !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09img[class=3DmcnImage]{
=09=09=09width:100% !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09table[class=3DmcnImageGroupContentContainer]{
=09=09=09width:100% !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09td[class=3DmcnImageGroupContent]{
=09=09=09padding:9px !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09td[class=3DmcnImageGroupBlockInner]{
=09=09=09padding-bottom:0 !important;
=09=09=09padding-top:0 !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09tbody[class=3DmcnImageGroupBlockOuter]{
=09=09=09padding-bottom:9px !important;
=09=09=09padding-top:9px !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09table[class=3DmcnCaptionTopContent]=2Ctable[class=3DmcnCaptionBott=
omContent]{
=09=09=09width:100% !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09table[class=3DmcnCaptionLeftTextContentContainer]=2Ctable[class=3D=
mcnCaptionRightTextContentContainer]=2Ctable[class=3DmcnCaptionLeftImageC=
ontentContainer]=2Ctable[class=3DmcnCaptionRightImageContentContainer]=2C=
table[class=3DmcnImageCardLeftTextContentContainer]=2Ctable[class=3DmcnI=
mageCardRightTextContentContainer]{
=09=09=09width:100% !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09td[class=3DmcnImageCardLeftImageContent]=2Ctd[class=3DmcnImageCard=
RightImageContent]{
=09=09=09padding-right:18px !important;
=09=09=09padding-left:18px !important;
=09=09=09padding-bottom:0 !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09td[class=3DmcnImageCardBottomImageContent]{
=09=09=09padding-bottom:9px !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09td[class=3DmcnImageCardTopImageContent]{
=09=09=09padding-top:18px !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09table[class=3DmcnCaptionLeftContentOuter] td[class=3DmcnTextConten=
t]=2Ctable[class=3DmcnCaptionRightContentOuter] td[class=3DmcnTextConten=
t]{
=09=09=09padding-top:9px !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09td[class=3DmcnCaptionBlockInner] table[class=3DmcnCaptionTopConten=
t]:last-child td[class=3DmcnTextContent]{
=09=09=09padding-top:18px !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09td[class=3DmcnBoxedTextContentColumn]{
=09=09=09padding-left:18px !important;
=09=09=09padding-right:18px !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09td[class=3DsectionContainer]{
=09=09=09display:block !important;
=09=09=09max-width:600px !important;
=09=09=09width:100% !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09td[class=3DmcnTextContent]{
=09=09=09padding-right:18px !important;
=09=09=09padding-left:18px !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09table[id=3DtemplateContainer]=2Ctable[id=3DtemplatePreheader]=2Cta=
ble[id=3DtemplateHeader]=2Ctable[id=3DtemplateBody]=2Ctable[id=3Dtempla=
teBodyInner]=2Ctable[id=3DtemplateSidebar]=2Ctable[id=3DtemplateFooter]{
=09=09=09max-width:600px !important;
=09=09=09width:100% !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09h1{
=09=09=09font-size:24px !important;
=09=09=09line-height:125% !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09h2{
=09=09=09font-size:20px !important;
=09=09=09line-height:125% !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09h3{
=09=09=09font-size:18px !important;
=09=09=09line-height:125% !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09h4{
=09=09=09font-size:16px !important;
=09=09=09line-height:125% !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09table[class=3DmcnBoxedTextContentContainer] td[class=3DmcnTextCont=
ent]=2Ctd[class=3DmcnBoxedTextContentContainer] td[class=3DmcnTextConten=
t] p{
=09=09=09font-size:18px !important;
=09=09=09line-height:125% !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09table[id=3DtemplatePreheader]{
=09=09=09display:block !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09td[class=3DpreheaderContainer] td[class=3DmcnTextContent]=2Ctd[cl=
ass=3DpreheaderContainer] td[class=3DmcnTextContent] p{
=09=09=09font-size:14px !important;
=09=09=09line-height:115% !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09td[class=3DheaderContainer] td[class=3DmcnTextContent]=2Ctd[class=
=3DheaderContainer] td[class=3DmcnTextContent] p{
=09=09=09font-size:18px !important;
=09=09=09line-height:125% !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09td[class=3DbodyContainer] td[class=3DmcnTextContent]=2Ctd[class=
=3DbodyContainer] td[class=3DmcnTextContent] p{
=09=09=09font-size:18px !important;
=09=09=09line-height:125% !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09td[class=3DsidebarContainer] td[class=3DmcnTextContent]=2Ctd[clas=
s=3DsidebarContainer] td[class=3DmcnTextContent] p{
=09=09=09font-size:18px !important;
=09=09=09line-height:125% !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09table[id=3DtemplateSidebar]{
=09=09=09border-left:0 !important;
=09=09=09border-right:0 !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09table[id=3DtemplateSidebarInner]{
=09=09=09border-left:0 !important;
=09=09=09border-right:0 !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09td[class=3DfooterContainer] td[class=3DmcnTextContent]=2Ctd[class=
=3DfooterContainer] td[class=3DmcnTextContent] p{
=09=09=09font-size:14px !important;
=09=09=09line-height:115% !important;
=09=09}

}=09@media only screen and (max-width: 480px){
=09=09td[class=3DfooterContainer] a[class=3DutilityLink]{
=09=09=09display:block !important;
=09=09}

}</style></head>
    <body leftmargin=3D"0" marginwidth=3D"0" topmargin=3D"0" marginheight=
=3D"0" offset=3D"0" style=3D"margin: 0;padding: 0;-ms-text-size-adjust: 10=
0%;-webkit-text-size-adjust: 100%;background-color: #F2F2F2;height: 100% !=
important;width: 100% !important;">
        <center>
            <table align=3D"center" border=3D"0" cellpadding=3D"0" cellspa=
cing=3D"0" height=3D"100%" width=3D"100%" id=3D"bodyTable" style=3D"border=
-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-s=
ize-adjust: 100%;-webkit-text-size-adjust: 100%;margin: 0;padding: 0;backg=
round-color: #F2F2F2;height: 100% !important;width: 100% !important;">
                <tr>
                    <td align=3D"center" valign=3D"top" id=3D"bodyCell" st=
yle=3D"mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 1=
00%;-webkit-text-size-adjust: 100%;margin: 0;padding: 20px;border-top: 0;h=
eight: 100% !important;width: 100% !important;">
                        <!-- BEGIN TEMPLATE // -->
                        <table border=3D"0" cellpadding=3D"0" cellspacing=
=3D"0" width=3D"600" id=3D"templateContainer" style=3D"border-collapse: co=
llapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 1=
00%;-webkit-text-size-adjust: 100%;border: 0;">
                            <tr>
                                <td align=3D"center" valign=3D"top" style=
=3D"mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%=
;-webkit-text-size-adjust: 100%;">
                                    <!-- BEGIN PREHEADER // -->
                                    <table border=3D"0" cellpadding=3D"0"=
 cellspacing=3D"0" width=3D"600" id=3D"templatePreheader" style=3D"backgro=
und: #FFFFFF none no-repeat center/cover;border-collapse: collapse;mso-tab=
le-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-te=
xt-size-adjust: 100%;min-width: 100%;background-color: #FFFFFF;background-=
image: none;background-repeat: no-repeat;background-position: center;backg=
round-size: cover;border-top: 0;border-bottom: 0;">
                                        <tr>
                                        =09<td valign=3D"top" class=3D"pre=
headerContainer" style=3D"padding-top: 9px;mso-table-lspace: 0pt;mso-table=
-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;"><=
table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" clas=
s=3D"mcnTextBlock" style=3D"border-collapse: collapse;mso-table-lspace: 0p=
t;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjus=
t: 100%;">
    <tbody class=3D"mcnTextBlockOuter">
        <tr>
            <td valign=3D"top" class=3D"mcnTextBlockInner" style=3D"mso-ta=
ble-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-t=
ext-size-adjust: 100%;">

                <table align=3D"left" border=3D"0" cellpadding=3D"0" cells=
pacing=3D"0" width=3D"366" class=3D"mcnTextContentContainer" style=3D"bord=
er-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text=
-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                    <tbody><tr>

                        <td valign=3D"top" class=3D"mcnTextContent" style=
=3D"padding-top: 9px;padding-left: 18px;padding-bottom: 9px;padding-right:=
 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;=
-webkit-text-size-adjust: 100%;color: #606060;font-family: Helvetica;font-=
size: 11px;line-height: 125%;text-align: left;">

                            Daily Updates from Right Side News
                        </td>
                    </tr>
                </tbody></table>

                <table align=3D"right" border=3D"0" cellpadding=3D"0" cell=
spacing=3D"0" width=3D"197" class=3D"mcnTextContentContainer" style=3D"bor=
der-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-tex=
t-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                    <tbody><tr>

                        <td valign=3D"top" class=3D"mcnTextContent" style=
=3D"padding-top: 9px;padding-right: 18px;padding-bottom: 9px;padding-left:=
 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;=
-webkit-text-size-adjust: 100%;color: #606060;font-family: Helvetica;font-=
size: 11px;line-height: 125%;text-align: left;">

                            <a href=3D"http://us3.campaign-archive1.com/?u=
=3D16fae18c4307c7f4c291009ac&id=3Dd530a6546a&e=3D84cf9d0f56" target=3D"_blan=
k" style=3D"word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-=
size-adjust: 100%;color: #606060;font-weight: normal;text-decoration: unde=
rline;">View this email in your browser</a>
                        </td>
                    </tr>
                </tbody></table>

            </td>
        </tr>
    </tbody>
</table></td>
                                        </tr>
                                    </table>
                                    <!-- // END PREHEADER -->
                                </td>
                            </tr>
                            <tr>
                                <td align=3D"center" valign=3D"top" style=
=3D"mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%=
;-webkit-text-size-adjust: 100%;">
                                    <!-- BEGIN HEADER // -->
                                    <table border=3D"0" cellpadding=3D"0"=
 cellspacing=3D"0" width=3D"600" id=3D"templateHeader" style=3D"background=
: #FFFFFF none no-repeat center/cover;border-collapse: collapse;mso-table-=
lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-=
size-adjust: 100%;min-width: 100%;background-color: #FFFFFF;background-ima=
ge: none;background-repeat: no-repeat;background-position: center;backgrou=
nd-size: cover;border-top: 0;border-bottom: 0;">
                                        <tr>
                                            <td valign=3D"top" class=3D"he=
aderContainer" style=3D"mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-te=
xt-size-adjust: 100%;-webkit-text-size-adjust: 100%;"><table border=3D"0"=
 cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" class=3D"mcnImageBlock=
" style=3D"min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt=
;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust=
: 100%;">
    <tbody class=3D"mcnImageBlockOuter">
            <tr>
                <td valign=3D"top" style=3D"padding: 9px;mso-table-lspace:=
 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-ad=
just: 100%;" class=3D"mcnImageBlockInner">
                    <table align=3D"left" width=3D"100%" border=3D"0" cell=
padding=3D"0" cellspacing=3D"0" class=3D"mcnImageContentContainer" style=
=3D"min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-ta=
ble-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;=
">
                        <tbody><tr>
                            <td class=3D"mcnImageContent" valign=3D"top" s=
tyle=3D"padding-right: 9px;padding-left: 9px;padding-top: 0;padding-bottom=
: 0;text-align: center;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-tex=
t-size-adjust: 100%;-webkit-text-size-adjust: 100%;">


                                        <img align=3D"center" alt=3D"" src=
=3D"https://gallery.mailchimp.com/16fae18c4307c7f4c291009ac/images/2df82d5=
f-93ac-4d3b-9a83-5f697fff5d88.gif" width=3D"564.0000305175781" style=3D"ma=
x-width: 640px;padding-bottom: 0;display: inline !important;vertical-align=
: bottom;border: 0;outline: none;text-decoration: none;-ms-interpolation-m=
ode: bicubic;" class=3D"mcnImage">


                            </td>
                        </tr>
                    </tbody></table>
                </td>
            </tr>
    </tbody>
</table></td>
                                        </tr>
                                    </table>
                                    <!-- // END HEADER -->
                                </td>
                            </tr>
                            <tr>
                                <td align=3D"center" valign=3D"top" style=
=3D"mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%=
;-webkit-text-size-adjust: 100%;">
                                    <!-- BEGIN BODY // -->
                                    <table border=3D"0" cellpadding=3D"0"=
 cellspacing=3D"0" width=3D"600" id=3D"templateBody" style=3D"border-colla=
pse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-ad=
just: 100%;-webkit-text-size-adjust: 100%;min-width: 100%;background-color=
: #FFFFFF;border-top: 0;border-bottom: 0;">
                                        <tr>
                                            <td align=3D"left" valign=3D"t=
op" width=3D"390" class=3D"sectionContainer" style=3D"mso-table-lspace: 0p=
t;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjus=
t: 100%;">
                                            =09<table border=3D"0" cellpad=
ding=3D"0" cellspacing=3D"0" width=3D"100%" id=3D"templateBodyInner" style=
=3D"border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;=
-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;min-width: 100%;=
">
                                                =09<tr>
                                                    =09<td valign=3D"top"=
 class=3D"bodyContainer" style=3D"mso-table-lspace: 0pt;mso-table-rspace:=
 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;"><table bo=
rder=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" class=3D"mcn=
TextBlock" style=3D"border-collapse: collapse;mso-table-lspace: 0pt;mso-ta=
ble-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;=
">
    <tbody class=3D"mcnTextBlockOuter">
        <tr>
            <td valign=3D"top" class=3D"mcnTextBlockInner" style=3D"mso-ta=
ble-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-t=
ext-size-adjust: 100%;">

                <table align=3D"left" border=3D"0" cellpadding=3D"0" cells=
pacing=3D"0" width=3D"NaN" class=3D"mcnTextContentContainer" style=3D"bord=
er-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text=
-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                    <tbody><tr>

                        <td valign=3D"top" class=3D"mcnTextContent" style=
=3D"padding-top: 9px;padding-right: 18px;padding-bottom: 9px;padding-left:=
 18px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 10=
0%;-webkit-text-size-adjust: 100%;color: #606060;font-family: Helvetica;fo=
nt-size: 15px;line-height: 150%;text-align: left;">

                            Updates from
<h1 style=3D"margin: 0;padding: 0;display: block;font-family: Helvetica;fo=
nt-size: 40px;font-style: normal;font-weight: bold;line-height: 125%;lette=
r-spacing: -1px;text-align: left;color: #606060 !important;">Right Side Ne=
ws</h1>

                        </td>
                    </tr>
                </tbody></table>

            </td>
        </tr>
    </tbody>
</table><table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"1=
00%" class=3D"mcnTextBlock" style=3D"border-collapse: collapse;mso-table-l=
space: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-s=
ize-adjust: 100%;">
    <tbody class=3D"mcnTextBlockOuter">
        <tr>
            <td valign=3D"top" class=3D"mcnTextBlockInner" style=3D"mso-ta=
ble-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-t=
ext-size-adjust: 100%;">

                <table align=3D"left" border=3D"0" cellpadding=3D"0" cells=
pacing=3D"0" width=3D"NaN" class=3D"mcnTextContentContainer" style=3D"bord=
er-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text=
-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                    <tbody><tr>

                        <td valign=3D"top" class=3D"mcnTextContent" style=
=3D"padding-top: 9px;padding-right: 18px;padding-bottom: 9px;padding-left:=
 18px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 10=
0%;-webkit-text-size-adjust: 100%;color: #606060;font-family: Helvetica;fo=
nt-size: 15px;line-height: 150%;text-align: left;">


<h2 class=3D"mc-toc-title" style=3D"margin: 0;padding: 0;display: block;fo=
nt-family: Helvetica;font-size: 26px;font-style: normal;font-weight: bold;=
line-height: 125%;letter-spacing: -.75px;text-align: left;color: #404040 !=
important;"><a href=3D"http://rightsidenews.us3.list-manage.com/track/clic=
k?u=3D16fae18c4307c7f4c291009ac&id=3Da31d8eaa85&e=3D84cf9d0f56" target=3D=
"_blank" style=3D"word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit=
-text-size-adjust: 100%;color: #0b53b1;font-weight: normal;text-decoration=
: underline;"><span style=3D"color:#0000ff">Vets=C2=A0Demand=C2=A0Hillary=
=C2=A0Clinton=C2=A0Cut=C2=A0Ties=C2=A0 with=C2=A0Abedin=2C=C2=A0Mills=C2=
=A0and=C2=A0Samuelson=C2=A0</span></a></h2>
<em>Posted on Oct 29=2C 2016 01:07 pm</em><br>
<a href=3D"http://rightsidenews.us3.list-manage.com/track/click?u=3D16fae1=
8c4307c7f4c291009ac&id=3D0ff1d4a5c6&e=3D84cf9d0f56" target=3D"_blank" sty=
le=3D"word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-a=
djust: 100%;color: #0b53b1;font-weight: normal;text-decoration: underline;=
">Read in browser =C2=BB</a><br>
<a href=3D"http://rightsidenews.us3.list-manage1.com/track/click?u=3D16fae=
18c4307c7f4c291009ac&id=3D250587b844&e=3D84cf9d0f56" target=3D"_blank" st=
yle=3D"word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-=
adjust: 100%;color: #0b53b1;font-weight: normal;text-decoration: underline=
;"><img src=3D"http://cdn-images.mailchimp.com/social_connect_tweet.png" b=
order=3D"0" width=3D"55" height=3D"20" style=3D"display: inline;border: 0;=
outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;height=
: auto !important;" alt=3D"share on Twitter"></a> <a href=3D"http://rights=
idenews.us3.list-manage2.com/track/click?u=3D16fae18c4307c7f4c291009ac&id=
=3D3a3c02224e&e=3D84cf9d0f56" title=3D"Like Vets=C2=A0Demand=C2=A0Hillary=
=C2=A0Clinton=C2=A0Cut=C2=A0Ties=C2=A0 with=C2=A0Abedin=2C=C2=A0Mills=C2=
=A0and=C2=A0Samuelson=C2=A0 on Facebook" rel=3D"socialproxy" id=3D"fblike-=
94c8793d" style=3D"word-wrap: break-word;-ms-text-size-adjust: 100%;-webki=
t-text-size-adjust: 100%;color: #0b53b1;font-weight: normal;text-decoratio=
n: underline;"><img src=3D"http://cdn-images.mailchimp.com/fb/like.gif" bo=
rder=3D"0" alt=3D"Like Vets=C2=A0Demand=C2=A0Hillary=C2=A0Clinton=C2=A0Cut=
=C2=A0Ties=C2=A0 with=C2=A0Abedin=2C=C2=A0Mills=C2=A0and=C2=A0Samuelson=C2=
=A0 on Facebook" height=3D"20" width=3D"48" style=3D"display: inline;borde=
r: 0;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;h=
eight: auto !important;"></a><br>
<br>

<h2 class=3D"mc-toc-title" style=3D"margin: 0;padding: 0;display: block;fo=
nt-family: Helvetica;font-size: 26px;font-style: normal;font-weight: bold;=
line-height: 125%;letter-spacing: -.75px;text-align: left;color: #404040 !=
important;"><a href=3D"http://rightsidenews.us3.list-manage.com/track/clic=
k?u=3D16fae18c4307c7f4c291009ac&id=3D807deafc34&e=3D84cf9d0f56" target=3D=
"_blank" style=3D"word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit=
-text-size-adjust: 100%;color: #0b53b1;font-weight: normal;text-decoration=
: underline;"><span style=3D"color:#0000ff">FBI Found =E2=80=9CTens Of Tho=
usands Of Emails=E2=80=9D Belonging To Huma Abedin On Weiner=E2=80=99s Lap=
top</span></a></h2>
<em>Posted on Oct 29=2C 2016 11:41 am</em><br>
<a href=3D"http://rightsidenews.us3.list-manage1.com/track/click?u=3D16fae=
18c4307c7f4c291009ac&id=3D3c41890410&e=3D84cf9d0f56" target=3D"_blank" st=
yle=3D"word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-=
adjust: 100%;color: #0b53b1;font-weight: normal;text-decoration: underline=
;">Read in browser =C2=BB</a><br>
<a href=3D"http://rightsidenews.us3.list-manage.com/track/click?u=3D16fae1=
8c4307c7f4c291009ac&id=3D2f04bbb265&e=3D84cf9d0f56" target=3D"_blank" sty=
le=3D"word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-a=
djust: 100%;color: #0b53b1;font-weight: normal;text-decoration: underline;=
"><img src=3D"http://cdn-images.mailchimp.com/social_connect_tweet.png" bo=
rder=3D"0" width=3D"55" height=3D"20" style=3D"display: inline;border: 0;o=
utline: none;text-decoration: none;-ms-interpolation-mode: bicubic;height:=
 auto !important;" alt=3D"share on Twitter"></a> <a href=3D"http://rightsi=
denews.us3.list-manage1.com/track/click?u=3D16fae18c4307c7f4c291009ac&id=
=3D13c622cb7b&e=3D84cf9d0f56" title=3D"Like FBI Found =E2=80=9CTens Of Th=
ousands Of Emails=E2=80=9D Belonging To Huma Abedin On Weiner=E2=80=99s La=
ptop on Facebook" rel=3D"socialproxy" id=3D"fblike-9327ff71" style=3D"word=
-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100=
%;color: #0b53b1;font-weight: normal;text-decoration: underline;"><img src=
=3D"http://cdn-images.mailchimp.com/fb/like.gif" border=3D"0" alt=3D"Like=
 FBI Found =E2=80=9CTens Of Thousands Of Emails=E2=80=9D Belonging To Huma=
 Abedin On Weiner=E2=80=99s Laptop on Facebook" height=3D"20" width=3D"48"=
 style=3D"display: inline;border: 0;outline: none;text-decoration: none;-m=
s-interpolation-mode: bicubic;height: auto !important;"></a><br>
<br>
<br>
&nbsp;
<h3 class=3D"h3" style=3D"margin: 0;padding: 0;display: block;font-family:=
 Helvetica;font-size: 18px;font-style: normal;font-weight: bold;line-heigh=
t: 125%;letter-spacing: -.5px;text-align: left;color: #606060 !important;"=
>Recent Articles:</h3>
<span style=3D"color:#000000"><a rel=3D"nofollow" target=3D"_blank" href=
=3D"http://rightsidenews.us3.list-manage.com/track/click?u=3D16fae18c4307c=
7f4c291009ac&id=3D20b03af196&e=3D84cf9d0f56" class=3D"rss-recent" style=
=3D"word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-adj=
ust: 100%;color: #0b53b1;font-weight: normal;text-decoration: underline;">=
Federal Outlaws Brutally Attack Bundy Defense Attorney Marcus Mumford</a><=
br><a rel=3D"nofollow" target=3D"_blank" href=3D"http://rightsidenews.us3.=
list-manage.com/track/click?u=3D16fae18c4307c7f4c291009ac&id=3D17178eb194&=
e=3D84cf9d0f56" class=3D"rss-recent" style=3D"word-wrap: break-word;-ms-t=
ext-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #0b53b1;font-w=
eight: normal;text-decoration: underline;">Americans Want Hillary in Jail=
 =E2=80=93 Rightly So!</a><br><a rel=3D"nofollow" target=3D"_blank" href=
=3D"http://rightsidenews.us3.list-manage.com/track/click?u=3D16fae18c4307c=
7f4c291009ac&id=3D968468bfc3&e=3D84cf9d0f56" class=3D"rss-recent" style=
=3D"word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-adj=
ust: 100%;color: #0b53b1;font-weight: normal;text-decoration: underline;">=
More Islamist Money Flows to Hillary Clinton</a><br><a rel=3D"nofollow" ta=
rget=3D"_blank" href=3D"http://rightsidenews.us3.list-manage.com/track/cli=
ck?u=3D16fae18c4307c7f4c291009ac&id=3Da3b2d63568&e=3D84cf9d0f56" class=3D=
"rss-recent" style=3D"word-wrap: break-word;-ms-text-size-adjust: 100%;-we=
bkit-text-size-adjust: 100%;color: #0b53b1;font-weight: normal;text-decora=
tion: underline;">James Comey Internal Memo =E2=80=93 Explains Why He Info=
rmed Congress of Clinton Investigation</a><br><a rel=3D"nofollow" target=
=3D"_blank" href=3D"http://rightsidenews.us3.list-manage.com/track/click?u=
=3D16fae18c4307c7f4c291009ac&id=3D703197f07c&e=3D84cf9d0f56" class=3D"rss=
-recent" style=3D"word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit=
-text-size-adjust: 100%;color: #0b53b1;font-weight: normal;text-decoration=
: underline;">Will Barack Obama Delay Or Suspend The Election If Hillary I=
s Forced Out By The New FBI Email Investigation?</a></span>
                        </td>
                    </tr>
                </tbody></table>

            </td>
        </tr>
    </tbody>
</table></td>
                                                    </tr>
                                                </table>
                                            </td>
                                            <td align=3D"left" valign=3D"t=
op" width=3D"200" class=3D"sectionContainer" style=3D"mso-table-lspace: 0p=
t;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjus=
t: 100%;">
                                                <table border=3D"0" cellpa=
dding=3D"0" cellspacing=3D"0" width=3D"100%" id=3D"templateSidebar" style=
=3D"border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;=
-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;min-width: 100%;=
border-left: 0;background-color: #FFFFFF;">
                                                =09<tr>
                                                    =09<td align=3D"right"=
 valign=3D"top" style=3D"mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-t=
ext-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                                                        =09<table border=
=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" id=3D"templateSi=
debarInner" style=3D"border-collapse: collapse;mso-table-lspace: 0pt;mso-t=
able-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%=
;min-width: 100%;border-left: 0;">
                                                            =09<tr>
                                                                =09<td val=
ign=3D"top" class=3D"sidebarContainer" style=3D"mso-table-lspace: 0pt;mso-=
table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100=
%;"><table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%"=
 class=3D"mcnBoxedTextBlock" style=3D"min-width: 100% !important;border-co=
llapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size=
-adjust: 100%;-webkit-text-size-adjust: 100%;">
    <!--[if gte mso 9]>
=09<table align=3D"center" border=3D"0" cellspacing=3D"0" cellpadding=3D"0=
" width=3D"100%">
=09<![endif]-->
=09<tbody class=3D"mcnBoxedTextBlockOuter">
        <tr>
            <td valign=3D"top" class=3D"mcnBoxedTextBlockInner" style=3D"m=
so-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-web=
kit-text-size-adjust: 100%;">

=09=09=09=09<!--[if gte mso 9]>
=09=09=09=09<td align=3D"center" valign=3D"top" ">
=09=09=09=09<![endif]-->
                <table align=3D"left" border=3D"0" cellpadding=3D"0" cells=
pacing=3D"0" width=3D"100%" class=3D"mcnBoxedTextContentContainer" style=
=3D"min-width: 204px;max-width: 204px;border-collapse: collapse;mso-table-=
lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-=
size-adjust: 100%;">
                    <tbody><tr>

                        <td style=3D"padding-top: 9px;padding-left: 18px;p=
adding-bottom: 9px;padding-right: 18px;mso-table-lspace: 0pt;mso-table-rsp=
ace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">

                            <table border=3D"0" cellpadding=3D"18" cellspa=
cing=3D"0" class=3D"mcnTextContentContainer" width=3D"100%" style=3D"min-w=
idth: 100% !important;background-color: #F3F0F0;border-collapse: collapse;=
mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-we=
bkit-text-size-adjust: 100%;">
                                <tbody><tr>
                                    <td valign=3D"top" class=3D"mcnTextCon=
tent" style=3D"color: #1882C9;font-family: Helvetica;font-size: 13px;font-=
weight: normal;line-height: 18px;text-align: left;mso-table-lspace: 0pt;ms=
o-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 1=
00%;">
                                        <h3 class=3D"null" style=3D"text-a=
lign: center;margin: 0;padding: 0;display: block;font-family: Helvetica;fo=
nt-size: 18px;font-style: normal;font-weight: bold;line-height: 125%;lette=
r-spacing: -.5px;color: #606060 !important;">Help Spread The News!</h3>

<div style=3D"text-align: left;"><br>
<a href=3D"http://rightsidenews.us3.list-manage1.com/track/click?u=3D16fae=
18c4307c7f4c291009ac&id=3D879c9ac26e&e=3D84cf9d0f56" target=3D"_blank" st=
yle=3D"word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-=
adjust: 100%;color: #6DC6DD;font-weight: normal;text-decoration: underline=
;"><span style=3D"color:#0000CD"><strong>Subscribe to email</strong></span=
></a><br>
&nbsp;</div>

<div style=3D"text-align: left;"><a href=3D"http://rightsidenews.us3.list-=
manage.com/track/click?u=3D16fae18c4307c7f4c291009ac&id=3D888bb86ddc&e=3D=
84cf9d0f56" target=3D"_blank" style=3D"word-wrap: break-word;-ms-text-size=
-adjust: 100%;-webkit-text-size-adjust: 100%;color: #6DC6DD;font-weight: n=
ormal;text-decoration: underline;"><span style=3D"color:#0000CD"><strong><=
span style=3D"line-height:1.6em">Grab our RSS Feed</span></strong></span><=
/a><br>
&nbsp;</div>

<div style=3D"text-align: left;"><a href=3D"http://rightsidenews.us3.list-=
manage.com/track/click?u=3D16fae18c4307c7f4c291009ac&id=3Dd3ad5bf8be&e=3D=
84cf9d0f56" target=3D"_blank" style=3D"word-wrap: break-word;-ms-text-size=
-adjust: 100%;-webkit-text-size-adjust: 100%;color: #6DC6DD;font-weight: n=
ormal;text-decoration: underline;"><span style=3D"color:#0000CD"><strong>T=
ip Jar</strong></span></a></div>

                                    </td>
                                </tr>
                            </tbody></table>
                        </td>
                    </tr>
                </tbody></table>
=09=09=09=09<!--[if gte mso 9]>
=09=09=09=09</td>
=09=09=09=09<![endif]-->

=09=09=09=09<!--[if gte mso 9]>
                </tr>
                </table>
=09=09=09=09<![endif]-->
            </td>
        </tr>
    </tbody>
</table><table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"1=
00%" class=3D"mcnFollowBlock" style=3D"border-collapse: collapse;mso-table=
-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text=
-size-adjust: 100%;">
    <tbody class=3D"mcnFollowBlockOuter">
        <tr>
            <td align=3D"center" valign=3D"top" style=3D"padding: 9px;mso-=
table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit=
-text-size-adjust: 100%;" class=3D"mcnFollowBlockInner">
                <table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" wi=
dth=3D"100%" class=3D"mcnFollowContentContainer" style=3D"border-collapse:=
 collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust=
: 100%;-webkit-text-size-adjust: 100%;">
    <tbody><tr>
        <td align=3D"center" style=3D"padding-left: 9px;padding-right: 9px=
;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-w=
ebkit-text-size-adjust: 100%;">
            <table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=
=3D"100%" class=3D"mcnFollowContent" style=3D"border-collapse: collapse;ms=
o-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webk=
it-text-size-adjust: 100%;">
                <tbody><tr>
                    <td align=3D"center" valign=3D"top" style=3D"padding-t=
op: 9px;padding-right: 9px;padding-left: 9px;mso-table-lspace: 0pt;mso-tab=
le-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;"=
>
                        <table border=3D"0" cellpadding=3D"0" cellspacing=
=3D"0" style=3D"border-collapse: collapse;mso-table-lspace: 0pt;mso-table-=
rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                            <tbody><tr>
                                <td valign=3D"top" style=3D"mso-table-lspa=
ce: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size=
-adjust: 100%;">
                                    <!--[if mso]>
                                    <table align=3D"left" border=3D"0" cel=
lspacing=3D"0" cellpadding=3D"0" width=3D"128">
                                    <tr>
                                    <td align=3D"left" valign=3D"top" widt=
h=3D"128">
                                    <![endif]-->



                                            <table align=3D"left" border=
=3D"0" cellpadding=3D"0" cellspacing=3D"0" style=3D"border-collapse: colla=
pse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%=
;-webkit-text-size-adjust: 100%;">
                                                <tbody><tr>
                                                    <td valign=3D"top" sty=
le=3D"padding-right: 10px;padding-bottom: 9px;mso-table-lspace: 0pt;mso-ta=
ble-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;=
" class=3D"mcnFollowContentItemContainer">
                                                        <table border=3D"0=
" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" class=3D"mcnFollowCon=
tentItem" style=3D"border-collapse: collapse;mso-table-lspace: 0pt;mso-tab=
le-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;"=
>
                                                            <tbody><tr>
                                                                <td align=
=3D"left" valign=3D"middle" style=3D"padding-top: 5px;padding-right: 10px;=
padding-bottom: 5px;padding-left: 9px;mso-table-lspace: 0pt;mso-table-rspa=
ce: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                                                                    <table=
 align=3D"left" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"=
" style=3D"border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspac=
e: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                                                                        <t=
body><tr>

                                                                         =
       <td align=3D"center" valign=3D"middle" width=3D"24" class=3D"mcnFol=
lowIconContent" style=3D"mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-t=
ext-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                                                                         =
           <a href=3D"http://rightsidenews.us3.list-manage1.com/track/clic=
k?u=3D16fae18c4307c7f4c291009ac&id=3D2b30525eb1&e=3D84cf9d0f56" target=3D=
"_blank" style=3D"word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit=
-text-size-adjust: 100%;"><img src=3D"http://cdn-images.mailchimp.com/icon=
s/social-block-v2/color-facebook-48.png" style=3D"display: block;border: 0=
;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;" hei=
ght=3D"24" width=3D"24" class=3D""></a>
                                                                         =
       </td>


                                                                        </=
tr>
                                                                    </tbod=
y></table>
                                                                </td>
                                                            </tr>
                                                        </tbody></table>
                                                    </td>
                                                </tr>
                                            </tbody></table>




                                            <table align=3D"left" border=
=3D"0" cellpadding=3D"0" cellspacing=3D"0" style=3D"border-collapse: colla=
pse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%=
;-webkit-text-size-adjust: 100%;">
                                                <tbody><tr>
                                                    <td valign=3D"top" sty=
le=3D"padding-right: 0;padding-bottom: 9px;mso-table-lspace: 0pt;mso-table=
-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" c=
lass=3D"mcnFollowContentItemContainer">
                                                        <table border=3D"0=
" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" class=3D"mcnFollowCon=
tentItem" style=3D"border-collapse: collapse;mso-table-lspace: 0pt;mso-tab=
le-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;"=
>
                                                            <tbody><tr>
                                                                <td align=
=3D"left" valign=3D"middle" style=3D"padding-top: 5px;padding-right: 10px;=
padding-bottom: 5px;padding-left: 9px;mso-table-lspace: 0pt;mso-table-rspa=
ce: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                                                                    <table=
 align=3D"left" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"=
" style=3D"border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspac=
e: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                                                                        <t=
body><tr>

                                                                         =
       <td align=3D"center" valign=3D"middle" width=3D"24" class=3D"mcnFol=
lowIconContent" style=3D"mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-t=
ext-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                                                                         =
           <a href=3D"http://rightsidenews.us3.list-manage2.com/track/clic=
k?u=3D16fae18c4307c7f4c291009ac&id=3Dc8f61cdb51&e=3D84cf9d0f56" target=3D=
"_blank" style=3D"word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit=
-text-size-adjust: 100%;"><img src=3D"http://cdn-images.mailchimp.com/icon=
s/social-block-v2/color-twitter-48.png" style=3D"display: block;border: 0;=
outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;" heig=
ht=3D"24" width=3D"24" class=3D""></a>
                                                                         =
       </td>


                                                                        </=
tr>
                                                                    </tbod=
y></table>
                                                                </td>
                                                            </tr>
                                                        </tbody></table>
                                                    </td>
                                                </tr>
                                            </tbody></table>


                                    <!--[if mso]>
                                    </td>
                                    </tr>
                                    </table>
                                    <![endif]-->
                                </td>
                            </tr>
                        </tbody></table>
                    </td>
                </tr>
            </tbody></table>
        </td>
    </tr>
</tbody></table>

            </td>
        </tr>
    </tbody>
</table></td>
                                                                </tr>
                                                            </table>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                    </table>
                                    <!-- // END BODY -->
                                </td>
                            </tr>
                            <tr>
                                <td align=3D"center" valign=3D"top" style=
=3D"mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%=
;-webkit-text-size-adjust: 100%;">
                                    <!-- BEGIN FOOTER // -->
                                    <table border=3D"0" cellpadding=3D"0"=
 cellspacing=3D"0" width=3D"600" id=3D"templateFooter" style=3D"background=
: #FFFFFF none no-repeat center/cover;border-collapse: collapse;mso-table-=
lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-=
size-adjust: 100%;min-width: 100%;background-color: #FFFFFF;background-ima=
ge: none;background-repeat: no-repeat;background-position: center;backgrou=
nd-size: cover;border-top: 0;border-bottom: 0;">
                                        <tr>
                                            <td valign=3D"top" class=3D"fo=
oterContainer" style=3D"padding-bottom: 9px;mso-table-lspace: 0pt;mso-tabl=
e-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">=
<table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" cla=
ss=3D"mcnTextBlock" style=3D"border-collapse: collapse;mso-table-lspace: 0=
pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adju=
st: 100%;">
    <tbody class=3D"mcnTextBlockOuter">
        <tr>
            <td valign=3D"top" class=3D"mcnTextBlockInner" style=3D"mso-ta=
ble-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-t=
ext-size-adjust: 100%;">

                <table align=3D"left" border=3D"0" cellpadding=3D"0" cells=
pacing=3D"0" width=3D"600" class=3D"mcnTextContentContainer" style=3D"bord=
er-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text=
-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                    <tbody><tr>

                        <td valign=3D"top" class=3D"mcnTextContent" style=
=3D"padding-top: 9px;padding-right: 18px;padding-bottom: 9px;padding-left:=
 18px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 10=
0%;-webkit-text-size-adjust: 100%;color: #606060;font-family: Helvetica;fo=
nt-size: 11px;line-height: 125%;text-align: left;">

                            <em>Copyright =C2=A9 2016 Right Side News=2C A=
ll rights reserved.</em>
<br>
    You are receiving this because you opted in to receive our newsletter
    <br>
    <br>
    <strong>Our mailing address is:</strong>
    <br>
    <div class=3D"vcard"><span class=3D"org fn">Right Side News</span><div=
 class=3D"adr"><div class=3D"street-address">2711 Buford Road=2C Suite 105=
</div><span class=3D"locality">North Chesterfield</span>=2C <span class=3D=
"region">Virginia</span>  <span class=3D"postal-code">23235</span></div><b=
r><a href=3D"http://rightsidenews.us3.list-manage1.com/vcard?u=3D16fae18c4=
307c7f4c291009ac&id=3D12c31c183e" class=3D"hcard-download">Add us to your=
 address book</a></div>
    <br>
    <br>
=09Want to change how you receive these emails?<br>
    You can <a href=3D"http://rightsidenews.us3.list-manage.com/profile?u=
=3D16fae18c4307c7f4c291009ac&id=3D12c31c183e&e=3D84cf9d0f56" style=3D"word-w=
rap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;=
color: #606060;font-weight: normal;text-decoration: underline;">update you=
r preferences</a> or <a href=3D"http://rightsidenews.us3.list-manage2.com/=
unsubscribe?u=3D16fae18c4307c7f4c291009ac&id=3D12c31c183e&e=3D84cf9d0f56&c=
=3Dd530a6546a" style=3D"word-wrap: break-word;-ms-text-size-adjust: 100%;-=
webkit-text-size-adjust: 100%;color: #606060;font-weight: normal;text-deco=
ration: underline;">unsubscribe from this list</a>
    <br>
    <br>
                        </td>
                    </tr>
                </tbody></table>

            </td>
        </tr>
    </tbody>
</table></td>
                                        </tr>
                                    </table>
                                    <!-- // END FOOTER -->
                                </td>
                            </tr>
                        </table>
                        <!-- // END TEMPLATE -->
                    </td>
                </tr>
            </table>
        </center>
    <img src=3D"http://rightsidenews.us3.list-manage.com/track/open.php?u=
=3D16fae18c4307c7f4c291009ac&id=3Dd530a6546a&e=3D84cf9d0f56" height=3D"1"=
 width=3D"1"></body>
</html>
--_----------=_MCPart_1387133383--
