#!/usr/bin/ksh
# CHANGE


NAMES=
NAMES="${NAMES} STDFNAMEIN STDFNAMEOUT STDFNAMEERR "


DN=/dev/null
PF=/tmp/pf${$}

function cleanup {
  rm -f ${PF}
}

trap 'cleanup ; exit 1' 1 2 3 15 16 17

for N in ${NAMES} ; do
  print -- ${N}
done > ${PF}


for F in "${@}" ; do

  if [[ -r "${F}" ]] ; then

      print -u2 -- "${0}: file=${F}"

      if fgrep -f ${PF} ${F} > ${DN} ; then

      ed - $F <<\EOF
	g/STDFNAMEIN/s//STDINFNAME/g
	g/STDFNAMEOUT/s//STDOUTFNAME/g
	g/STDFNAMEERR/s//STDERRFNAME/g
	w
	q
EOF

      fi

  fi

done

cleanup



