#!/usr/bin/ksh
# CHANGE


NAMES=
NAMES="${NAMES} VARERRORFNAME _ERRORFILE"


DN=/dev/null
for F in "${@}" ; do

  if [[ -r "${F}" ]] ; then

    for N in ${NAMES} ; do

      print -u2 -- "${0}: file=${F} str=${N}"

      if fgrep "${N}" ${F} > ${DN} ; then

      ed - $F <<\EOF
	g/VARERRORFNAME/s//VAREFNAME/g
	g/_ERRORFILE/s//_EF/g
	w
	q
EOF

      fi

    done

  fi

done


