execve("testsleep.x", 0xFFBEEC6C, 0xFFBEEC74)  argc = 1
open("/var/ld/ld.config", O_RDONLY)		Err#2 ENOENT
mmap(0x00000000, 8192, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANON, -1, 0) = 0xFF3A0000
open("/usr/add-on/local/lib/S5/libsocket.so.1", O_RDONLY) Err#2 ENOENT
open("/opt/SUNWspro/lib/libsocket.so.1", O_RDONLY) Err#2 ENOENT
open("/usr/dt/lib/libsocket.so.1", O_RDONLY)	Err#2 ENOENT
open("/usr/openwin/lib/libsocket.so.1", O_RDONLY) Err#2 ENOENT
open("/usr/java/lib/libsocket.so.1", O_RDONLY)	Err#2 ENOENT
open("/usr/add-on/X11/lib/libsocket.so.1", O_RDONLY) Err#2 ENOENT
open("/usr/add-on/ncmp/lib/libsocket.so.1", O_RDONLY) Err#2 ENOENT
open("/usr/add-on/gnu/lib/libsocket.so.1", O_RDONLY) Err#2 ENOENT
open("/usr/add-on/local/lib/S5/libsocket.so.1", O_RDONLY) Err#2 ENOENT
open("/usr/add-on/local/lib/libsocket.so.1", O_RDONLY) Err#2 ENOENT
open("/usr/lib/libsocket.so.1", O_RDONLY)	= 3
fstat(3, 0xFFBEE33C)				= 0
mmap(0x00000000, 8192, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xFF390000
mmap(0x00000000, 114688, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xFF370000
mmap(0xFF38A000, 4349, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 40960) = 0xFF38A000
munmap(0xFF37A000, 65536)			= 0
memcntl(0xFF370000, 14440, MC_ADVISE, MADV_WILLNEED, 0, 0) = 0
close(3)					= 0
open("/usr/add-on/local/lib/S5/libnsl.so.1", O_RDONLY) Err#2 ENOENT
open("/opt/SUNWspro/lib/libnsl.so.1", O_RDONLY)	Err#2 ENOENT
open("/usr/dt/lib/libnsl.so.1", O_RDONLY)	Err#2 ENOENT
open("/usr/openwin/lib/libnsl.so.1", O_RDONLY)	Err#2 ENOENT
open("/usr/java/lib/libnsl.so.1", O_RDONLY)	Err#2 ENOENT
open("/usr/add-on/X11/lib/libnsl.so.1", O_RDONLY) Err#2 ENOENT
open("/usr/add-on/ncmp/lib/libnsl.so.1", O_RDONLY) Err#2 ENOENT
open("/usr/add-on/gnu/lib/libnsl.so.1", O_RDONLY) Err#2 ENOENT
open("/usr/add-on/local/lib/S5/libnsl.so.1", O_RDONLY) Err#2 ENOENT
open("/usr/add-on/local/lib/libnsl.so.1", O_RDONLY) Err#2 ENOENT
open("/usr/lib/libnsl.so.1", O_RDONLY)		= 3
fstat(3, 0xFFBEE33C)				= 0
mmap(0xFF390000, 8192, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0xFF390000
mmap(0x00000000, 696320, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xFF280000
mmap(0xFF31A000, 32508, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 565248) = 0xFF31A000
mmap(0xFF322000, 30672, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANON, -1, 0) = 0xFF322000
munmap(0xFF30A000, 65536)			= 0
memcntl(0xFF280000, 81620, MC_ADVISE, MADV_WILLNEED, 0, 0) = 0
close(3)					= 0
open("/usr/add-on/local/lib/S5/libc.so.1", O_RDONLY) Err#2 ENOENT
open("/opt/SUNWspro/lib/libc.so.1", O_RDONLY)	Err#2 ENOENT
open("/usr/dt/lib/libc.so.1", O_RDONLY)		Err#2 ENOENT
open("/usr/openwin/lib/libc.so.1", O_RDONLY)	Err#2 ENOENT
open("/usr/java/lib/libc.so.1", O_RDONLY)	Err#2 ENOENT
open("/usr/add-on/X11/lib/libc.so.1", O_RDONLY)	Err#2 ENOENT
open("/usr/add-on/ncmp/lib/libc.so.1", O_RDONLY) Err#2 ENOENT
open("/usr/add-on/gnu/lib/libc.so.1", O_RDONLY)	Err#2 ENOENT
open("/usr/add-on/local/lib/S5/libc.so.1", O_RDONLY) Err#2 ENOENT
open("/usr/add-on/local/lib/libc.so.1", O_RDONLY) Err#2 ENOENT
open("/usr/lib/libc.so.1", O_RDONLY)		= 3
fstat(3, 0xFFBEE33C)				= 0
mmap(0xFF390000, 8192, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0xFF390000
mmap(0x00000000, 786432, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xFF180000
mmap(0xFF238000, 24720, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 688128) = 0xFF238000
munmap(0xFF228000, 65536)			= 0
memcntl(0xFF180000, 112632, MC_ADVISE, MADV_WILLNEED, 0, 0) = 0
close(3)					= 0
open("/usr/add-on/local/lib/S5/libdl.so.1", O_RDONLY) Err#2 ENOENT
open("/opt/SUNWspro/lib/libdl.so.1", O_RDONLY)	Err#2 ENOENT
open("/usr/dt/lib/libdl.so.1", O_RDONLY)	Err#2 ENOENT
open("/usr/openwin/lib/libdl.so.1", O_RDONLY)	Err#2 ENOENT
open("/usr/java/lib/libdl.so.1", O_RDONLY)	Err#2 ENOENT
open("/usr/add-on/X11/lib/libdl.so.1", O_RDONLY) Err#2 ENOENT
open("/usr/add-on/ncmp/lib/libdl.so.1", O_RDONLY) Err#2 ENOENT
open("/usr/add-on/gnu/lib/libdl.so.1", O_RDONLY) Err#2 ENOENT
open("/usr/lib/libdl.so.1", O_RDONLY)		= 3
fstat(3, 0xFFBEE33C)				= 0
mmap(0xFF390000, 8192, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0xFF390000
close(3)					= 0
open("/usr/add-on/local/lib/S5/libmp.so.2", O_RDONLY) Err#2 ENOENT
open("/opt/SUNWspro/lib/libmp.so.2", O_RDONLY)	Err#2 ENOENT
open("/usr/dt/lib/libmp.so.2", O_RDONLY)	Err#2 ENOENT
open("/usr/openwin/lib/libmp.so.2", O_RDONLY)	Err#2 ENOENT
open("/usr/java/lib/libmp.so.2", O_RDONLY)	Err#2 ENOENT
open("/usr/add-on/X11/lib/libmp.so.2", O_RDONLY) Err#2 ENOENT
open("/usr/add-on/ncmp/lib/libmp.so.2", O_RDONLY) Err#2 ENOENT
open("/usr/add-on/gnu/lib/libmp.so.2", O_RDONLY) Err#2 ENOENT
open("/usr/lib/libmp.so.2", O_RDONLY)		= 3
fstat(3, 0xFFBEE33C)				= 0
mmap(0x00000000, 8192, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xFF360000
mmap(0x00000000, 90112, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xFF340000
mmap(0xFF354000, 865, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 16384) = 0xFF354000
munmap(0xFF344000, 65536)			= 0
memcntl(0xFF340000, 3124, MC_ADVISE, MADV_WILLNEED, 0, 0) = 0
close(3)					= 0
mprotect(0x00010000, 39592, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
open("/usr/platform/SUNW,Ultra-2/lib/libc_psr.so.1", O_RDONLY) = 3
fstat(3, 0xFFBEE1CC)				= 0
mmap(0xFF360000, 8192, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0xFF360000
mmap(0x00000000, 16384, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xFF270000
close(3)					= 0
mprotect(0x00010000, 39592, PROT_READ|PROT_EXEC) = 0
munmap(0xFF360000, 8192)			= 0
write(3, " m a i n :   e r r f d =".., 14)	Err#9 EBADF
getrlimit(RLIMIT_NOFILE, 0xFFBED8A0)		= 0
dup(2)						= 3
fcntl(3, F_GETFL, 0x00000000)			= 8193
fstat64(3, 0xFFBED6C8)				= 0
fcntl(3, F_GETFD, 0x00000000)			= 0
fcntl(3, F_SETFD, 0x00000001)			= 0
fstat64(3, 0xFFBED8A8)				= 0
ioctl(3, TCGETA, 0xFFBED82C)			Err#25 ENOTTY
llseek(3, 0, SEEK_CUR)				= 5863
sysconfig(_CONFIG_PAGESIZE)			= 8192
brk(0x0002A308)					= 0
brk(0x00030308)					= 0
getpid()					= 3846 [3845]
access("/usr/sbin", 4)				= 0
getuid()					= 201 [201]
getuid()					= 201 [201]
getgid()					= 309 [309]
getgid()					= 309 [309]
getuid()					= 201 [201]
open64("/etc/.name_service_door", O_RDONLY)	= 4
fcntl(4, F_SETFD, 0x00000001)			= 0
door_info(4, 0xFF23E7A0)			= 0
door_call(4, 0xFFBECEB0)			= 0
getrlimit(RLIMIT_NOFILE, 0xFFBECE38)		= 0
open64("/etc/udomains", O_RDONLY|O_LARGEFILE)	= 5
fcntl(5, F_GETFD, 0x00000000)			= 0
fcntl(5, F_SETFD, 0x00000001)			= 0
fstat64(5, 0xFFBECE40)				= 0
ioctl(5, TCGETA, 0xFFBECDC4)			Err#25 ENOTTY
llseek(5, 0, SEEK_CUR)				= 0
brk(0x00030308)					= 0
brk(0x00032308)					= 0
read(5, " #   U D O M A I N S   (".., 8192)	= 227
read(5, 0x00030000, 8192)			= 0
close(5)					= 0
uname(0xFFBECF20)				= 1
time()						= 1014257560
alarm(0)					= 0
sigaction(SIGALRM, 0xFFBED860, 0xFFBED910)	= 0
sigfillset(0xFF23E928)				= 0
sigprocmask(SIG_BLOCK, 0xFFBED900, 0xFFBED8F0)	= 0
alarm(10)					= 0
sigsuspend(0xFFBED8E0)		(sleeping...)
    Received signal #14, SIGALRM, in sigsuspend() [caught]
sigsuspend(0xFFBED8E0)				Err#4 EINTR
setcontext(0xFFBED5C8)
alarm(0)					= 0
sigprocmask(SIG_UNBLOCK, 0xFFBED900, 0x00000000) = 0
sigaction(SIGALRM, 0xFFBED860, 0x00000000)	= 0
close(3)					= 0
llseek(0, 0, SEEK_CUR)				= 1942033
_exit(0)
