.\"_
.TH INCIMA 1 1995-03-01 LOCAL
.SH NAME
incima \- graphics filter program for AT&T DWB documents
.SH SYNOPSIS
.BR incima
.RB [ input_file ]
.OP -v "" ] [
.OP -V "" ] [
.OP -D "" ] [
.\"_
.SH DESCRIPTION
.\"_
.SS Introduction
.PP
This program is used much like most of the rest of the DWB filters
should be used.  The source like DWB document should be piped through this
filter so that graphics inclusion directives can be expanded.
This filter expands the graphics inclusion directive named '\f(CWBG\fP'.
.\"_
.SS Options
.IP "-v" 10
This option allow for verbose output during execution.
.IP "-V" 10
The \fB-V\fP causes the program to print its version number and
then to exit.
.IP "-D" 10
The \fB-D\fP option turns on debugging of the program itself.
This is not normally needed by regular users but instead was used by the
program developer.
.\"_
.SS Execution
This command is usually executed by the \fBprtfmt\fP command when
preparing AT&T DWB formatted documents.  Note that only the \fBprtfmt\fP
program used by the Starbase project is smart enough to call \fBincima\fP
when it is needed.  Other \fBprtfmt\fP programs like the UNISON version,
do not automatically call \fBincima\fP at all.
Typical execution of this filter program in a pipeline might be :
.EX
cat source.mm | incima | troff -mm -Tpost | dpost > out.ps
.EE
.PP
If an argument is given on the command invocation line other than
a key letter option, it is taken to be an input file to be filtered.
When this argument is not supplied, the program simply reads standard
input.
.\"_
.SH EXAMPLES
.PP
.IP \(rh 5
To filter out graphics include requests only :
.EX
incinc file > outfile
.EE
.IP \(rh 5
To filter out graphics requests and send the output to a printer,
one can use :
.EX
incima infile.mm | /usr/add-on/unison/bin/prtfmt -d di0
.EE
.IP \(rh 5
To print a file containing graphics include requests using the
Starbase print command :
.EX
prtfmt inputfile
.EE
.IP \(rh 5
To print a file containing grapgics inclusion requests to a specified
Starbase printer :
.EX
prtfmt file -d di0
.EE
.\"_
.SH SEE ALSO
prt(1), prtfmt(1), prtmin(1)
.\"_
.SH PATH TO
This program is currently located in 
\fC/usr/add-on/local/bin\fP on most systems.
.\"_
.SH WARNINGS
Be careful to put a space between all option key letters and the associated
key letter parameter values.
.\"_
