#!/usr/bin/ksh
# RUNIT-RVV


RF_MKTROFF=true
RF_MKPDF=true
VER=rvv
LAN=spanish

TT=bible_${VER}

SETOPTS=
SETOPTS="${SETOPTS} -ibz -tc "
SETOPTS="${SETOPTS} -ndb ${LAN}"
SETOPTS="${SETOPTS} -wdb ${LAN} "
SETOPTS="${SETOPTS} -cover biblecover_${VER}.eps "
SETOPTS="${SETOPTS} -front biblefront_${VER}.mm "

PO="0.75i"
PW="7.0i"

ENC=latin1

bibleset.x ${SETOPTS} ${TT}.txt > ${TT}.mm

troff -TLatin1 -rO"${PO}" -rW"${PW}" -mm ${TT}.mm > ${TT}.troff

if ${RF_MKTROFF} ; then
  troff -TLatin1 -rO"${PO}" -rW"${PW}" -mm -mpictures ${TT}.mm > ${TT}.troff
  if ${RF_MKPDF} ; then
    dpost -T${ENC} -y -0.1 > ${TT}.ps < ${TT}.troff
    if [[ -s "${TT}.ps" ]] ; then
      ps2pdf ${TT}.ps ${TT}.pdf 
    fi
  fi
fi




