From gmail.com!coldspacemachine+caf_=dam=rightcore.com Tue Mar 26 14:00:36 EDT 2013 -0400
return-path:  <coldspacemachine+caf_=dam=rightcore.com@gmail.com>
received: from mail-ia0-f169.google.com (mail-ia0-f169.google.com 
	[209.85.210.169])
 by mail.rightcore.com (RCMAILER) with ESMTP id 13735233FD
 for <dam@rightcore.com>; Tue, 26 Mar 2013 14:00:35 -0400 (EDT)
received: by mail-ia0-f169.google.com with SMTP id j5so6685370iaf.14
 for <dam@rightcore.com>; Tue, 26 Mar 2013 11:00:36 -0700 (PDT)
received: by 10.50.156.225 with SMTP id wh1csp28388igb;
 Tue, 26 Mar 2013 11:00:36 -0700 (PDT)
received: from acmsmtp01.acm.org (ACMSMTP01.acm.org. [64.238.147.78])
 by mx.google.com with ESMTPS id s12si5182029qct.176.2013.03.26.11.00.35
 (version=TLSv1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
 Tue, 26 Mar 2013 11:00:35 -0700 (PDT)
received: from psmtp.com
 by acmsmtp01.acm.org (ACM Email Forwarding Service) with SMTP (SSL) id 
	LVA87530
 for <morano@acm.org>; Tue, 26 Mar 2013 14:00:30 -0400
received: from mail-vb0-f43.google.com ([209.85.212.43]) (using TLSv1) by 
	na3sys009amx226.postini.com ([74.125.148.10]) with SMTP;
 Tue, 26 Mar 2013 11:00:31 PDT
received: by mail-vb0-f43.google.com with SMTP id fs19so4753493vbb.30
 for <morano@acm.org>; Tue, 26 Mar 2013 11:00:29 -0700 (PDT)
received: by 10.221.13.18 with HTTP; Tue, 26 Mar 2013 11:00:29 -0700 (PDT)
content-length: 1206                
message-id: <CANXuW=Ninu2qo_M=6PKxmi-r+ovuwraD37mS2vMSzGQe5fCiaw@mail.gmail.com>
x-original-to: dam@rightcore.com
delivered-to: dam@rightcore.com
delivered-to: coldspacemachine@gmail.com
x-received: by 10.50.87.2 with SMTP id t2mr2047227igz.19.1364320836893;
 Tue, 26 Mar 2013 11:00:36 -0700 (PDT)
x-received: by 10.229.102.101 with SMTP id 
	f37mr3347094qco.112.1364320835502;
 Tue, 26 Mar 2013 11:00:35 -0700 (PDT)
x-received: by 10.52.177.161 with SMTP id cr1mr17170310vdc.64.1364320829870;
 Tue, 26 Mar 2013 11:00:29 -0700 (PDT)
x-forwarded-to: dam@rightcore.com
x-forwarded-for: coldspacemachine@gmail.com dam@rightcore.com
received-spf: pass (google.com: domain of 
	SRS0+e738f4f8bdb065d5=NO=gmail.com=dell.morano@srs.acm.org 
	designates 64.238.147.78 as permitted sender) 
	client-ip=64.238.147.78;
authentication-results: mx.google.com;
 spf=pass (google.com: domain of 
	SRS0+e738f4f8bdb065d5=NO=gmail.com=dell.morano@srs.acm.org 
	designates 64.238.147.78 as permitted sender) 
	smtp.mail=SRS0+e738f4f8bdb065d5=NO=gmail.com=dell.morano@srs.acm.org;
 dkim=pass header.i=@gmail.com
dkim-signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
 d=gmail.com; s=20120113;
 h=mime-version:x-received:date:message-id:subject:from:to:cc
 :content-type;
 bh=LP96HrDZyguZ32vMZFOIsKjHTzZSGtA7VbCeArDY4ok=;
 b=XozKsaA6CvG0MAGyP9+sz4N5WCkNlDCBZBlDFr5Ug0VBSwcvwkHfAYq2ewMnl/47wv
 g7M4F9e1EbGpRfHzIhh3Jxb8iiBD7zc1OjeKFBlReYruKZX3fj9bc6+f4/DXguDJk7Sp
 kOAFCgN0djmE2+gl0p3Pmzd0VKD01RjichaSlUv+urYLE7HfM1waAtRC4G8ef6pFJRyB
 ZPr17QuC0vJksLs11alFaFyn+3MGIg0CVdedaUW4fZkQ4t3jCFxiOmbTUcPzyMRYbITv
 uTt12Uxbg1Gr/HjjGzEdoIG4a1Pw4DUzKwAKZLz4MFJm9MOwBkdPfZjwAwIb9ar8jzdR
 Udaw==
mime-version: 1.0
content-type: multipart/alternative; boundary=20cf3071ceac6c9eb904d8d7b2e3
x-pstn-levels: (S:99.90000/99.90000 CV:99.9000 FC:95.5390 LC:95.5390 
	R:95.9108 P:95.9108 M:97.0282 C:98.6951 )
x-pstn-dkim: 1 skipped:not-enabled
x-pstn-settings: 3 (1.0000:0.0100) s cv GT3 gt2 gt1
x-pstn-addresses: from <dell.morano@gmail.com> forward (user good) 
	[3193/157]
status: 
From:  Dell Morano <dell.morano@gmail.com>
To:  "David Morano:ACM" <morano@acm.org>
to: dam (David Morano)
cc:  Dell Morano <dell.morano@gmail.com>
Date: Tue, 26 Mar 2013 14:00:29 -0400
Subject: it's late to go

--20cf3071ceac6c9eb904d8d7b2e3
Content-Type: text/plain; charset=ISO-8859-1

Dave,

It's really too late to go out to Danvers to Ira Toyota...but I'm upset
bout some thing on my car....seems, every time I leave my car over night at
a garage....they seem to strip various parts...I feel as if there is an
part missing from the front end of my car and I wanna know what goes
there....I see all holes and know that a some kind of a part goes
there...but I dunno what ..so I'm headed for Ira right now...and I know the
traffice will be heavy...
mom

--20cf3071ceac6c9eb904d8d7b2e3
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

Dave,<br><br>It&#39;s really too late to go out to Danvers to Ira Toyota...=
but I&#39;m upset bout some thing on my car....seems, every time I leave my=
 car over night at a garage....they seem to strip various parts...I feel as=
 if there is an part missing from the front end of my car and I wanna know =
what goes there....I see all holes and know that a some kind of a part goes=
 there...but I dunno what ..so I&#39;m headed for Ira right now...and I kno=
w the traffice will be heavy...<br>
mom<br>

--20cf3071ceac6c9eb904d8d7b2e3--
