From karen.hart@nbc.com Tue Sep 25 15:54:43 EDT 2001 
Return-Path: <karen.hart@nbc.com>
Received: from sendmail2.computer.org (sendmail2.computer.org [206.99.235.25])
	by leviathan.ele.uri.edu (8.11.2/8.11.2) with ESMTP id f8PJr6207657
	for <morano@ele.uri.edu>; Tue, 25 Sep 2001 15:53:10 -0400 (EDT)
Received: from ext-ch1gw-1.online-age.net (ext-ch1gw-1.online-age.net [216.34.191.35])
	by sendmail2.computer.org (Build 101 8.9.3/NT-8.9.3) with ESMTP id PAA07554
	for <morano@computer.org>; Tue, 25 Sep 2001 15:55:02 -0400
Received: from int-ch1gw-5.online-age.net (int-chi1-log [3.159.232.69])
	by ext-ch1gw-1.online-age.net (8.9.3+Sun/8.9.1/990426-RLH) with ESMTP id PAA18014;
	Tue, 25 Sep 2001 15:51:21 -0400 (EDT)
Received: from MAILER-DAEMONewman.nbc.COM (localhost [127.0.0.1])
	by int-ch1gw-5.online-age.net (8.9.3+Sun/8.9.1/990426-RLH) with ESMTP id PAA17598;
	Tue, 25 Sep 2001 15:51:15 -0400 (EDT)
Received: from ny07nbcge.nbc.com (ny07nbcge.nbc.com [3.23.16.26]) by MAILER-DAEMONewman.nbc.COM (8.9.1b+Sun/8.6.12) with ESMTP id PAA16745; Tue, 25 Sep 2001 15:50:35 -0400 (EDT)
Received: by ny07nbcge.nbc.com with Internet Mail Service (5.5.2653.19)
	id <TLML8L7R>; Tue, 25 Sep 2001 15:50:48 -0400
Message-ID: <57CFBDB9446DD2118D830001FAF8DB92054651C2@ny06nbcge.nbc.com>
From: "Hart, Karen (NBC)" <karen.hart@nbc.com>
To: "'Tsang, David'" <David.Tsang@jacobs.com>,
   "'Alec Taylor (E-mail)'"
	 <tayloral@nima.mil>,
   "'Alice Paar (E-mail)'" <acpaar@yahoo.com>,
   "'Betty Jennings (E-mail)'" <ejennings@bics.bwh.harvard.edu>,
   "'Carl Donath (E-mail)'" <carl@donath.org>,
   "'Charles Schatz (E-mail)'"
	 <cfschatz@a-znet.com>,
   "'Currans (E-mail)'" <acurren1@twcny.rr.com>,
   "'Dan & MinJi (E-mail)'" <kimdk@bigfoot.com>,
   "'Dave Morano (E-mail)'"
	 <morano@computer.org>,
   "'David Martin (E-mail)'" <davermartin@yahoo.com>,
   "'Diane Harrington (E-mail)'" <ladydicst@juno.com>,
   "'Elizabeth Webb (E-mail)'" <webbclutch@hotmail.com>,
   "'Ereling Nordmo (E-mail)'" <erelingn@rocketmail.com>,
   "'Eric Johnson (E-mail)'" <ericjj9532@yahoo.com>,
   "'Jody Adams (E-mail)'"
	 <jodytadams@yahoo.com>,
   "'Julie Sonjara (E-mail)'"
	 <Julie_Sonjara@lotus.com>,
   "Hart, Karen (NBC)" <karen.hart@nbc.com>,
   "'Lisa Pierce (E-mail)'" <ldpierce@yahoo.com>,
   "'Marilyn Beaton (E-mail)'" <marilyn.beaton@knet.on.ca>,
   "'Mark England (E-mail)'" <dme101@ptdprolog.net>,
   "'Michele Alesci (E-mail)'" <mburgwin@crossbridgefinancial.com>,
   "'Paul Beaulieu (E-mail)'" <pbeaulieu@rational.com>,
   "'Nate Iamaio (E-mail)'" <npiamaio@twcny.rr.com>,
   "'Ruth Comanda (E-mail)'" <rcomanda@rockbridge.org>,
   "'Tom Fisher(work) (E-mail)'" <TFisher@Shipley.com>,
   "Alastair Halliday (E-mail)" <alastair@vicoms.com>,
   "Lily Koo (E-mail)"
	 <lilyyk@mit.edu>,
   "Dave Natalizia (E-mail)" <dn@iname.com>,
   "'bonnieabrams@aol.com'" <bonnieabrams@aol.com>,
   "'JillDB@worldnet.att.net'" <JillDB@worldnet.att.net>,
   "'Boehmcke, Matt[matt.boehmcke@csfb.com]'" <matt.boehmcke@csfb.com>,
   "'cjacobs@tiffany.com'"
	 <cjacobs@tiffany.com>,
   "'jonathan@jwduncan.com'" <jonathan@jwduncan.com>,
   "'joan_fiore@hotmail.com'" <joan_fiore@hotmail.com>,
   "'ginafrassetto@hotmail.com'" <ginafrassetto@hotmail.com>,
   "'cgay@jackpot.com'" <cgay@jackpot.com>,
   "'jamigrich@yahoo.com'"
	 <jamigrich@yahoo.com>,
   "'susan.luce@lcra.org'" <susan.luce@lcra.org>,
   "'Meghan_Duttenhofer@timeinc.com'" <Meghan_Duttenhofer@timeinc.com>,
   "'Morello@bessemer.com'" <Morello@bessemer.com>,
   "'Norgrk1@aol.com'"
	 <Norgrk1@aol.com>, "'parkjv@bc.edu'" <parkjv@bc.edu>,
   "'wmrstepp@aol.com'" <wmrstepp@aol.com>,
   "'Aimeer@asisolutions.com'"
	 <Aimeer@asisolutions.com>,
   "'psaghir@hotmail.com'" <psaghir@hotmail.com>,
   "'Abbey.Sidebottom@ci.minneapolis.mn.us'"
	 <Abbey.Sidebottom@ci.minneapolis.mn.us>,
   "'Aheath0417@aol.com'"
	 <Aheath0417@aol.com>, alexandra.galston@gs.com,
   dawn.garnett@mtvi.com, Suzy Rechtermann <srechtermann@hearst.com>,
   "'Alison_Reichert@liz.com'"
	 <Alison_Reichert@liz.com>,
   "'CATowers@aol.com'" <CATowers@aol.com>,
   "'hayes_samanth92@hotmail.com'" <hayes_samanth92@hotmail.com>,
   "'jarbour@nhl.com'" <jarbour@nhl.com>,
   "'phamil8153@aol.com'"
	 <phamil8153@aol.com>,
   "'Meredith.Glenn@publicis-usa.com'"
	 <Meredith.Glenn@publicis-usa.com>,
   "'cathygordon2001@yahoo.com'"
	 <cathygordon2001@yahoo.com>,
   "'jen.smith@olgilvy.com'"
	 <jen.smith@olgilvy.com>,
   "'jwalton@hearst.com'" <jwalton@hearst.com>,
   "'jody@jackpot.com'" <jody@jackpot.com>,
   "'mikemcneilly@newsoft.com'"
	 <mikemcneilly@newsoft.com>,
   "'kendra.petersen@turner.com'"
	 <kendra.petersen@turner.com>,
   "'Karen Kuo'" <karenkuo@pacbell.net>, thadley1@uswest.net,
   "'chelleyrachel@yahoo.com'"
	 <chelleyrachel@yahoo.com>,
   "'iversenk@mskcc.org'" <iversenk@mskcc.org>
Subject: New job
Date: Tue, 25 Sep 2001 15:51:07 -0400
Return-Receipt-To: "Hart, Karen (NBC)" <karen.hart@nbc.com>
X-Mailer: Internet Mail Service (5.5.2653.19)
Content-Length: 387

Friends,

After this Friday, I'll be leaving NBC to pursue a new and exciting
opportunity!  Effective Monday, Oct 1 this email address will be inactive.
You can reach me on my personal account at hartk1210@yahoo.com or at my new
account karen@panyc.org


Love each other,
Karen


	Because e-mail can be altered electronically, 
	the integrity of this communication cannot be guaranteed.

