From c.adjemian@att.net Wed Aug 14 13:18:40 EDT 2002 
received:
	by rca.rightcore.com
	; 14 Aug 2002 13:21:06 -0400 (EDT)
Return-Path: <c.adjemian@att.net>
Received: from clement.computer.org (clement.computer.org [63.84.220.160])
	by leviathan.ele.uri.edu (8.12.2/8.12.2) with ESMTP id g7EHGOvi023156
	for <morano@ele.uri.edu>; Wed, 14 Aug 2002 13:16:25 -0400 (EDT)
Received: from mtiwmhc23.worldnet.att.net (mtiwmhc23.worldnet.att.net [204.127.131.48])
	by clement.computer.org (Switch-2.1.1/Switch-2.1.1) with ESMTP id U7EH05TN26375
	for <morano@computer.org>; Wed, 14 Aug 2002 10:05:29 -0700
Received: from Pastorcomputer ([12.91.11.39]) by mtiwmhc23.worldnet.att.net
          (InterMail vM.4.01.03.27 201-229-121-127-20010626) with SMTP
          id <20020814170503.UFMQ7441.mtiwmhc23.worldnet.att.net@Pastorcomputer>;
          Wed, 14 Aug 2002 17:05:03 +0000
Message-ID: <00d001c243b4$b3ca2960$d30a5b0c@Pastorcomputer>
From: "Christian Adjemian" <c.adjemian@att.net>
To: "Self" <c.adjemian@worldnet.att.net>
Cc: "Verne & Trudy Rosenberger" <psalmhim@gis.net>,
   "Tom home Fisher" <tafisher@concentric.net>,
   "Susan Burger" <bookworm430@hotmail.com>,
   "Stephanie Ruth Adjemian" <tefferruth@worldnet.att.net>,
   "Self" <c.adjemian@worldnet.att.net>,
   "Scott K. Greiner" <scottkg@mindspring.com>,
   "Ruth Bockoven" <pixiestix538@aol.com>,
   "Roberta Van Vlack" <roberta@uwalumni.com>,
   "Rachel Adjemian" <rachelariela@att.net>,
   "Peter & Christine Bockoven" <pcbock@aol.com>,
   "Pam Chilton" <pam@chiltonfamily.org>,
   "Nate Iamaio" <npiamaio@twcny.rr.com>,
   "Nadia Swartz" <bohemiansunshine@hotmail.com>,
   "Minji Kim" <mkim@brandeis.edu>, "Maureen Wright" <mrwright@geneva.edu>,
   "Matthew J. Van Vlack" <vanvlack@nber.org>, "Lisa Pierce" <ldpierce@bu.edu>,
   "Lily Koo" <lilyyk@mit.edu>, "Laura Moberg" <lmoberg@wso.williams.edu>,
   "Laura Adjemian" <ladjemian@att.net>, "Larry Cecchi" <BUSTERJOE@afo.net>,
   "Kyle Dugdale" <gsd99kad@gsd.harvard.edu>,
   "Kevin Conklin" <conklink@questdiagnostics.com>,
   "Ken Chilton" <ken@chiltonfamily.org>, "Karen Iamaio" <karen@iamaio.com>,
   "Julie Sonjara" <Julie_Sonjara@lotus.com>,
   "=?iso-8859-1?Q?Jos=E9_M._Gonz=E1lez?=" <jmgonzal@fas.harvard.edu>,
   "Jonathan Adjemian" <jadjemian@hotmail.com>,
   "Jody Adams" <jodytadams@yahoo.com>, "Jeff Hwang" <hwang82@yahoo.com>,
   "Jeff Henrikson" <jehenrik@alum.mit.edu>,
   "Jason Crawford" <jcrawfor@fas.harvard.edu>,
   "Janet Millican" <jemillican@aol.com>, "Deryl Robson" <deryljcr@aol.com>,
   "David Tsang" <dtsang@Vollmer.com>, "David Robson" <dcrobson@aol.com>,
   "David Morano" <morano@computer.org>, "Dan Kim" <danandminji@yahoo.com>,
   "Christopher W Bogosh" <solafidecoramdeo@juno.com>,
   "Chris & Carol Wright" <wrightc@gis.net>,
   "Charles & Betty Burger" <housiezoo@earthlink.net>,
   "Brenan & Hilary McCarragher" <brenan@attbi.com>,
   "Bonnie Chan" <gsd98bac@hotmail.com>,
   "Betty Jennings" <ejennings@partners.org>,
   "Betty Burger" <Bettyburger@earthlink.net>,
   "Anna Adjemian" <grumpyelf@att.net>, "Alice Paar" <acpaar@yahoo.com>,
   "Alastair Halliday" <alastair@vicoms.com>,
   "Adrian Wright" <atwright@geneva.edu>,
   "Jan-Hermen Dannenberg" <j.dannenberg@nki.nl>
Subject: Fw: Fall courses - Granite State School
Date: Wed, 14 Aug 2002 13:04:11 -0400
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="----=_NextPart_000_00CD_01C24393.15560E50"
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 6.00.2600.0000
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2600.0000
Content-Length: 7824

This is a multi-part message in MIME format.

------=_NextPart_000_00CD_01C24393.15560E50
Content-Type: text/plain;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable


----- Original Message -----=20
From: Gregory Reynolds=20
Sent: Tuesday, August 13, 2002 11:03 PM
Subject: Fall courses - Granite State School



Dear friends:

Once again we have one of the finest Old Testament professors in the =
English-speaking world, Dr. Meredith G. Kline, teaching at the Granite =
State School of Theology and Missions. We have reduced the credit cost =
of tuition by 33% in the hope that more students will take the course =
for credit. [A list of schools that have already recognized our credits =
is available]
On September 12 [Each Thursday for ten weeks, September 12 through =
November 14, 7:00 to 9:30 PM] Dr. Meredith G. Kline, renowned Old =
Testament scholar, will teach a course titled "Covenant-Kingdom =
Foundations." The course will explore the foundations and covenantal =
structure of the history of the Kingdom of God as developed from the =
exegesis of Genesis. He will use his own classic book, Kingdom Prologue, =
as his text. Many Christians do not have the tools to read the Bible as =
a whole because they do not understand the covenant structure of =
Scripture. Dr Kline is skilled at opening the riches of God's saving =
grace in the Old Testament, and indeed the entire Bible.=20

Dr. Kline has been teaching since 1948. He has been a professor at =
Gordon-Conwell Theological Seminary; Westminster Theological Seminary; =
Claremont School of Theology; Reformed Theological Seminary; and =
Westminster Theological Seminary in California. He is the author of six =
books and a host of journal articles and reviews.

Students may register on Thursday, September 12 at 6:30 PM. They may =
also pre-register by contacting our registrar: Mr. David King at 68 =
Overledge Drive, Derry, NH  03038; telephone: 603.432.1489; email: =
kking15469@attbi.net. Cost: $150.00 [3 credits] $75.00 [audit].

I hope you will take advantage of this unique opportunity.
=20
Yours in the Lamb,
=20
Greg Reynolds.

___________________________

Dr Gregory Reynolds
Amoskeag Presbyterian Church
95 Brook Street
Manchester, NH  03104
603.644.8435
reynolds.1@opc.org
www.amoskeagchurch.org

------=_NextPart_000_00CD_01C24393.15560E50
Content-Type: text/html;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML xmlns:o =3D "urn:schemas-microsoft-com:office:office"><HEAD>
<META http-equiv=3DContent-Type content=3D"text/html; =
charset=3Diso-8859-1">
<META content=3D"MSHTML 6.00.2716.2200" name=3DGENERATOR>
<STYLE></STYLE>
</HEAD>
<BODY bgColor=3D#ffffff>
<DIV><FONT face=3DVerdana size=3D2></FONT>&nbsp;</DIV>
<DIV style=3D"FONT: 10pt arial">----- Original Message -----=20
<DIV style=3D"BACKGROUND: #e4e4e4; font-color: black"><B>From:</B> <A=20
title=3Dreynolds.1@opc.org href=3D"mailto:reynolds.1@opc.org">Gregory =
Reynolds</A>=20
</DIV>
<DIV><B>Sent:</B> Tuesday, August 13, 2002 11:03 PM</DIV>
<DIV><B>Subject:</B> Fall courses - Granite State School</DIV></DIV>
<DIV><BR></DIV>
<DIV><FONT face=3DArial size=3D2></FONT>&nbsp;</DIV><FONT face=3DArial =
size=3D2>
<DIV>
<DIV><FONT face=3DArial size=3D2>Dear friends:</FONT></DIV>
<DIV><FONT face=3DArial size=3D2></FONT>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>Once again we have one of the finest =
Old Testament=20
professors in the English-speaking world, Dr. Meredith G. =
Kline,&nbsp;teaching=20
at the Granite State School of Theology and Missions. We have reduced =
the credit=20
cost of tuition by 33% in the hope that more students will take the =
course for=20
credit. [A list of schools that have already recognized our credits is=20
available]</FONT></DIV>
<P class=3DMsoNormal><FONT face=3DArial size=3D2>On September 12 [Each =
Thursday for=20
ten weeks, September 12 through November 14, 7:00 to 9:30 PM] Dr. =
Meredith G.=20
Kline, renowned Old Testament scholar, will teach a course titled=20
=93Covenant-Kingdom Foundations.=94 The course will explore the =
foundations and=20
covenantal structure of the history of the Kingdom of God as developed =
from the=20
exegesis of Genesis. He will use his own classic book, <I=20
style=3D"mso-bidi-font-style: normal">Kingdom Prologue</I>, as his =
text<I=20
style=3D"mso-bidi-font-style: normal">.</I> Many Christians do not have =
the tools=20
to read the Bible as a whole because they do not understand the covenant =

structure of Scripture. Dr Kline is skilled at opening the riches of =
God=92s=20
saving grace in the Old Testament, and indeed the entire Bible. =
</FONT></P>
<DIV class=3DMsoNormal><SPAN=20
style=3D"FONT-SIZE: 12pt; FONT-FAMILY: 'Times New Roman'; =
mso-bidi-font-size: 10.0pt; mso-fareast-font-family: 'Times New Roman'; =
mso-ansi-language: EN-US; mso-fareast-language: EN-US; =
mso-bidi-language: AR-SA"><FONT=20
face=3DArial size=3D2>Dr. Kline has been teaching since 1948. He has =
been a=20
professor at Gordon-Conwell Theological Seminary; Westminster =
Theological=20
Seminary; Claremont School of Theology; Reformed Theological Seminary; =
and=20
Westminster Theological Seminary in California. He is the author of six =
books=20
and a host of journal articles and reviews.</FONT></SPAN></DIV>
<DIV><SPAN=20
style=3D"FONT-SIZE: 12pt; FONT-FAMILY: 'Times New Roman'; =
mso-bidi-font-size: 10.0pt; mso-fareast-font-family: 'Times New Roman'; =
mso-ansi-language: EN-US; mso-fareast-language: EN-US; =
mso-bidi-language: AR-SA"><FONT=20
face=3DArial size=3D2></FONT></SPAN>&nbsp;</DIV>
<DIV><SPAN=20
style=3D"FONT-SIZE: 12pt; FONT-FAMILY: 'Times New Roman'; =
mso-bidi-font-size: 10.0pt; mso-fareast-font-family: 'Times New Roman'; =
mso-ansi-language: EN-US; mso-fareast-language: EN-US; =
mso-bidi-language: AR-SA"><FONT=20
face=3DArial size=3D2>Students may register on Thursday, September 12 at =
6:30 PM.=20
They may also pre-register by contacting our registrar: Mr. David King =
at 68=20
Overledge Drive, Derry, NH<SPAN style=3D"mso-spacerun: yes">&nbsp; =
</SPAN>03038;=20
telephone: 603.432.1489; email: <SPAN class=3DMsoHyperlink><SPAN=20
style=3D"COLOR: blue"><U><A=20
href=3D"mailto:kking15469@attbi.net">kking15469@attbi.net</A></U></SPAN><=
/SPAN>.=20
Cost: $150.00 [3 credits] $75.00 [audit].</FONT></DIV>
<DIV><SPAN=20
style=3D"FONT-WEIGHT: normal; FONT-SIZE: 12pt; FONT-FAMILY: 'Times New =
Roman'; mso-bidi-font-size: 10.0pt"><FONT=20
face=3DArial><FONT size=3D2></FONT></FONT></SPAN>&nbsp;</DIV>
<DIV><SPAN=20
style=3D"FONT-WEIGHT: normal; FONT-SIZE: 12pt; FONT-FAMILY: 'Times New =
Roman'; mso-bidi-font-size: 10.0pt"><FONT=20
face=3DArial><FONT size=3D2>I hope you will take advantage of this =
unique=20
opportunity.<o:p></o:p></FONT></FONT></SPAN></DIV>
<DIV class=3DMsoHeader style=3D"tab-stops: .5in"><FONT =
face=3DArial><FONT=20
size=3D2>&nbsp;<o:p></o:p></FONT></FONT></DIV>
<DIV class=3DMsoNormal><FONT face=3DArial size=3D2>Yours in the=20
Lamb,</FONT></DIV></SPAN>
<DIV class=3DMsoNormal><SPAN=20
style=3D"FONT-SIZE: 8pt; mso-bidi-font-size: 10.0pt"><FONT =
face=3DArial><FONT=20
size=3D2>&nbsp;<o:p></o:p></FONT></FONT></SPAN></DIV>
<DIV><SPAN=20
style=3D"FONT-WEIGHT: normal; FONT-SIZE: 12pt; mso-bidi-font-size: =
10.0pt; mso-bidi-font-weight: bold"><FONT=20
face=3DArial><FONT size=3D2>Greg=20
Reynolds.<o:p></o:p></FONT></FONT></SPAN></DIV><BR>______________________=
_____</DIV>
<DIV>&nbsp;</DIV>
<DIV>Dr Gregory Reynolds<BR>Amoskeag Presbyterian Church<BR>95 Brook=20
Street<BR>Manchester, NH&nbsp; 03104<BR>603.644.8435<BR><A=20
href=3D"mailto:reynolds.1@opc.org">reynolds.1@opc.org</A><BR><A=20
href=3D"http://www.amoskeagchurch.org">www.amoskeagchurch.org</A></FONT><=
/DIV></BODY></HTML>

------=_NextPart_000_00CD_01C24393.15560E50--



