from:    	PCS_administrator <mtgbcs!pcs>
to:      	group : mtgbcs ! "dam here" ( this is a comment )
	,another (comment another), person ; ( outer ), 
	(front here) mgroup : ~dam,other (here sub ),
	third : four1, four2 (person) ; (person) 
	 ; ( again ), 
	~final, _list,
	here :; (here comment )
subject:	test email/posting 2
date:           02 Dec 93 12:26:33 PST
reply-to:	other@person
to:		dam

This is a test.  This is a test of the emergency email/posting
system.  This is only a test.  This test has been devised
as a means of testing email or bulletin board related operations.
If this had been an actual emergency, you would have been instructed
as to where to send email (for testing purposes !).
This concludes this test of the emergency email/posting system.

From this time forward we will see

PCS Administrator

