From gmail.com!coldspacemachine+caf_=dam=rightcore.com Tue Feb 17 17:41:22 USEST 2015 -0500
return-path:  <coldspacemachine+caf_=dam=rightcore.com@gmail.com>
received: from mail-ig0-f172.google.com (mail-ig0-f172.google.com 
	[209.85.213.172])
 by mail.rightcore.com (RCMAILER) with ESMTP id DA41E2EF03
 for <dam@rightcore.com>; Tue, 17 Feb 2015 17:41:21 -0500 (USEST)
received: by mail-ig0-f172.google.com with SMTP id l13so32892459iga.5
 for <dam@rightcore.com>; Tue, 17 Feb 2015 14:41:22 -0800 (PST)
received: by 10.50.0.33 with SMTP id 1csp2436977igb;
 Tue, 17 Feb 2015 14:41:20 -0800 (PST)
received: from mail-lb0-f177.google.com (mail-lb0-f177.google.com. 
	[209.85.217.177])
 by mx.google.com with ESMTPS id ba11si11438029lab.114.2015.02.17.14.41.19
 for <coldspacemachine@gmail.com>
 (version=TLSv1.2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
 Tue, 17 Feb 2015 14:41:19 -0800 (PST)
received: by mail-lb0-f177.google.com with SMTP id z12so7314597lbi.11
 for <coldspacemachine@gmail.com>; Tue, 17 Feb 2015 14:41:19 -0800 (PST)
received: by 10.112.13.74 with SMTP id f10csp2447005lbc;
 Tue, 17 Feb 2015 14:41:18 -0800 (PST)
received: from vms173023pub.verizon.net (vms173023pub.verizon.net. 
	[206.46.173.23])
 by mx.google.com with ESMTPS id z63si1290079oig.91.2015.02.17.14.41.16
 for <morano@ieee.org>
 (version=TLSv1 cipher=RC4-SHA bits=128/128);
 Tue, 17 Feb 2015 14:41:17 -0800 (PST)
received: from Joe-Meszaross-Mac-mini.local ([71.174.29.23])
 by vms173023.mailsrvcs.net
 (Oracle Communications Messaging Server 7.0.5.32.0 64bit (built Jul 16 
	2014))
 with ESMTPA id <0NJX00HPVTOLP740@vms173023.mailsrvcs.net> for 
	morano@ieee.org;
 Tue, 17 Feb 2015 16:41:10 -0600 (CST)
content-length: 969                 
message-id: <54E3C384.4060202@verizon.net>
x-original-to: dam@rightcore.com
delivered-to: dam@rightcore.com
delivered-to: coldspacemachine@gmail.com
delivered-to: morano@ieee.org
x-received: by 10.42.226.5 with SMTP id iu5mr38449023icb.0.1424212881926;
 Tue, 17 Feb 2015 14:41:21 -0800 (PST)
x-received: by 10.152.87.50 with SMTP id u18mr30905175laz.82.1424212879807;
 Tue, 17 Feb 2015 14:41:19 -0800 (PST)
x-received: by 10.112.139.136 with SMTP id 
	qy8mr29602131lbb.38.1424212879084;
 Tue, 17 Feb 2015 14:41:19 -0800 (PST)
x-received: by 10.182.144.229 with SMTP id 
	sp5mr19661262obb.14.1424212877518;
 Tue, 17 Feb 2015 14:41:17 -0800 (PST)
x-forwarded-to: dam@rightcore.com
x-forwarded-to: coldspacemachine@gmail.com
x-forwarded-for: coldspacemachine@gmail.com dam@rightcore.com
received-spf: pass (google.com: domain of 
	morano+caf_=coldspacemachine=gmail.com@ieee.org designates 
	209.85.217.177 as permitted sender) client-ip=209.85.217.177;
received-spf: pass (google.com: domain of joe.meszaros@verizon.net 
	designates 206.46.173.23 as permitted sender) 
	client-ip=206.46.173.23;
authentication-results: mx.google.com;
 spf=pass (google.com: domain of 
	morano+caf_=coldspacemachine=gmail.com@ieee.org designates 
	209.85.217.177 as permitted sender) 
	smtp.mail=morano+caf_=coldspacemachine=gmail.com@ieee.org
x-google-dkim-signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
 d=1e100.net; s=20130820;
 h=x-original-authentication-results:x-gm-message-state:delivered-to
 :mime-version:content-transfer-encoding:content-type:message-id:date
 :from:user-agent:to:cc:subject:references:in-reply-to;
 bh=PjKFDJqoZh9lI/bnBXsBQF3fZTG2Iw8pBEmKW9y8T7g=;
 b=nF4Cseqmu6kjnxZ/54X9ifDUJ0lR+oXGDr3vDh2uOIYvuu6kxQnV8z8IxTNvn36Jft
 02Ne9/hRqNg04/bF9OQZijQT2CuK3Dz83Iuwj89Rl0geDf78HjDBMiCZJCic0amy03Yb
 Z6I7OhCDQH3e9sml4qp+6z558MY2Cg1MZl/ezL+7A505J4gfOC9Xr4rY3+Obdnoy3Lat
 qwYh5UxPwpxmwyAcrPPTTKDK7mtZFc4oItpVsmhG01EALlLhC7/Zh1ltnyMNM12UBDBJ
 PiOUufCp0jupmiriRpJMzHMN9iSRU4jR0vpC2fXuQRXLNu6di3oZxy/o+dMv1hFjCXzd
 KiSw==
x-original-authentication-results: mx.google.com;       spf=pass 
	(google.com: domain of joe.meszaros@verizon.net designates 
	206.46.173.23 as permitted sender) 
	smtp.mail=joe.meszaros@verizon.net
x-gm-message-state: 
	ALoCoQmy+pKptyypIJA9lhsjqwcDpP19poN6u822cE/bhJ+pKTUWz9MPlGWz/0J59ZOPM2JTIYvN
x-x-forwarded-for: morano@ieee.org coldspacemachine@gmail.com
mime-version: 1.0
content-transfer-encoding: 8BIT
content-type: text/plain; charset=windows-1252; format=flowed
x-cmae-score: 0
x-cmae-analysis: v=2.1 cv=PYxIXZlY c=1 sm=1 tr=0	
	a=VRynkGr9XiHC1fkGaCm25w==:117
 a=sXhmN769Lu4A:10 a=N659UExz7-8A:10	a=o1OHuDzbAAAA:8 
	a=oR5dmqMzAAAA:8
 a=-9mUelKeXuEA:10 a=0HtSIViG9nkA:10	a=zQ7y9GTPAAAA:8 
	a=kViFeMVHAAAA:20
 a=YQbTsBPhAAAA:8 a=uMfHurOcAAAA:20	a=o5tZOWlaajPojoU39i8A:9 
	a=pILNOxqGKmIA:10
 a=KtYTXwoU_38A:10	a=E-E4SplAhJUA:10
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:17.0)
 Gecko/20130328 Thunderbird/17.0.5
in-reply-to: <rca11386.54E39A6F.0@rightcore.com>
x-bogosity: Unsure, tests=bogofilter, spamicity=0.520000, version=1.1.5
status:           
references: <rca11386.54E39A6F.0@rightcore.com>
From:  Joe Meszaros <joe.meszaros@verizon.net>
To:  David Morano: COMPUTER <morano@computer.org>, David Morano: IEEE
 <morano@ieee.org>, David Morano: ACM <morano@acm.org>
cc:  Abettina Morano <dell.morano@gmail.com>
Date: Tue, 17 Feb 2015 17:41:08 -0500
Subject: Re: Ben Carson


"‘Conservative Hero’ Ben Carson To Beck: You Have No Right To 
Semi-Automatic Weapons In Large Cities":

http://www.mediaite.com/tv/conservative-hero-ben-carson-to-beck-you-have-no-right-to-semi-automatic-weapons-in-large-cities/

http://tinyurl.com/anr7jb6



"Ben Carson Open to 'Conversation' on 2nd Amendment, Against Assault 
Weapons Ban":

http://www.breitbart.com/video/2014/05/28/ben-carson-open-to-conversation-on-2nd-amendment-against-assault-weapons-ban/

http://tinyurl.com/nwss64t



On 2/17/15 2:45 PM, David Morano wrote:
> Hi Mom,
>
> I don't know "Ben Carson" from a hole in the wall, but
> apparently there are two things about him:
>
> a) he is supposed to be a candidate for president on the GOP side
> b) he now wants impose forced mandatory vaccinations for the whole
>     population of the United States
>
> This guy "Ben Carson" is a psychopath!
>
> Whatever he might have been before, we now know that he is a
> total psychopath!
>
> Dave
>

