From gmail.com!coldspacemachine+caf_=dam=rightcore.com Fri Jun 14 15:24:23 EDT 2013 -0400
return-path:  <coldspacemachine+caf_=dam=rightcore.com@gmail.com>
received: from mail-ie0-f174.google.com (mail-ie0-f174.google.com 
	[209.85.223.174])
 by mail.rightcore.com (RCMAILER) with ESMTP id 0ECAF233FE
 for <dam@rightcore.com>; Fri, 14 Jun 2013 15:24:22 -0400 (EDT)
received: by mail-ie0-f174.google.com with SMTP id 9so2193586iec.19
 for <dam@rightcore.com>; Fri, 14 Jun 2013 12:24:22 -0700 (PDT)
received: by 10.50.195.132 with SMTP id ie4csp37916igc;
 Fri, 14 Jun 2013 12:24:21 -0700 (PDT)
received: from cs-ems2.ieee.org (cs-listserv.ieee.org. [140.98.193.208])
 by mx.google.com with ESMTPS id he7si3198134qab.69.2013.06.14.12.24.21
 for <coldspacemachine@gmail.com>
 (version=TLSv1 cipher=RC4-SHA bits=128/128);
 Fri, 14 Jun 2013 12:24:21 -0700 (PDT)
received: from hormel8.ieee.org (hormel8.ieee.org [140.98.193.231])
 by cs-ems2.ieee.org (8.13.8/8.13.8/) with ESMTP id r5EJOJol015564
 for <morano@computer.org>; Fri, 14 Jun 2013 15:24:20 -0400
received: from mail-pb0-f52.google.com (mail-pb0-f52.google.com 
	[209.85.160.52])
 by hormel8.ieee.org (8.14.3/8.14.3/Debian-5+lenny1) with ESMTP id 
	r5EJNojA024595
 for <morano@computer.org>; Fri, 14 Jun 2013 15:23:54 -0400
received: by mail-pb0-f52.google.com with SMTP id xa12so865181pbc.11
 for <morano@computer.org>; Fri, 14 Jun 2013 12:23:50 -0700 (PDT)
received: from psmtp.com ([74.125.149.121])
 by mx.google.com with SMTP id zo4si1741297pbc.319.2013.06.14.12.15.27
 for <morano@computer.org>;
 Fri, 14 Jun 2013 12:15:31 -0700 (PDT)
received: from mr38.us.researchgate.net ([66.135.44.248]) by 
	na3sys009amx237.postini.com ([74.125.148.10]) with SMTP;
 Fri, 14 Jun 2013 19:15:30 GMT
received: from mr38.us.researchgate.net (localhost [127.0.0.1])
 by mr38.us.researchgate.net (Postfix) with ESMTP id AB0E110005A7C
 for <morano@computer.org>; Fri, 14 Jun 2013 19:15:26 +0000 (UTC)
content-length: 16263               
message-id: <20130614191526.A9CA4100003B3@mr38.us.researchgate.net>
x-original-to: dam@rightcore.com
delivered-to: dam@rightcore.com
delivered-to: coldspacemachine@gmail.com
x-google-dkim-signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
 d=google.com; s=20120113;
 h=x-forwarded-to:x-forwarded-for:delivered-to:dkim-signature
 :domainkey-signature:mime-version:to:list-unsubscribe:from:subject
 :content-type:message-id:date:x-gm-message-state:x-bayes-prob
 :x-spam-score:x-canit-geo:x-canitpro-stream:x-canit-stats-id
 :x-scanned-by;
 bh=MFnzVWBI1ftkiEqetWbV0DLojzp/iwwdlxQBbAa6jTA=;
 b=mTEuVdhjOJnm7nXqGD1zFQaaEL3dQ805a2cLZmG0YoF/0+xj0lfLlM2lgYkVe4VFdB
 M6WU9Y2v7nXp1qC0lJQkaDcjPnw3Hw0IdbGySulugdTkPtpbWXSsxOHlzC0422+gAuUL
 bPQiklKvd/HxeCsz8njN4vsCVN5NwDK2yF+Lv7w6Tb+9LhNRX10BN0tatWpSPn2uwuWS
 koY6GHA7h53M7XPGYfEDJYoAt4L+gZScGOqxDxmCHHB/y2g+P+3RXQubd70OPTZp5sny
 wGZMmvnYtAK8f7DfptDLsYfZsRqGtD93viAJnMedIz6pCWuV/Ip4J5Df+H+ZvGn6/8Ka
 AkWw==
x-received: by 10.50.30.2 with SMTP id o2mr1760590igh.77.1371237862552;
 Fri, 14 Jun 2013 12:24:22 -0700 (PDT)
x-received: by 10.224.181.14 with SMTP id bw14mr3899843qab.54.1371237861540;
 Fri, 14 Jun 2013 12:24:21 -0700 (PDT)
x-received: by 10.68.226.99 with SMTP id rr3mr3980895pbc.35.1371237331331;
 Fri, 14 Jun 2013 12:15:31 -0700 (PDT)
x-received: by 10.68.226.99 with SMTP id rr3mr3980887pbc.35.1371237331245;
 Fri, 14 Jun 2013 12:15:31 -0700 (PDT)
x-forwarded-to: dam@rightcore.com
x-forwarded-for: coldspacemachine@gmail.com dam@rightcore.com
received-spf: softfail (google.com: domain of transitioning 
	MJRDIOJSGUYWEYRWMI3WINTFGYYDKO3NN5ZGC3TPIBRW63LQOV2GK4RON5ZGO===@bounce.researchgate.net
	does not designate 140.98.193.208 as permitted sender) 
	client-ip=140.98.193.208;
received-spf: pass (google.com: domain of 
	MJRDIOJSGUYWEYRWMI3WINTFGYYDKO3NN5ZGC3TPIBRW63LQOV2GK4RON5ZGO===@bounce.researchgate.net
	designates 66.135.44.248 as permitted sender) 
	client-ip=66.135.44.248;
authentication-results: mx.google.com;
 spf=softfail (google.com: domain of transitioning 
	MJRDIOJSGUYWEYRWMI3WINTFGYYDKO3NN5ZGC3TPIBRW63LQOV2GK4RON5ZGO===@bounce.researchgate.net
	does not designate 140.98.193.208 as permitted sender) 
	smtp.mail=MJRDIOJSGUYWEYRWMI3WINTFGYYDKO3NN5ZGC3TPIBRW63LQOV2GK4RON5ZGO===@bounce.researchgate.net;
 dkim=pass header.i=@researchgate.net
dkim-signature: v=1; a=rsa-sha1; c=relaxed; d=researchgate.net; h=
 mime-version:to:list-unsubscribe:from:subject:content-type
 :message-id:date; s=rg; bh=UZffBObAMod7oU6fhCoLP4UAri4=; b=MFas0
 MoO/Eaj1z9SaK/RJUXfxYh8yoqizYcbqkVb4wGnyPvrUt/OKpnPt23Ay2a5701nu
 hTc5mchmXtUkWj67zQiRcCImvV3eVCV7XUK/Nv3bG3mkgbsdujsbEv9TwduJnaSu
 xKvhlpUMShiMkntX96WUz1cXozXFogoFNjt0dY=
domainkey-signature: a=rsa-sha1; c=nofws; d=researchgate.net; h=
 mime-version:to:list-unsubscribe:from:subject:content-type
 :message-id:date; q=dns; s=rg; b=NlJdAnTNnIYsPcN1AkjDVbNT2VfodDJ
 aLDQclNdtVLjHCqFWnpbwRJSoGAefYD9jxR+G2cP/yMk2eHiZtHJGy/j2P2sL/3A
 jhXc1XBuQNVs+88Tl5dp+1SgQrMuFTXR2uBekMTY9XJQGT6AAgLsWMCx5mHNaZa7
 FiQoSRX86FHA=
mime-version: 1.0
list-unsubscribe: 
	<http://www.researchgate.net/go.Out.rgScoreDigest.html?ch=reg&loginT=Qob9hLIiU8fAhD1HAmTrVO25SyCKd5wczV0UJUbgy6I,&cp=re246_b_u3&ev=list-usub>
content-type: multipart/alternative;
 boundary="=_2598c08f9b905c8c8b75e87a4c075993"
x-pstn-neptune: 0/0/0.00/0
x-pstn-levels: (S: 1.25634/99.90000 CV:99.9000 FC:95.5390 LC:95.5390 
	R:95.9108 P:95.9108 M:97.0282 C:98.6951 )
x-pstn-dkim: 1 skipped:not-enabled
x-pstn-status: off
x-pstn-nxpr: disp=neutral, envrcpt=morano@computer.org
x-pstn-nxpr: disp=neutral, envrcpt=morano@computer.org
x-pstn-nxp: bodyHash=ec31e735abc3d8573b511dc4aa294af501533b0d, 
	headerHash=ee8103a094386c0711443ce7908065e1c4c620c3, keyName=4, 
	rcptHash=dbb4786c836f1d131dd4a603a7a958c1aa59c394, 
	sourceip=66.135.44.248, version=1
x-pstn-nxp: bodyHash=ec31e735abc3d8573b511dc4aa294af501533b0d, 
	headerHash=ee8103a094386c0711443ce7908065e1c4c620c3, keyName=4, 
	rcptHash=dbb4786c836f1d131dd4a603a7a958c1aa59c394, 
	sourceip=66.135.44.248, version=1
x-gm-message-state: 
	ALoCoQkREP0Gk2PrGaBY9gIC1drgHQOyi9ela/EicjMakr2r2s29hIFn6U3tz0JrjQx2vJ+7ErlV9L4iRW+DIZK4EBJpZ58GUzA+RCiXs2QnHMIlhAUJp82hMqoMVzYQBAgPGZRcSZuiamuRj6zXG8vwWHRjXRI10Q==
x-bayes-prob: 0.0001 (Score 0, tokens from: @@RPTN)
x-spam-score: 0.00 () [Hold at 7.00] HTML_MESSAGE,SPF(softfail:0)
x-canit-geo: ip=209.85.160.52; country=US; region=CA; city=Mountain View; 
	postalcode=94043; latitude=37.4192; longitude=-122.0574; 
	metrocode=807; areacode=650; 
	http://maps.google.com/maps?q=37.4192,-122.0574&z=6
x-canitpro-stream: 04263802@computer_society (inherits from 
	80_DEFAULT,default)
x-canit-stats-id: Bayes signature not available
x-scanned-by: IEEE Spam Scanner (https://uce.ieee.org/) on 140.98.193.231
status: 
From:  ResearchGate <no-reply@researchgate.net>
x-To:  David Morano <morano@computer.org>
x-Date: Fri, 14 Jun 2013 19:15:26 +0000 (UTC)
Subject: David, 6 researchers viewed your profile

--=_2598c08f9b905c8c8b75e87a4c075993
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

David, here&#39;s your weekly stats update.
Your stats dashboard makes it easy to gauge the reach and visibility of y=
our research over time.

Publication views
6 LAST WEEK
34 TOTAL
https://www.researchgate.net/profile/David_Morano/stats/?ch=3Dreg&cp=3Dre=
246_b_p5&pli=3D1&loginT=3DQob9hLIiU8fAhD1HAmTrVO25SyCKd5wczV0UJUbgy6I,#ta=
rget-Publications


Full-text downloads
5 LAST WEEK
21 TOTAL
https://www.researchgate.net/profile/David_Morano/stats/?chart=3Dfull-tex=
t_downloads&ch=3Dreg&cp=3Dre246_b_p6&pli=3D1&loginT=3DQob9hLIiU8fAhD1HAmT=
rVO25SyCKd5wczV0UJUbgy6I,#target-Publications


Profile views
6 LAST WEEK
16 TOTAL
See views by country
https://www.researchgate.net/profile/David_Morano/stats/?ch=3Dreg&cp=3Dre=
246_b_p8&pli=3D1&loginT=3DQob9hLIiU8fAhD1HAmTrVO25SyCKd5wczV0UJUbgy6I,#ta=
rget-Profile



View your stats: https://www.researchgate.net/profile/David_Morano/stats/=
?ch=3Dreg&cp=3Dre246_b_p2&pli=3D1&loginT=3DQob9hLIiU8fAhD1HAmTrVO25SyCKd5=
wczV0UJUbgy6I,


-------------------------------------------------------------------------=
------

This message was sent to morano@computer.org. To make sure you receive ou=
r updates, add ResearchGate to your address book or safe list.
See instructions: http://www.researchgate.net/application.EmailInstructio=
ns.html

If you don't want to receive these emails from ResearchGate in the future=
, please unsubscribe:
http://www.researchgate.net/go.Out.rgScoreDigest.html?ch=3Dreg&cp=3Dre246=
_b_u2&loginT=3DQob9hLIiU8fAhD1HAmTrVO25SyCKd5wczV0UJUbgy6I,

ResearchGate GmbH, Invalidenstr. 115, 10115 Berlin, Germany.
See our Privacy Policy: http://www.researchgate.net/application.PrivacyPo=
licy.html and Terms & Conditions: http://www.researchgate.net/application=
.TermsAndConditions.html
--=_2598c08f9b905c8c8b75e87a4c075993
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset="UTF-8"

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3c.org/TR/1999/REC-html401-19991224/loose.dtd"><html><head><ti=
tle></title></head><body><table
width=3D"100%" cellspacing=3D"0" cellpadding=3D"0" border=3D"0" bgcolor=3D"=
#ffffff"><tbody><tr><td><table
width=3D"590" cellspacing=3D"0" cellpadding=3D"0" border=3D"0" align=3D"cen=
ter"><tbody><tr><td><table
width=3D"590" cellspacing=3D"0" cellpadding=3D"0" border=3D"0"><tbody><tr><=
td
height=3D"10"></td></tr><tr><td
valign=3D"top"><table
width=3D"100%" cellspacing=3D"0" cellpadding=3D"0" border=3D"0" style=3D"ba=
ckground: #666666; font-family: Helvetica, Arial, sans-serif !important;"><=
tbody><tr><td
width=3D"542" height=3D"50" align=3D"right"> <img
style=3D"border: 0; outline: 0; margin: 0 0 2px 0; padding: 0;" width=3D"12=
0" height=3D"20" title=3D"ResearchGate" alt=3D"ResearchGate" src=3D"http://=
www.researchgate.net/images/template/rg_logo_mail.png?uid=3Dbb49251bb6b7d6e=
605&cn=3D6kt3JVrQOLAozxBllLgjWiyEqslAmndTRoAiqyJ1XMWsX6p2pT2zMm7vyPh2eF1TR-=
CEl2kTb-8wc9f4jjsiXckbQdEe_NCq4VAo8_m8cMFURZqfimnYl0j1oUf_iYV8&loginT=3DQob=
9hLIiU8fAhD1HAmTrVO25SyCKd5wczV0UJUbgy6I," /></td><td
width=3D"30" height=3D"50"></td></tr></tbody></table></td></tr></tbody></ta=
ble><table
cellspacing=3D"0" border=3D"0" cellpadding=3D"0" width=3D"590" style=3D"pad=
ding:0; background-color: #f7f7f4;"><tbody><tr><td
height=3D"30">&nbsp;</td><td
height=3D"30">&nbsp;</td><td
height=3D"30">&nbsp;</td></tr><tr><td
width=3D"30">&nbsp;</td><td><table><tbody><tr><td><p
style=3D"font-size: 16px; margin:0;padding:0; color: #666; margin: 0 0 10px=
 0; font-family: helvetica, arial, sans-serif;"><strong>David, here&#39;s y=
our weekly stats update.</strong></p><p
style=3D"font-size: 15px; margin:0;padding:0; color: #666; margin: 0 0 0 0;=
 font-family: helvetica, arial, sans-serif;">Your stats dashboard makes it =
easy to gauge the reach and visibility of your research over time.</p></td>=
</tr><tr><td
height=3D"17"></td></tr></tbody></table><table
width=3D"100%" style=3D"line-height: 10px; background-color: #ffffff;"><tbo=
dy><tr><td
width=3D"30">&nbsp;</td><td><table
cellspacing=3D"0" border=3D"0" cellpadding=3D"0"><tbody><tr><td
style=3D"padding: 0; margin: 0; font-size: 0px;" height=3D"85"> <a
href=3D"https://www.researchgate.net/profile/David_Morano/stats/?ch=3Dreg&c=
p=3Dre246_b_p5&pli=3D1&loginT=3DQob9hLIiU8fAhD1HAmTrVO25SyCKd5wczV0UJUbgy6I=
,#target-Publications" style=3D"text-decoration: none;"> <img
alt=3D"Publication views" height=3D"47" width=3D"47" src=3D"http://www.rese=
archgate.net/images/mailing/icons/publication-white.png" /> </a></td><td
width=3D"20" height=3D"85">&nbsp;</td><td
valign=3D"middle" style=3D"" height=3D"85" width=3D"80"><p
style=3D"font-family: helvetica, arial, sans-serif; font-size: 14px; font-w=
eight: bold; margin: 0 0 0px 0; padding: 0;line-height: 20px;"> <a
href=3D"https://www.researchgate.net/profile/David_Morano/stats/?ch=3Dreg&c=
p=3Dre246_b_p5&pli=3D1&loginT=3DQob9hLIiU8fAhD1HAmTrVO25SyCKd5wczV0UJUbgy6I=
,#target-Publications" style=3D"text-decoration: none; color: #666;">Public=
ation views</a></p></td><td
height=3D"85" width=3D"35">&nbsp;</td><td
valign=3D"middle" style=3D"" height=3D"85" width=3D"145"><p
style=3D"font-family: helvetica, arial, sans-serif; font-size: 11px; margin=
: 0 0 0px 0; padding: 0;line-height: 20px;"> <a
href=3D"https://www.researchgate.net/profile/David_Morano/stats/?ch=3Dreg&c=
p=3Dre246_b_p5&pli=3D1&loginT=3DQob9hLIiU8fAhD1HAmTrVO25SyCKd5wczV0UJUbgy6I=
,#target-Publications" style=3D"text-decoration: none; color: #588631;"> <s=
pan
style=3D"font-size: 16px;font-weight: bold;">6</span>&nbsp;&nbsp;&nbsp;&nbs=
p;LAST WEEK </a></p><p
style=3D"font-family: helvetica, arial, sans-serif; font-size: 11px; color:=
 #666; margin: 0 0 0px 0; padding: 0;line-height: 20px;"> <a
href=3D"https://www.researchgate.net/profile/David_Morano/stats/?ch=3Dreg&c=
p=3Dre246_b_p5&pli=3D1&loginT=3DQob9hLIiU8fAhD1HAmTrVO25SyCKd5wczV0UJUbgy6I=
,#target-Publications" style=3D"text-decoration: none; color: #666;"> <span
style=3D"font-size: 16px;font-weight: bold;">34</span>&nbsp;&nbsp;&nbsp;&nb=
sp;TOTAL </a></p></td><td
height=3D"85" width=3D"30">&nbsp;</td><td
valign=3D"middle" style=3D"" height=3D"85" width=3D"120"><p
style=3D"font-family: helvetica, arial, sans-serif; font-size: 11px; color:=
 #666; margin: 0 0 0px 0; padding: 0;line-height: 20px;"> <a
href=3D"https://www.researchgate.net/profile/David_Morano/stats/?ch=3Dreg&c=
p=3Dre246_b_p5&pli=3D1&loginT=3DQob9hLIiU8fAhD1HAmTrVO25SyCKd5wczV0UJUbgy6I=
,#target-Publications" style=3D"text-decoration: underline; color: #666666;=
">View details</a></p></td></tr></tbody></table><table
width=3D"100%" cellspacing=3D"0" cellpadding=3D"0" borderspacing=3D"0" bord=
er=3D"0"><tbody><tr><td
height=3D"1" style=3D"background-color: #dddddd;" width=3D"100%"></td></tr>=
<tr><td
height=3D"1" style=3D"background-color: #ffffff;" width=3D"100%"></td></tr>=
</tbody></table><table
cellspacing=3D"0" border=3D"0" cellpadding=3D"0"><tbody><tr><td
style=3D"padding: 0; margin: 0; font-size: 0px;" height=3D"85"> <a
href=3D"https://www.researchgate.net/profile/David_Morano/stats/?chart=3Dfu=
ll-text_downloads&ch=3Dreg&cp=3Dre246_b_p6&pli=3D1&loginT=3DQob9hLIiU8fAhD1=
HAmTrVO25SyCKd5wczV0UJUbgy6I,#target-Publications" style=3D"text-decoration=
: none;"> <img
alt=3D"Full-text downloads" height=3D"47" width=3D"47" src=3D"http://www.re=
searchgate.net/images/mailing/icons/full-text-white.png" /> </a></td><td
width=3D"20" height=3D"85">&nbsp;</td><td
valign=3D"middle" style=3D"" height=3D"85" width=3D"80"><p
style=3D"font-family: helvetica, arial, sans-serif; font-size: 14px; font-w=
eight: bold; margin: 0 0 0px 0; padding: 0;line-height: 20px;"> <a
href=3D"https://www.researchgate.net/profile/David_Morano/stats/?chart=3Dfu=
ll-text_downloads&ch=3Dreg&cp=3Dre246_b_p6&pli=3D1&loginT=3DQob9hLIiU8fAhD1=
HAmTrVO25SyCKd5wczV0UJUbgy6I,#target-Publications" style=3D"text-decoration=
: none; color: #666;">Full-text downloads</a></p></td><td
height=3D"85" width=3D"35">&nbsp;</td><td
valign=3D"middle" style=3D"" height=3D"85" width=3D"145"><p
style=3D"font-family: helvetica, arial, sans-serif; font-size: 11px; margin=
: 0 0 0px 0; padding: 0;line-height: 20px;"> <a
href=3D"https://www.researchgate.net/profile/David_Morano/stats/?chart=3Dfu=
ll-text_downloads&ch=3Dreg&cp=3Dre246_b_p6&pli=3D1&loginT=3DQob9hLIiU8fAhD1=
HAmTrVO25SyCKd5wczV0UJUbgy6I,#target-Publications" style=3D"text-decoration=
: none; color: #588631;"> <span
style=3D"font-size: 16px;font-weight: bold;">5</span>&nbsp;&nbsp;&nbsp;&nbs=
p;LAST WEEK </a></p><p
style=3D"font-family: helvetica, arial, sans-serif; font-size: 11px; color:=
 #666; margin: 0 0 0px 0; padding: 0;line-height: 20px;"> <a
href=3D"https://www.researchgate.net/profile/David_Morano/stats/?chart=3Dfu=
ll-text_downloads&ch=3Dreg&cp=3Dre246_b_p6&pli=3D1&loginT=3DQob9hLIiU8fAhD1=
HAmTrVO25SyCKd5wczV0UJUbgy6I,#target-Publications" style=3D"text-decoration=
: none; color: #666;"> <span
style=3D"font-size: 16px;font-weight: bold;">21</span>&nbsp;&nbsp;&nbsp;&nb=
sp;TOTAL </a></p></td><td
height=3D"85" width=3D"30">&nbsp;</td><td
valign=3D"middle" style=3D"" height=3D"85" width=3D"120"><p
style=3D"font-family: helvetica, arial, sans-serif; font-size: 11px; color:=
 #666; margin: 0 0 0px 0; padding: 0;line-height: 20px;"> <a
href=3D"https://www.researchgate.net/profile/David_Morano/stats/?chart=3Dfu=
ll-text_downloads&ch=3Dreg&cp=3Dre246_b_p6&pli=3D1&loginT=3DQob9hLIiU8fAhD1=
HAmTrVO25SyCKd5wczV0UJUbgy6I,#target-Publications" style=3D"text-decoration=
: underline; color: #666666;">View publications</a></p></td></tr></tbody></=
table><table
width=3D"100%" cellspacing=3D"0" cellpadding=3D"0" borderspacing=3D"0" bord=
er=3D"0"><tbody><tr><td
height=3D"1" style=3D"background-color: #dddddd;" width=3D"100%"></td></tr>=
<tr><td
height=3D"1" style=3D"background-color: #ffffff;" width=3D"100%"></td></tr>=
</tbody></table><table
cellspacing=3D"0" border=3D"0" cellpadding=3D"0"><tbody><tr><td
style=3D"padding: 0; margin: 0; font-size: 0px;" height=3D"85"> <a
href=3D"https://www.researchgate.net/profile/David_Morano/stats/?ch=3Dreg&c=
p=3Dre246_b_p8&pli=3D1&loginT=3DQob9hLIiU8fAhD1HAmTrVO25SyCKd5wczV0UJUbgy6I=
,#target-Profile" style=3D"text-decoration: none;"> <img
alt=3D"Profile views" height=3D"47" width=3D"47" src=3D"http://www.research=
gate.net/images/mailing/icons/profile-white.png" /> </a></td><td
width=3D"20" height=3D"85">&nbsp;</td><td
valign=3D"middle" style=3D"" height=3D"85" width=3D"80"><p
style=3D"font-family: helvetica, arial, sans-serif; font-size: 14px; font-w=
eight: bold; margin: 0 0 0px 0; padding: 0;line-height: 20px;"> <a
href=3D"https://www.researchgate.net/profile/David_Morano/stats/?ch=3Dreg&c=
p=3Dre246_b_p8&pli=3D1&loginT=3DQob9hLIiU8fAhD1HAmTrVO25SyCKd5wczV0UJUbgy6I=
,#target-Profile" style=3D"text-decoration: none; color: #666;">Profile vie=
ws</a></p></td><td
height=3D"85" width=3D"35">&nbsp;</td><td
valign=3D"middle" style=3D"" height=3D"85" width=3D"145"><p
style=3D"font-family: helvetica, arial, sans-serif; font-size: 11px; margin=
: 0 0 0px 0; padding: 0;line-height: 20px;"> <a
href=3D"https://www.researchgate.net/profile/David_Morano/stats/?ch=3Dreg&c=
p=3Dre246_b_p8&pli=3D1&loginT=3DQob9hLIiU8fAhD1HAmTrVO25SyCKd5wczV0UJUbgy6I=
,#target-Profile" style=3D"text-decoration: none; color: #588631;"> <span
style=3D"font-size: 16px;font-weight: bold;">6</span>&nbsp;&nbsp;&nbsp;&nbs=
p;LAST WEEK </a></p><p
style=3D"font-family: helvetica, arial, sans-serif; font-size: 11px; color:=
 #666; margin: 0 0 0px 0; padding: 0;line-height: 20px;"> <a
href=3D"https://www.researchgate.net/profile/David_Morano/stats/?ch=3Dreg&c=
p=3Dre246_b_p8&pli=3D1&loginT=3DQob9hLIiU8fAhD1HAmTrVO25SyCKd5wczV0UJUbgy6I=
,#target-Profile" style=3D"text-decoration: none; color: #666;"> <span
style=3D"font-size: 16px;font-weight: bold;">16</span>&nbsp;&nbsp;&nbsp;&nb=
sp;TOTAL </a></p></td><td
height=3D"85" width=3D"30">&nbsp;</td><td
valign=3D"middle" style=3D"" height=3D"85" width=3D"120"><p
style=3D"font-family: helvetica, arial, sans-serif; font-size: 12px; color:=
 #666; margin: 0 0 0px 0; padding: 0;line-height: 20px;"><strong>See views =
by</strong></p><p
style=3D"font-family: helvetica, arial, sans-serif; font-size: 11px; color:=
 #666; margin: 0 0 0px 0; padding: 0;line-height: 20px;"> <a
href=3D"https://www.researchgate.net/profile/David_Morano/stats/?ch=3Dreg&c=
p=3Dre246_b_p8&pli=3D1&loginT=3DQob9hLIiU8fAhD1HAmTrVO25SyCKd5wczV0UJUbgy6I=
,#target-Profile" style=3D"text-decoration: underline; color: #666666;">cou=
ntry</a></p></td></tr></tbody></table></td><td
width=3D"30">&nbsp;</td></tr></tbody></table><table
cellspacing=3D"0" border=3D"0" cellpadding=3D"0" width=3D"100%" style=3D"pa=
dding: 0; margin:0;"><tbody><tr
height=3D"20"><td
height=3D"20" style=3D"font-size: 10px;">&nbsp;</td><td
height=3D"20" style=3D"font-size: 10px;">&nbsp;</td><td
height=3D"20" style=3D"font-size: 10px;">&nbsp;</td><td
height=3D"20" style=3D"font-size: 10px;">&nbsp;</td></tr><tr><td><table
align=3D"left" width=3D"270" cellspacing=3D"0" cellpadding=3D"0" borderspac=
ing=3D"0"><tbody><tr><td
height=3D"40" align=3D"center" style=3D"padding: 0; border-color: rgb(167, =
223, 85) rgb(115, 162, 47) rgb(115, 162, 47); border-width: 1px; border-sty=
le: solid; background-color: rgb(131, 183, 54); background-position: 50% 0%=
; background-repeat: repeat-x; background-image: url('http://www.researchga=
te.net/images/mailing/button-gradient.jpg');"> <a
style=3D"text-align: center; display: block; text-decoration: none; height:=
 100%; line-height: 40px; color: #ffffff; margin: 0; font-family: helvetica=
, arial, sans-serif; width: 100%; font-size: 14px; font-weight:bold;" href=
=3D"https://www.researchgate.net/profile/David_Morano/stats/?ch=3Dreg&cp=3D=
re246_b_p2&pli=3D1&loginT=3DQob9hLIiU8fAhD1HAmTrVO25SyCKd5wczV0UJUbgy6I,">V=
iew your stats</a></td></tr></tbody></table></td></tr><tr
height=3D"15"><td
height=3D"15" style=3D"font-size: 10px;">&nbsp;</td><td
height=3D"15" style=3D"font-size: 10px;">&nbsp;</td><td
height=3D"15" style=3D"font-size: 10px;">&nbsp;</td><td
height=3D"15" style=3D"font-size: 10px;">&nbsp;</td></tr></tbody></table></=
td><td
width=3D"30">&nbsp;</td></tr><tr><td
height=3D"30">&nbsp;</td><td
height=3D"30">&nbsp;</td><td
height=3D"30">&nbsp;</td></tr></tbody></table><table
width=3D"590" cellspacing=3D"0" cellpadding=3D"0" border=3D"0"><tbody><tr><=
td
width=3D"590" valign=3D"middle" height=3D"5" style=3D"background-color: rgb=
(204, 204, 204);"></td></tr><tr><td
height=3D"8"></td></tr><tr><td><p
style=3D"font-size: 11px; line-height: 15px; font-family: Helvetica,Arial,s=
ans-serif; color: rgb(153, 153, 153); margin: 0px 0px 20px 0pt;"> This mess=
age was sent to morano@computer.org. To make sure you receive our updates, =
add ResearchGate to your address book or safe list. <a
style=3D"color: rgb(153, 153, 153); text-decoration: underline;" href=3D"ht=
tp://www.researchgate.net/application.EmailInstructions.html">See instructi=
ons</a>.<br
/><br
/> If you don&#39;t want to receive these emails from ResearchGate in the f=
uture, please <a
style=3D"color: rgb(153, 153, 153); text-decoration: underline;" href=3D"ht=
tp://www.researchgate.net/go.Out.rgScoreDigest.html?ch=3Dreg&cp=3Dre246_b_u=
1&loginT=3DQob9hLIiU8fAhD1HAmTrVO25SyCKd5wczV0UJUbgy6I,">unsubscribe</a>.<b=
r
/> <br/>ResearchGate GmbH, Invalidenstr. 115, 10115 Berlin, Germany.<br
/> See our <a
style=3D"color: rgb(153, 153, 153); text-decoration: underline;" href=3D"ht=
tp://www.researchgate.net/application.PrivacyPolicy.html">Privacy Policy</a=
> and <a
style=3D"color: rgb(153, 153, 153); text-decoration: underline;" href=3D"ht=
tp://www.researchgate.net/application.TermsAndConditions.html">Terms &amp; =
Conditions</a>.</p></td></tr></tbody></table> <img
width=3D"1" height=3D"1" alt=3D"" src=3D"http://www.researchgate.net/images=
/template/footer.gif?uid=3Dbb49251bb6b7d6e605&cn=3D6kt3JVrQOLAozxBllLgjWiyE=
qslAmndTRoAiqyJ1XMWsX6p2pT2zMm7vyPh2eF1TR-CEl2kTb-8wc9f4jjsiXckbQdEe_NCq4VA=
o8_m8cMFURZqfimnYl0j1oUf_iYV8" /></td></tr></tbody></table></td></tr></tbod=
y></table></body></html>
--=_2598c08f9b905c8c8b75e87a4c075993--

