/* config */


#define	VERSION		"0"
#define	WHATINFO	"@(#)RMER "
#define	BANNER		"Remover"
#define	SEARCHNAME	"rmer"
#define	VARPRNAME	"LOCAL"

#ifndef	PROGRAMROOT
#define	PROGRAMROOT	"/usr/add-on/local"
#endif

#define	VARPROGRAMROOT1	"RMER_PROGRAMROOT"
#define	VARPROGRAMROOT2	VARPRNAME
#define	VARPROGRAMROOT3	"PROGRAMROOT"

#define	VARBANNER	"RMER_BANNER"
#define	VARSEARCHNAME	"RMER_NAME"
#define	VARJOBDNAME	"RMER_DNAME"
#define	VARAFNAME	"RMER_AF"
#define	VAREFNAME	"RMER_EF"
#define	VARERRORFNAME	"RMER_ERRORFILE"

#define	VARDEBUGFNAME	"RMER_DEBUGFILE"
#define	VARDEBUGFD1	"RMER_DEBUGFD"
#define	VARDEBUGFD2	"DEBUGFD"

#define	VARSYSNAME	"SYSNAME"
#define	VARRELEASE	"RELEASE"
#define	VARMACHINE	"MACHINE"
#define	VARARCHITECTURE	"ARCHITECTURE"
#define	VARHZ		"HZ"
#define	VARNODE		"NODE"
#define	VARCLUSTER	"CLUSTER"
#define	VARSYSTEM	"SYSTEM"
#define	VARDOMAIN	"DOMAIN"
#define	VARNISDOMAIN	"NISDOMAIN"
#define	VARTERM		"TERM"
#define	VARPRINTER	"PRINTER"
#define	VARLPDEST	"LPDEST"
#define	VARPAGER	"PAGER"
#define	VARMAIL		"MAIL"
#define	VARORGANIZATION	"ORGANIZATION"
#define	VARLINES	"LINES"
#define	VARCOLUMNS	"COLUMNS"
#define	VARNAME		"NAME"
#define	VARFULLNAME	"FULLNAME"
#define	VARTZ		"TZ"
#define	VARUSERNAME	"USERNAME"
#define	VARLOGNAME	"LOGNAME"

#define	VARHOMEDNAME	"HOME"
#define	VARTMPDNAME	"TMPDIR"
#define	VARMAILDNAME	"MAILDIR"
#define	VARMAILDNAMES	"MAILDIRS"

#define	VARPRLOCAL	"LOCAL"
#define	VARPRPCS	"PCS"

#define	TMPDNAME	"/tmp"

#define	MKJOBDIR1	"var/spool/locks"
#define	MKJOBDIR2	"/tmp/pcs/locks"
#define	MKJOBDIR3	"/tmp/locks"

#define	LOGCNAME	"log"

#define	LOGFNAME	"log"
#define	HELPFNAME	"help"

#define	LOGSIZE		80000

#define	TO_FILE		(5*60)


