from:    	PCS_administrator <morano@computer.org>
to:      	dmorano@ece.neu.edu
subject:	test email/posting 2
date:           02 Dec 93 12:26:33 PST

This is a test.  This is a test of the emergency email/posting
system.  This is only a test.  This test has been devised
as a means of testing email or bulletin board related operations.
If this had been an actual emergency, you would have been instructed
as to where to send email (for testing purposes !).
This concludes this test of the emergency email/posting system.

From this time forward we will see

PCS Administrator

