From: morano@computer.org (David Morano)
reply-to: morano@computer.org, morano@ele.uri.edu, morano@ieee.org
To: rondayle@juno.com (Pastor Ron Johnson)
x-cc: timothy.bevin@mercer.com
x-cc: acarpenito@juno.com (Arthur Capenito)
x-cc: busterjoe@afo.net
x-cc: ljc@afo.net
x-cc: ddrost@PEACE.GORDON.EDU
x-cc: silver@clresearch.org (Eve Silver)
x-cc: zerotheigenvector@yahoo.com
Subject: re: Regrets +

Pastor,

> But, for a number of reasons, the major one being the request of my son
> Michael to attend a evening service in NH, I will not be able to attend
> Park Street this Sunday.  Things may not work out for me even to attend
> the one in NH.  I trust you understand and hopefully we can plan it for
> another Sunday.

Oh, we didn't have to do that this week at all.  Those churches will be
around for a while (probably much longer than we would like) ! :-)  We
can visit those anytime, including maybe sometime next year (after the
New Year) if that is more convenient.  I just think that it would be an
interesting visit to see how some other rabidly conservative Christian and
Reformed churches conduct their worship now-a-days.  They will be doing
the same things (or worse) for some time to come (if the Lord tarries).

> Thanks for the photos from Katrina.  What it must have been like to be
> under those clouds!  What will the clouds of His appearing be like?

In a word: glorious ! :-)

God's speed, according to His will,
Dave

