#!/usr/bin/ksh
# RUNIT-TEST


TT=bibletest
RF_MKTROFF=true
RF_MKPDF=false

SETOPTS=
SETOPTS="${SETOPTS} -ibz -tc "
SETOPTS="${SETOPTS} -ndb spanish "
SETOPTS="${SETOPTS} -wdb spanish "

PO="0.75i"
PW="7.0i"

bibleset.x ${SETOPTS} ${TT}.txt > ${TT}.mm



