SENDER: dam@rightcore.com (David Morano)
reply-to: morano@computer.org (David Morano - COMPUTER), 
	morano@ieee.org (David Morano - IEEE), 
	morano@acm.org (David Morano - ACM)
from: morano@computer.org (David Morano)
x-cc: morano@computer.org (other recipients)
TO: dell.morano@gmail.com (Abettina Morano)
BCC: dell7me@yahoo.com (Abettina Morano)
BCC: dell7me@gmail.com (Abettina Morano)
x-to: joe.meszaros@verizon.net (Joe Meszaros)
x-cc: joe.meszaros@verizon.net (Joe Meszaros)
x-to: pmorano@gmail.com
	(Phil Morano - if at first you don't succeed, skydiving is not 
	for you)  
x-cc: pmorano@gmail.com
	(Phil Morano - if at first you don't succeed, skydiving is not 
	for you)  
x-cc: pmorano@gmail.com
x-cc: dani.morano@myfairpoint.net (Dani Morano)
x-to: morano@computer.org
x-to: friends <morano@computer.org>
x-bcc: rmdellorfano@gmail.com (Richard Dell'Orfano)
x-cc: 6038600207@VTEXT.COM (Abettina Morano)
BCC: coldspacemachine@gmail.com
content-type: text/plain ; charset=ISO-8859-1
CONTENT-TRANSFER-ENCODING: 8bit
x-content-transfer-encoding: base64
x-Date: 31 Dec 2013 23:55:44 -0500 (USEST)
x-references: 
 <CANXuW=PstPsBAOSHKucx0KkoMJ-HHqRpxYcfEAAifP3JfY2a7w@mail.gmail.com>
x-in-reply-to: 
 <CANXuW=PstPsBAOSHKucx0KkoMJ-HHqRpxYcfEAAifP3JfY2a7w@mail.gmail.com>
x-subject: re: is this a joke?

Hi Mom,

> Well guys.
> Lemme know if this is joke?

Yes, of course it is a joke.

But it is a pretty clever one in that they were able to make pretty
good special effects in that little (3+ minute) film of theirs.

Dave
