SENDER: dam@rightcore.com (David Morano)
reply-to:
	morano@ieee.org (David Morano - IEEE), 
	morano@acm.org (David Morano - ACM)
from: morano@acm.org (David Morano)
TO: dell.morano@gmail.com (Abettina Morano)
CC: abettina.7@gmail.com (Dell Morano)
x-CC: dell7me@yahoo.com (Abettina Morano)
x-CC: dell7me@gmail.com (Abettina Morano)
x-cc: dell.morano@gmail.com (Abettina Morano)
x-to: joe.meszaros@verizon.net (Joe Meszaros)
x-to: pmorano@gmail.com
	(Phil Morano - if at first you don't succeed, skydiving is not 
	for you)  
x-bcc: joe.meszaros@verizon.net (Joe Meszaros)
x-cc: joe.meszaros@verizon.net (Joe Meszaros)
x-cc: pmorano@gmail.com
	(Phil Morano - if at first you don't succeed, skydiving is not 
	for you)  
x-cc: pmorano@gmail.com (Phil Morano)
x-to: morano@computer.org
x-cc: dani.morano@myfairpoint.net (Dani Morano)
x-bcc: rmdellorfano@gmail.com (Richard Dell'Orfano)
x-cc: 6038600207@VTEXT.COM (Abettina Morano)
BCC: coldspacemachine@gmail.com (David A. Morano)
BCC: morano@acm.org (David A. Morano)
MIME-version: 1.0
x-content-transfer-encoding: base64
content-type: text/plain ; charset=ISO-8859-1
CONTENT-TRANSFER-ENCODING: 8bit
x-date:      Sat, 17 Sep 2016 09:07:17 -0400 (USEDT)
x-expires: Tue, 10 Jun 2015 17:44:35 -0400
in-reply-to:
  <CANXuW=PrqTqO1ftNkd1p8iGiYM5M2uER1qRjU7kDRt7LfK-kFg@mail.gmail.com>
References: 
  <CANXuW=PrqTqO1ftNkd1p8iGiYM5M2uER1qRjU7kDRt7LfK-kFg@mail.gmail.com>
Subject: Re: C O L D

Hi Ma,

> I went to the Market Basket today to get some food in my house ... and
> when I realized how c o l d -- it was -- that caused chills ... I
> thought of you ... and hope this c o l d - spell we're in -- will be
> cold enough for you...

Of course, it cannot get cold *enough* for me!

----
Dave

