x-sender: dam@rightcore.com (David Morano)
from: dam@rightcore.com (David Morano)
TO: (David A.                                                          
 ) coldspacemachine       (            ) @            gmail . com
 (             Morano                                            )
to: (        	  	 ) other (  	 	 	 )
content-type: text/plain ; charset=iso-8859-1
content-transfer-encoding: 8bit
x-priority: 1 (high)
subject: test-google

TO: coldspacemachine@gmail.com
Google address parsing

