From rca!dam Sun Apr 14 23:51:37 EDT 2013 -0400
message-id: <rca20298.516B78DB.0@rightcore.com>
x-mailer: PCS-mkmsg
x-face: Y$dX+NUQ@#4._S''f~,b5CNOaIeBWC/c%A(D2ADv\hVzeUdbMy%b-[&Dx7*TT
 5L4?vE*A))U%vN=Claf&#c+$y>{H*6ay6^$+'}{R`;J@y4oojH6IJT/ST!*z6*yA2|jY
 !g)8]=Wt^|,\Wu,8?$4*Je3wWNcsuD*nw'E8YM,NI.$J*:
organization: Rightcore Network Services
x-sender: dam@rightcore.com
reply-to: morano@computer.org, morano@ieee.org, morano@acm.org
content-type: text/plain
content-lines: 92
content-length: 4258
From: morano@computer.org (David A.D. Morano, PE, PhD)
x-To: friends <morano@computer.org>
x-Date: 14 Apr 2013 23:49:47 -0400 (EDT)
x-Subject: uncoming anniversaries

Hello All,

Here are some upcoming anniversaries worth noting:

= April 16

Martin Luther approaches the city of Worms in the morning on this day in
the year 1521.  He will appear before the Diet of Worms two days later
on the 18th.  The day after his appearance, on the 19th, the inquisitors
of Martin Luther at the Diet of Worms do not come to an agreement about
what to do with his case.

Also on the 16th in the year 73, the strong-hold of Masada (occupied by
Jewbo rebels to the Roman Empire) falls to the Romans ending the Jewish
Revolt (lasting since it began in the year 66).  The Romans find after
taking the strong-hold that all of the Jewbos had either murdered each
other or had committed suicide.  Fathers murdered their children and
then their own wives and then either murdered each other or finally
committed suicide.  On investigation by the Romans, it appears that the
Jewbo men murdered each other by the casting of the lot and then the
last man committed suicide.  It is thought that the Jewbos got this idea
from when the Jewbos murdered each other years before when the famous
Jewbo-Roman historian Flavius Josephus murdered the other men held in
siege with him by the Roman general Vespasian.  The Jewbos cast lots
(according to then Jewbo general Flavius Josephus) and murdered each
other, finally leaving Flavius Josephus alive with one other man who
then both finally surrendered to the Romans.

The fact that Jewbos, when under siege, murder each other (including
their own children and wives) by lot and then commit suicide (as in the
case with Masada) show just how cowardly the Jewbos really are (or were
in olden times).  Have Jewbos changed their ways in recent times?  Or are
they the biggest cowards in the history of the world since its beginning?
Who knows?

= April 17

Playboy extraordinaire John F. Kennedy botches his invasion of Cuba
with the famously botched "Bay of Pigs" incident in 1961.  Enough said
already about the first boy-president of the United States (the second
boy-president being Billy-Boy Clinton).

= April 18

Albert Einstein dies in the year 1955.

= April 20

The US Supreme Court unanimously rules in 1971 in favor of bussing, forcing
Niggers to be integrated with Whitie folk in public schools.  Enough said.

= April 21

Her Majesty Queen Elizabeth II of the Commonwealth Realms (then Her
Royal Highness Princess Elizabeth of the British Empire) is born in 1926.

His Majesty King Henry VII of England and France dies in 1509.

His Royal Highness Prince Henry becomes king of England and France (Henry
VIII) on the death of his father His Majesty King Henry VII in 1509
(same event as the previous item).

Rome is founded by Romulus in the year 753 BC.  It will become a republic
(from a kingdom) in the year 509 BC (the usual founding date for the Roman
Empire).  The Western half of the Empire will finally fall irrevocably
in the year 496 (twenty years after the abdication of the last emperor
in the West) giving the Western Roman Empire a lifespan of 1004 years
(1248 years after the founding of Rome).  The Empire will continue in
the East until falling in the year 1453, giving the Eastern Roman Empire
a lifespan of 1961 years (from 509 BC) or 2205 years after the founding
of Rome (in 753 BC).  

The only known state in the history of the world to have a lifespan
approaching that of Rome was the Holy Roman Empire, founded in the year
800 and dissolved by its last emperor (Emperor Francis II) in the year
1806, giving it a lifespan of 1006 years.  The only Prince Elector of the
Empire (the Holy Roman Empire) to object to the dissolution of the Empire
by the Emperor was His Majesty King George the III of the British Empire.
His Majesty King George the III of the British Empire was also both the
king of Hanover (one of the states making up the Holy Roman Empire) and
a Prince Elector of the Holy Roman Empire.  He (HM King George III) gave
his consent to the dissolution of the Holy Roman Empire a few years later.

Saint George's Day (England's National Day) in the Kingdom of England.
Saint George (the famous knight who slays the dragon when the princess
daughter of the king would have otherwise been sacrificed) is the
patron saint of the Kingdom of England.

----

Dave

