x-sender: dam@rightcore.com (David Morano)
x-from: morano@rightcore.com (David Morano)
from: dam@rightcore.com (David Morano)
x-from: dell.morano@gmail.com (Dell Morano)
x-reply-to: dam@rightcore.com (David Morano)
TO: (Cold) coldspacemachine@ ( Space ) gmail.com (Machine)
precedence: bulk
x-TO: david.a.morano (David A. Morano) @ gmail.com
x-to: morano@computer.org (David Morano)
content-type: text/plain ; charset=ISO-8859-1
x-content-transfer-encoding: 8bit
x-subject: picnic coming up

Hi Cindy,

The date of the company picnic is approaching.
Please make note.

Alice

