message-id: <here.586F1DA7.0@rightcore.com>
x-sender: dam@rightcore.com
x-forwarded-to: pcs@ rightcore. com (PCS)
SENDER: dam @ rightcore. 
	com
	(David J. Morano)
reply-to: 
 morano@ieee.org (David Morano),
 morano@acm.org (David Morano)
from: dam @
	rightcore.
	com (David A. Morano)
TO: d.a.morano@icloud.com (David A. Morano)
SUBJECT: anyone home?
BCC: 	pcs @ rightcore. com
BCC: 	pcs @ RIGHTcore . com

over there?
