From rca@dam Wed Mar 10 20:26:10 EST 2010 -0500
message-id: 
 <iugt7y7y97t7t7t87t087t8705t805085785085087508750875085085@rightcore.com>
x-mailer: junker-demsey hupmpty dumpty jumped over the wal to find
	all the kings men eating apples! (there is)
From: dam (David Morano)
From: guest
x-priority: 2 (moderate)
TO: dam
x-cc: dam
x-cc: pcs
X-FORWARDED-TO: dam
bcc: pcs,dam
x-Date: 18 Aug 2010 00:33:05 -0400 (EDT)
x-Date: 17 Aug 2010 09:9:9 -0400 (EDT)
x-subject: test other
status: O
bcc: dam
bcc: pcs
bcc: dam
bcc: pcs

This is the emergency broadcast system.

