From genserv Sat Apr 09 03:46:21 EDT 2005
return-path: genserv
content-length: 63              
x-mailer: PCS mkmsg
content-lines: 2
From: dmorano@ece.neu.edu
To: dmorano
Date: 9 Apr 2005 03:45:50 -0400 (EDT)
Subject: submit_job frodo

standard output
ECE frodo benchrun i64n4l1e0f vpr dir-optiflow
From genserv Sat Apr 09 06:39:52 EDT 2005
return-path: genserv
content-length: 67              
x-mailer: PCS mkmsg
content-lines: 2
From: dmorano@ece.neu.edu
To: dmorano
Date: 9 Apr 2005 06:39:20 -0400 (EDT)
Subject: submit_job frodo

standard output
ECE frodo benchrun i64n4l1e0f perlbmk dir-optiflow
