From gmail.com!coldspacemachine+caf_=dam=rightcore.com Sat Feb 22 11:34:34 USEST 2014 -0500
return-path:  <coldspacemachine+caf_=dam=rightcore.com@gmail.com>
received: from mail-ig0-f181.google.com (mail-ig0-f181.google.com 
	[209.85.213.181])
 by mail.rightcore.com (RCMAILER) with ESMTP id 7BA4A2EEF5
 for <dam@rightcore.com>; Sat, 22 Feb 2014 11:34:33 -0500 (USEST)
received: by mail-ig0-f181.google.com with SMTP id y6so1714820igj.2
 for <dam@rightcore.com>; Sat, 22 Feb 2014 08:34:31 -0800 (PST)
received: by 10.50.41.194 with SMTP id h2csp82015igl;
 Sat, 22 Feb 2014 08:34:29 -0800 (PST)
received: by 10.194.8.196 with HTTP; Sat, 22 Feb 2014 08:34:09 -0800 (PST)
content-length: 83                  
content-lines: 3                   
x-original-to: dam@rightcore.com
delivered-to: dam@rightcore.com
delivered-to: coldspacemachine@gmail.com
x-received: by 10.50.22.148 with SMTP id d20mr5972514igf.26.1393086871052;
 Sat, 22 Feb 2014 08:34:31 -0800 (PST)
x-received: from mr.google.com ([10.194.240.7])
 by 10.194.240.7 with SMTP id vw7mr13281859wjc.75.1393086869610 (num_hops = 
	1);
 Sat, 22 Feb 2014 08:34:29 -0800 (PST)
x-received: by 10.194.240.7 with SMTP id vw7mr11676113wjc.75.1393086869182;
 Sat, 22 Feb 2014 08:34:29 -0800 (PST)
x-forwarded-to: dam@rightcore.com
x-forwarded-for: coldspacemachine@gmail.com dam@rightcore.com
received-spf: pass (google.com: domain of eve.s.silver@gmail.com designates 
	10.194.240.7 as permitted sender) client-ip=10.194.240.7
authentication-results: mr.google.com;
 spf=pass (google.com: domain of eve.s.silver@gmail.com designates 
	10.194.240.7 as permitted sender) smtp.mail=eve.s.silver@gmail.com;
 dkim=pass header.i=@gmail.com
dkim-signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
 d=gmail.com; s=20120113;
 h=mime-version:sender:from:date:message-id:subject:to:content-type;
 bh=qTELEhTNBlWtn9sWFwZz//UE7tE1YQd2lR1r2VHyIJU=;
 b=LnDOqJSo34Q+f+MJDjoN8kdc2Y3OqUb6oonqydhfQFuu2P699X2chC5gjFKxpOCOJ7
 rOcaHwQ88gjip7SJUkOHp+Y+0G1ExuHU/MlAyFbZGGJcxSvY2vhcM4Tm9c4m2wu0rxe3
 s5/9Txpqa/MUGfhh0skUf37//3IzTOKIGUhjCdQS3wERuhKqfFSfJ6PmqckCCH+Ss6Vj
 bSQBk/9f3i9ob+m4v0Pauw1IxkvzyYm9cAcE1W26ms3eU8OclcV259Ow0uhkbm8qbVu/
 J00099Bj18n4Dmsd5c14BBwv6bUtCdppv0QNr7gluDIFcFmuRdUsHqylaHiV8VMrjmNr
 eG9A==
mime-version: 1.0
sender: eve.s.silver@gmail.com
x-google-sender-auth: oESdBk_SsFIfZY6cYUPAB6XYatQ
content-type: text/plain; charset=UTF-8
status: 
From:  Eve Silver <eve@evesilver.com>
To:  Dave Morano <morano@ieee.org>, David Morano
 <coldspacemachine@gmail.com>, David Morano <morano@acm.org>, David Morano
 <morano@computer.org>
Date: Sat, 22 Feb 2014 11:34:09 -0500
Subject: Hello my love

Is there any emailer taht you know about that is simpler than Google's Gmail?

Eve
